/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */
package view;

import javax.swing.*;

/**
 *
 * @author Herold
 */
public class Hinweis_option extends javax.swing.JFrame {

    /**
     * Creates new form Hinweis
     */
    public Hinweis_option() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    private void fensterschliessen()
    {
        this.setVisible(false);
        this.dispose();
        
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Teil_behaltenbtn = new javax.swing.JButton();
        Teil_entfbtn = new javax.swing.JButton();
        menge0lbl = new javax.swing.JLabel();
        entflbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Teil_behaltenbtn.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Teil_behaltenbtn.setText("Teil behalten");
        Teil_behaltenbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Teil_behaltenbtnActionPerformed(evt);
            }
        });

        Teil_entfbtn.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Teil_entfbtn.setText("Teil entfernen");
        Teil_entfbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Teil_entfbtnActionPerformed(evt);
            }
        });

        menge0lbl.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        menge0lbl.setText("Die Menge des ausgelagerten Teils fiel auf 0.");

        entflbl.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        entflbl.setText("Möchten Sie das Teil aus den Stammdaten entfernen?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Teil_behaltenbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Teil_entfbtn))
                    .addComponent(entflbl)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(menge0lbl)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(menge0lbl)
                .addGap(18, 18, 18)
                .addComponent(entflbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Teil_behaltenbtn)
                    .addComponent(Teil_entfbtn))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Teil_entfbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Teil_entfbtnActionPerformed

       System.out.println("Zu Teil entfernen Panel switchen");
       
       fensterschliessen();
        // TODO add your handling code here:
    }//GEN-LAST:event_Teil_entfbtnActionPerformed

    private void Teil_behaltenbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Teil_behaltenbtnActionPerformed

        fensterschliessen(); 
        // TODO add your handling code here:
    }//GEN-LAST:event_Teil_behaltenbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hinweis_option.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hinweis_option.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hinweis_option.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hinweis_option.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Hinweis_option().setVisible(true);
            }
        });
    }
    
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Teil_behaltenbtn;
    private javax.swing.JButton Teil_entfbtn;
    private javax.swing.JLabel entflbl;
    private javax.swing.JLabel menge0lbl;
    // End of variables declaration//GEN-END:variables
}
