/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */
package view;

/**
 *
 * @author Stephan
 */
public class Teile_entfernen_loeschen extends javax.swing.JFrame {

    /**
     * Creates new form Teile_entfernen_loeschen
     */
    public Teile_entfernen_loeschen() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        suchenButton = new javax.swing.JButton();
        Teilestammdatenbutton = new javax.swing.JButton();
        bestätigenButton = new javax.swing.JButton();
        IDTextfield = new javax.swing.JTextField();
        IDLabel = new javax.swing.JLabel();
        eingebenLabel = new javax.swing.JLabel();
        StammdatenLabel = new javax.swing.JLabel();
        BezeichnungLabel = new javax.swing.JLabel();
        TeileLabel = new javax.swing.JLabel();
        ZeichnungsnrLabel = new javax.swing.JLabel();
        MaterialgruppeLabel = new javax.swing.JLabel();
        BaugruppeLabel = new javax.swing.JLabel();
        PreisLabel = new javax.swing.JLabel();
        MAKLabel = new javax.swing.JLabel();
        MAMLabel = new javax.swing.JLabel();
        MAGLabel = new javax.swing.JLabel();
        BemerkungLabel = new javax.swing.JLabel();
        BezTextfield = new javax.swing.JTextField();
        TypTextfield = new javax.swing.JTextField();
        MaterialTextfield = new javax.swing.JTextField();
        ZNrTextfield = new javax.swing.JTextField();
        BaugruppeTextfield = new javax.swing.JTextField();
        BemerkungTextfield = new javax.swing.JTextField();
        MAGTextfield = new javax.swing.JTextField();
        MAMTextfield = new javax.swing.JTextField();
        MAKTextfield = new javax.swing.JTextField();
        PreisTextfield = new javax.swing.JTextField();
        EuroLabel = new javax.swing.JLabel();
        loeschenButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        Datei = new javax.swing.JMenu();
        Bearbeiten = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        suchenButton.setFont(new java.awt.Font("Arial", 0, 12));
        suchenButton.setText("Suchen");
        getContentPane().add(suchenButton);
        suchenButton.setBounds(404, 40, 129, 23);

        Teilestammdatenbutton.setFont(new java.awt.Font("Arial", 0, 12));
        Teilestammdatenbutton.setText("Teilestammdaten");
        getContentPane().add(Teilestammdatenbutton);
        Teilestammdatenbutton.setBounds(404, 81, 129, 23);

        bestätigenButton.setFont(new java.awt.Font("Arial", 0, 12));
        bestätigenButton.setText("Bestätigen");
        getContentPane().add(bestätigenButton);
        bestätigenButton.setBounds(151, 40, 91, 23);

        IDTextfield.setFont(new java.awt.Font("Arial", 0, 12));
        getContentPane().add(IDTextfield);
        IDTextfield.setBounds(52, 41, 93, 21);

        IDLabel.setFont(new java.awt.Font("Arial", 0, 12));
        IDLabel.setText("ID:");
        getContentPane().add(IDLabel);
        IDLabel.setBounds(27, 44, 15, 15);

        eingebenLabel.setFont(new java.awt.Font("Arial", 0, 12));
        eingebenLabel.setText("Bitte Teile ID eingeben:");
        getContentPane().add(eingebenLabel);
        eingebenLabel.setBounds(10, 11, 223, 15);

        StammdatenLabel.setFont(new java.awt.Font("Arial", 0, 12));
        StammdatenLabel.setText("Stammdaten:");
        getContentPane().add(StammdatenLabel);
        StammdatenLabel.setBounds(27, 124, 74, 15);

        BezeichnungLabel.setFont(new java.awt.Font("Arial", 0, 12));
        BezeichnungLabel.setText("Bezeichnung:");
        getContentPane().add(BezeichnungLabel);
        BezeichnungLabel.setBounds(27, 160, 74, 15);

        TeileLabel.setFont(new java.awt.Font("Arial", 0, 12));
        TeileLabel.setText("Teile Typ:");
        getContentPane().add(TeileLabel);
        TeileLabel.setBounds(27, 192, 52, 15);

        ZeichnungsnrLabel.setFont(new java.awt.Font("Arial", 0, 12));
        ZeichnungsnrLabel.setText("Zeichnungsnr.:");
        getContentPane().add(ZeichnungsnrLabel);
        ZeichnungsnrLabel.setBounds(27, 256, 82, 15);

        MaterialgruppeLabel.setFont(new java.awt.Font("Arial", 0, 12));
        MaterialgruppeLabel.setText("Materialgruppe:");
        getContentPane().add(MaterialgruppeLabel);
        MaterialgruppeLabel.setBounds(27, 224, 85, 15);

        BaugruppeLabel.setFont(new java.awt.Font("Arial", 0, 12));
        BaugruppeLabel.setText("Baugruppe:");
        getContentPane().add(BaugruppeLabel);
        BaugruppeLabel.setBounds(27, 286, 64, 15);

        PreisLabel.setFont(new java.awt.Font("Arial", 0, 12));
        PreisLabel.setText("Preis:");
        getContentPane().add(PreisLabel);
        PreisLabel.setBounds(319, 153, 32, 15);

        MAKLabel.setFont(new java.awt.Font("Arial", 0, 12));
        MAKLabel.setText("Max.Anzahl klein:");
        getContentPane().add(MAKLabel);
        MAKLabel.setBounds(319, 185, 92, 15);

        MAMLabel.setFont(new java.awt.Font("Arial", 0, 12));
        MAMLabel.setText("Max.Anzahl mittel:");
        getContentPane().add(MAMLabel);
        MAMLabel.setBounds(319, 217, 96, 15);

        MAGLabel.setFont(new java.awt.Font("Arial", 0, 12));
        MAGLabel.setText("Max.Anzahl groß:");
        getContentPane().add(MAGLabel);
        MAGLabel.setBounds(319, 249, 92, 15);

        BemerkungLabel.setFont(new java.awt.Font("Arial", 0, 12));
        BemerkungLabel.setText("Bemerkung");
        getContentPane().add(BemerkungLabel);
        BemerkungLabel.setBounds(319, 286, 64, 15);

        BezTextfield.setFont(new java.awt.Font("Arial", 0, 12));
        getContentPane().add(BezTextfield);
        BezTextfield.setBounds(141, 157, 98, 21);

        TypTextfield.setFont(new java.awt.Font("Arial", 0, 12));
        getContentPane().add(TypTextfield);
        TypTextfield.setBounds(141, 189, 98, 21);

        MaterialTextfield.setFont(new java.awt.Font("Arial", 0, 12));
        getContentPane().add(MaterialTextfield);
        MaterialTextfield.setBounds(141, 221, 98, 21);

        ZNrTextfield.setFont(new java.awt.Font("Arial", 0, 12));
        getContentPane().add(ZNrTextfield);
        ZNrTextfield.setBounds(141, 253, 98, 21);

        BaugruppeTextfield.setFont(new java.awt.Font("Arial", 0, 12));
        getContentPane().add(BaugruppeTextfield);
        BaugruppeTextfield.setBounds(141, 280, 98, 21);

        BemerkungTextfield.setFont(new java.awt.Font("Arial", 0, 12));
        getContentPane().add(BemerkungTextfield);
        BemerkungTextfield.setBounds(435, 278, 98, 21);

        MAGTextfield.setFont(new java.awt.Font("Arial", 0, 12));
        getContentPane().add(MAGTextfield);
        MAGTextfield.setBounds(435, 246, 98, 21);

        MAMTextfield.setFont(new java.awt.Font("Arial", 0, 12));
        getContentPane().add(MAMTextfield);
        MAMTextfield.setBounds(433, 214, 100, 21);

        MAKTextfield.setFont(new java.awt.Font("Arial", 0, 12));
        getContentPane().add(MAKTextfield);
        MAKTextfield.setBounds(433, 182, 100, 21);

        PreisTextfield.setFont(new java.awt.Font("Arial", 0, 12));
        getContentPane().add(PreisTextfield);
        PreisTextfield.setBounds(433, 150, 100, 21);

        EuroLabel.setFont(new java.awt.Font("Arial", 0, 12));
        EuroLabel.setText("€");
        getContentPane().add(EuroLabel);
        EuroLabel.setBounds(537, 153, 21, 15);

        loeschenButton.setFont(new java.awt.Font("Arial", 0, 12));
        loeschenButton.setText("Löschen");
        getContentPane().add(loeschenButton);
        loeschenButton.setBounds(452, 330, 81, 23);

        Datei.setText("Datei");
        jMenuBar1.add(Datei);

        Bearbeiten.setText("Edit");
        jMenuBar1.add(Bearbeiten);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teile_entfernen_loeschen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teile_entfernen_loeschen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teile_entfernen_loeschen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teile_entfernen_loeschen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Teile_entfernen_loeschen().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BaugruppeLabel;
    private javax.swing.JTextField BaugruppeTextfield;
    private javax.swing.JMenu Bearbeiten;
    private javax.swing.JLabel BemerkungLabel;
    private javax.swing.JTextField BemerkungTextfield;
    private javax.swing.JTextField BezTextfield;
    private javax.swing.JLabel BezeichnungLabel;
    private javax.swing.JMenu Datei;
    private javax.swing.JLabel EuroLabel;
    private javax.swing.JLabel IDLabel;
    private javax.swing.JTextField IDTextfield;
    private javax.swing.JLabel MAGLabel;
    private javax.swing.JTextField MAGTextfield;
    private javax.swing.JLabel MAKLabel;
    private javax.swing.JTextField MAKTextfield;
    private javax.swing.JLabel MAMLabel;
    private javax.swing.JTextField MAMTextfield;
    private javax.swing.JTextField MaterialTextfield;
    private javax.swing.JLabel MaterialgruppeLabel;
    private javax.swing.JLabel PreisLabel;
    private javax.swing.JTextField PreisTextfield;
    private javax.swing.JLabel StammdatenLabel;
    private javax.swing.JLabel TeileLabel;
    private javax.swing.JButton Teilestammdatenbutton;
    private javax.swing.JTextField TypTextfield;
    private javax.swing.JTextField ZNrTextfield;
    private javax.swing.JLabel ZeichnungsnrLabel;
    private javax.swing.JButton bestätigenButton;
    private javax.swing.JLabel eingebenLabel;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton loeschenButton;
    private javax.swing.JButton suchenButton;
    // End of variables declaration//GEN-END:variables
}
