/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */
package view;

/**
 *
 * @author Stephan
 */
public class Teile_auslagern extends javax.swing.JFrame {

    /**
     * Creates new form Teile_auslagern
     */
    public Teile_auslagern() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TeileIDLabel = new javax.swing.JLabel();
        BezeichnungLabel = new javax.swing.JLabel();
        FachLabel = new javax.swing.JLabel();
        BestandverringernLabel = new javax.swing.JLabel();
        BemerkungLabel = new javax.swing.JLabel();
        IDTextfield = new javax.swing.JTextField();
        BezeichnungTextfield = new javax.swing.JTextField();
        FachTextfield = new javax.swing.JTextField();
        BestandTextfield = new javax.swing.JTextField();
        FachinhaltTextfield = new javax.swing.JTextField();
        AusführenButton = new javax.swing.JButton();
        SuchenButton = new javax.swing.JButton();
        BemerkungTextfield = new javax.swing.JTextField();
        MengeTextfield = new javax.swing.JTextField();
        MengeLabel = new javax.swing.JLabel();
        BestätigenButton = new javax.swing.JButton();
        FachnhaltLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Datei = new javax.swing.JMenu();
        Bearbeiten = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TeileIDLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TeileIDLabel.setText("Teile ID:");

        BezeichnungLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        BezeichnungLabel.setText("Bezeichnung:");

        FachLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        FachLabel.setText("Fach:");

        BestandverringernLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        BestandverringernLabel.setText("Bestand verringern:");

        BemerkungLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        BemerkungLabel.setText("Bemerkung:");

        IDTextfield.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        BezeichnungTextfield.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        FachTextfield.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        BestandTextfield.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        BestandTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BestandTextfieldActionPerformed(evt);
            }
        });

        FachinhaltTextfield.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        AusführenButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        AusführenButton.setText("Ausführen");

        SuchenButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        SuchenButton.setText("Suchen");

        BemerkungTextfield.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        MengeTextfield.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        MengeLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        MengeLabel.setText("Menge:");

        BestätigenButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        BestätigenButton.setText("Bestätigen");
        BestätigenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BestätigenButtonActionPerformed(evt);
            }
        });

        FachnhaltLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        FachnhaltLabel.setText("Fachinhalt:");

        Datei.setText("Datei");
        jMenuBar1.add(Datei);

        Bearbeiten.setText("Bearbeiten");
        jMenuBar1.add(Bearbeiten);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TeileIDLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BezeichnungLabel)
                            .addComponent(FachLabel)
                            .addComponent(BestandverringernLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BezeichnungTextfield)
                            .addComponent(FachTextfield)
                            .addComponent(IDTextfield)
                            .addComponent(BestandTextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BemerkungLabel)
                            .addComponent(FachnhaltLabel)
                            .addComponent(AusführenButton)
                            .addComponent(BestätigenButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BemerkungTextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(FachinhaltTextfield))
                        .addGap(62, 62, 62)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MengeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SuchenButton)
                    .addComponent(MengeTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TeileIDLabel)
                    .addComponent(IDTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BestätigenButton)
                    .addComponent(SuchenButton))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BezeichnungLabel)
                    .addComponent(BemerkungLabel)
                    .addComponent(BezeichnungTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BemerkungTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FachLabel)
                            .addComponent(FachTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FachnhaltLabel))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BestandverringernLabel)
                            .addComponent(BestandTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AusführenButton)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(FachinhaltTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(MengeTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(MengeLabel)))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BestätigenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BestätigenButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BestätigenButtonActionPerformed

    private void BestandTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BestandTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BestandTextfieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teile_auslagern.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teile_auslagern.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teile_auslagern.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teile_auslagern.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Teile_auslagern().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AusführenButton;
    private javax.swing.JMenu Bearbeiten;
    private javax.swing.JLabel BemerkungLabel;
    private javax.swing.JTextField BemerkungTextfield;
    private javax.swing.JTextField BestandTextfield;
    private javax.swing.JLabel BestandverringernLabel;
    private javax.swing.JButton BestätigenButton;
    private javax.swing.JLabel BezeichnungLabel;
    private javax.swing.JTextField BezeichnungTextfield;
    private javax.swing.JMenu Datei;
    private javax.swing.JLabel FachLabel;
    private javax.swing.JTextField FachTextfield;
    private javax.swing.JTextField FachinhaltTextfield;
    private javax.swing.JLabel FachnhaltLabel;
    private javax.swing.JTextField IDTextfield;
    private javax.swing.JLabel MengeLabel;
    private javax.swing.JTextField MengeTextfield;
    private javax.swing.JButton SuchenButton;
    private javax.swing.JLabel TeileIDLabel;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
