/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */
package view;

/**
 *
 * @author Stephan
 */
public class Teile_Suchen extends javax.swing.JFrame {

    /**
     * Creates new form Teile_Suchen
     */
    public Teile_Suchen() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Panellinks = new javax.swing.JPanel();
        TeileStammdatenLabel = new javax.swing.JLabel();
        IDlinksLabel = new javax.swing.JLabel();
        BezeichnungLabel = new javax.swing.JLabel();
        TeiletypLabel = new javax.swing.JLabel();
        MaterialgruppeLabel = new javax.swing.JLabel();
        ZeichnungsnrLabel = new javax.swing.JLabel();
        BaugruppeLabel = new javax.swing.JLabel();
        MAGLabel = new javax.swing.JLabel();
        MAMLabel = new javax.swing.JLabel();
        MAKLabel = new javax.swing.JLabel();
        PreisLabel = new javax.swing.JLabel();
        IDTextfield = new javax.swing.JTextField();
        BezTextfield = new javax.swing.JTextField();
        MaterialTextfield = new javax.swing.JTextField();
        ZNrTextfield = new javax.swing.JTextField();
        TeiletypTextfield = new javax.swing.JTextField();
        BaugruppeTextfield = new javax.swing.JTextField();
        PreisTextfield = new javax.swing.JTextField();
        MAKTextfield = new javax.swing.JTextField();
        MAMTextfield = new javax.swing.JTextField();
        MAGTextfield = new javax.swing.JTextField();
        SuchenlinksButton = new javax.swing.JButton();
        EuroLabel = new javax.swing.JLabel();
        Panelrechts = new javax.swing.JPanel();
        LagerbestandLabel = new javax.swing.JLabel();
        MinMengeLabel = new javax.swing.JLabel();
        MaxMengeLabel = new javax.swing.JLabel();
        HaltbarkeitsLabel = new javax.swing.JLabel();
        FachnrLabel = new javax.swing.JLabel();
        TeileIDLabel = new javax.swing.JLabel();
        SuchenrechtsButton = new javax.swing.JButton();
        LagerbestandTextfield = new javax.swing.JTextField();
        MinTextfield = new javax.swing.JTextField();
        MaxTextfield = new javax.swing.JTextField();
        DatumTextfield = new javax.swing.JTextField();
        FachnrTextfield = new javax.swing.JTextField();
        TeileIDrechtsTextfield = new javax.swing.JTextField();
        Panelmitte = new javax.swing.JPanel();
        LagerfachbestandLabel = new javax.swing.JLabel();
        LagerortLabel = new javax.swing.JLabel();
        RegalnrLabel = new javax.swing.JLabel();
        ZeileLabel = new javax.swing.JLabel();
        SpalteLabel = new javax.swing.JLabel();
        BelegtLabel = new javax.swing.JLabel();
        GrößeLabel = new javax.swing.JLabel();
        SuchenmitteButton = new javax.swing.JButton();
        neinCB = new javax.swing.JCheckBox();
        jaCB = new javax.swing.JCheckBox();
        mCB = new javax.swing.JCheckBox();
        gCB = new javax.swing.JCheckBox();
        kCB = new javax.swing.JCheckBox();
        ZeileTextfield = new javax.swing.JTextField();
        SpalteTextfield = new javax.swing.JTextField();
        H1CB = new javax.swing.JCheckBox();
        H2CB = new javax.swing.JCheckBox();
        H4CB = new javax.swing.JCheckBox();
        H3CB = new javax.swing.JCheckBox();
        FCB = new javax.swing.JCheckBox();
        HCB = new javax.swing.JCheckBox();
        LagerfachbestandTextfield = new javax.swing.JTextField();
        H5CB = new javax.swing.JCheckBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        Datei = new javax.swing.JMenu();
        Bearbeiten = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 299, 1157, 160);

        Panellinks.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TeileStammdatenLabel.setFont(new java.awt.Font("Arial", 0, 12));
        TeileStammdatenLabel.setText("Teile Stammdaten:");

        IDlinksLabel.setFont(new java.awt.Font("Arial", 0, 12));
        IDlinksLabel.setText("ID:");

        BezeichnungLabel.setFont(new java.awt.Font("Arial", 0, 12));
        BezeichnungLabel.setText("Bezeichnung:");

        TeiletypLabel.setFont(new java.awt.Font("Arial", 0, 12));
        TeiletypLabel.setText("Teiletyp:");

        MaterialgruppeLabel.setFont(new java.awt.Font("Arial", 0, 12));
        MaterialgruppeLabel.setText("Materialgrupe:");

        ZeichnungsnrLabel.setFont(new java.awt.Font("Arial", 0, 12));
        ZeichnungsnrLabel.setText("Zeichnungsnr.:");

        BaugruppeLabel.setFont(new java.awt.Font("Arial", 0, 12));
        BaugruppeLabel.setText("Baugruppe:");

        MAGLabel.setFont(new java.awt.Font("Arial", 0, 12));
        MAGLabel.setText("MAG:");

        MAMLabel.setFont(new java.awt.Font("Arial", 0, 12));
        MAMLabel.setText("MAM:");

        MAKLabel.setFont(new java.awt.Font("Arial", 0, 12));
        MAKLabel.setText("MAK:");

        PreisLabel.setFont(new java.awt.Font("Arial", 0, 12));
        PreisLabel.setText("Preis:");

        IDTextfield.setFont(new java.awt.Font("Arial", 0, 12));

        BezTextfield.setFont(new java.awt.Font("Arial", 0, 12));

        MaterialTextfield.setFont(new java.awt.Font("Arial", 0, 12));

        ZNrTextfield.setFont(new java.awt.Font("Arial", 0, 12));

        TeiletypTextfield.setFont(new java.awt.Font("Arial", 0, 12));

        BaugruppeTextfield.setFont(new java.awt.Font("Arial", 0, 12));

        PreisTextfield.setFont(new java.awt.Font("Arial", 0, 12));

        MAKTextfield.setFont(new java.awt.Font("Arial", 0, 12));

        MAMTextfield.setFont(new java.awt.Font("Arial", 0, 12));

        MAGTextfield.setFont(new java.awt.Font("Arial", 0, 12));

        SuchenlinksButton.setFont(new java.awt.Font("Arial", 0, 12));
        SuchenlinksButton.setText("Suchen");

        EuroLabel.setText("€");

        javax.swing.GroupLayout PanellinksLayout = new javax.swing.GroupLayout(Panellinks);
        Panellinks.setLayout(PanellinksLayout);
        PanellinksLayout.setHorizontalGroup(
            PanellinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanellinksLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanellinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanellinksLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(SuchenlinksButton))
                    .addGroup(PanellinksLayout.createSequentialGroup()
                        .addGroup(PanellinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TeileStammdatenLabel)
                            .addGroup(PanellinksLayout.createSequentialGroup()
                                .addGroup(PanellinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanellinksLayout.createSequentialGroup()
                                        .addGroup(PanellinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(MaterialgruppeLabel)
                                            .addComponent(BezeichnungLabel)
                                            .addComponent(TeiletypLabel)
                                            .addComponent(ZeichnungsnrLabel)
                                            .addComponent(BaugruppeLabel))
                                        .addGap(18, 18, 18)
                                        .addGroup(PanellinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(MaterialTextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                            .addComponent(BezTextfield)
                                            .addComponent(ZNrTextfield)
                                            .addComponent(TeiletypTextfield)
                                            .addComponent(BaugruppeTextfield))
                                        .addGap(29, 29, 29)
                                        .addGroup(PanellinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(PreisLabel)
                                            .addComponent(MAGLabel)
                                            .addComponent(MAMLabel)
                                            .addComponent(MAKLabel)))
                                    .addGroup(PanellinksLayout.createSequentialGroup()
                                        .addComponent(IDlinksLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(IDTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(PanellinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MAKTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MAMTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MAGTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(PanellinksLayout.createSequentialGroup()
                                        .addComponent(PreisTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(EuroLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 37, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanellinksLayout.setVerticalGroup(
            PanellinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanellinksLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TeileStammdatenLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanellinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDlinksLabel)
                    .addComponent(IDTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(PanellinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BezeichnungLabel)
                    .addComponent(BezTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(PanellinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanellinksLayout.createSequentialGroup()
                        .addGroup(PanellinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PreisLabel)
                            .addComponent(PreisTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EuroLabel))
                        .addGap(43, 43, 43)
                        .addGroup(PanellinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MAMLabel)
                            .addComponent(MAMTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(PanellinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MAGLabel)
                            .addComponent(MAGTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PanellinksLayout.createSequentialGroup()
                        .addGroup(PanellinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanellinksLayout.createSequentialGroup()
                                .addComponent(TeiletypLabel)
                                .addGap(12, 12, 12)
                                .addGroup(PanellinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(MaterialgruppeLabel)
                                    .addComponent(ZNrTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MAKTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MAKLabel)))
                            .addComponent(MaterialTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanellinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ZeichnungsnrLabel)
                            .addComponent(TeiletypTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanellinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BaugruppeLabel)
                            .addComponent(BaugruppeTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(SuchenlinksButton)))
                .addContainerGap())
        );

        getContentPane().add(Panellinks);
        Panellinks.setBounds(0, 0, 469, 293);

        Panelrechts.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        LagerbestandLabel.setFont(new java.awt.Font("Arial", 0, 12));
        LagerbestandLabel.setText("Lagerbestand:");

        MinMengeLabel.setFont(new java.awt.Font("Arial", 0, 12));
        MinMengeLabel.setText("Mind. Menge im Fach:");

        MaxMengeLabel.setFont(new java.awt.Font("Arial", 0, 12));
        MaxMengeLabel.setText("Max. Menge im Fach:");

        HaltbarkeitsLabel.setFont(new java.awt.Font("Arial", 0, 12));
        HaltbarkeitsLabel.setText("Haltbarkeitsdatum:");

        FachnrLabel.setFont(new java.awt.Font("Arial", 0, 12));
        FachnrLabel.setText("Fachnummer:");

        TeileIDLabel.setFont(new java.awt.Font("Arial", 0, 12));
        TeileIDLabel.setText("Teile ID:");

        SuchenrechtsButton.setFont(new java.awt.Font("Arial", 0, 12));
        SuchenrechtsButton.setText("Suchen");

        LagerbestandTextfield.setFont(new java.awt.Font("Arial", 0, 12));

        MinTextfield.setFont(new java.awt.Font("Arial", 0, 12));

        MaxTextfield.setFont(new java.awt.Font("Arial", 0, 12));

        DatumTextfield.setFont(new java.awt.Font("Arial", 0, 12));

        FachnrTextfield.setFont(new java.awt.Font("Arial", 0, 12));

        TeileIDrechtsTextfield.setFont(new java.awt.Font("Arial", 0, 12));

        javax.swing.GroupLayout PanelrechtsLayout = new javax.swing.GroupLayout(Panelrechts);
        Panelrechts.setLayout(PanelrechtsLayout);
        PanelrechtsLayout.setHorizontalGroup(
            PanelrechtsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelrechtsLayout.createSequentialGroup()
                .addGroup(PanelrechtsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelrechtsLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(PanelrechtsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FachnrLabel)
                            .addComponent(TeileIDLabel)
                            .addComponent(HaltbarkeitsLabel)
                            .addComponent(MaxMengeLabel)
                            .addComponent(MinMengeLabel)
                            .addComponent(LagerbestandLabel))
                        .addGap(44, 44, 44)
                        .addGroup(PanelrechtsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MinTextfield)
                            .addComponent(MaxTextfield)
                            .addComponent(DatumTextfield)
                            .addComponent(FachnrTextfield)
                            .addComponent(TeileIDrechtsTextfield)
                            .addComponent(LagerbestandTextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelrechtsLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SuchenrechtsButton)))
                .addContainerGap())
        );
        PanelrechtsLayout.setVerticalGroup(
            PanelrechtsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelrechtsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelrechtsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LagerbestandLabel)
                    .addComponent(LagerbestandTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelrechtsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MinMengeLabel)
                    .addComponent(MinTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelrechtsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MaxMengeLabel)
                    .addComponent(MaxTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelrechtsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HaltbarkeitsLabel)
                    .addComponent(DatumTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelrechtsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FachnrLabel)
                    .addComponent(FachnrTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelrechtsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TeileIDLabel)
                    .addComponent(TeileIDrechtsTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(SuchenrechtsButton)
                .addContainerGap())
        );

        getContentPane().add(Panelrechts);
        Panelrechts.setBounds(826, 0, 331, 293);

        Panelmitte.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        LagerfachbestandLabel.setFont(new java.awt.Font("Arial", 0, 12));
        LagerfachbestandLabel.setText("Lagerfachbestand:");

        LagerortLabel.setFont(new java.awt.Font("Arial", 0, 12));
        LagerortLabel.setText("Lagerort:");

        RegalnrLabel.setFont(new java.awt.Font("Arial", 0, 12));
        RegalnrLabel.setText("Regalnr.:");

        ZeileLabel.setFont(new java.awt.Font("Arial", 0, 12));
        ZeileLabel.setText("Zeile:");

        SpalteLabel.setFont(new java.awt.Font("Arial", 0, 12));
        SpalteLabel.setText("Spalte:");

        BelegtLabel.setFont(new java.awt.Font("Arial", 0, 12));
        BelegtLabel.setText("Belegt:");

        GrößeLabel.setFont(new java.awt.Font("Arial", 0, 12));
        GrößeLabel.setText("Größe:");

        SuchenmitteButton.setFont(new java.awt.Font("Arial", 0, 12));
        SuchenmitteButton.setText("Suchen");

        neinCB.setFont(new java.awt.Font("Arial", 0, 12));
        neinCB.setText("nein");

        jaCB.setFont(new java.awt.Font("Arial", 0, 12));
        jaCB.setText("ja");

        mCB.setFont(new java.awt.Font("Arial", 0, 12));
        mCB.setText("M");
        mCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCBActionPerformed(evt);
            }
        });

        gCB.setFont(new java.awt.Font("Arial", 0, 12));
        gCB.setText("G");

        kCB.setFont(new java.awt.Font("Arial", 0, 12));
        kCB.setText("K");

        ZeileTextfield.setFont(new java.awt.Font("Arial", 0, 12));

        SpalteTextfield.setFont(new java.awt.Font("Arial", 0, 12));

        H1CB.setFont(new java.awt.Font("Arial", 0, 12));
        H1CB.setText("H1");

        H2CB.setFont(new java.awt.Font("Arial", 0, 12));
        H2CB.setText("H2");

        H4CB.setFont(new java.awt.Font("Arial", 0, 12));
        H4CB.setText("H4");

        H3CB.setFont(new java.awt.Font("Arial", 0, 12));
        H3CB.setText("H3");

        FCB.setFont(new java.awt.Font("Arial", 0, 12));
        FCB.setText("F");

        HCB.setFont(new java.awt.Font("Arial", 0, 12));
        HCB.setText("H");

        LagerfachbestandTextfield.setFont(new java.awt.Font("Arial", 0, 12));

        H5CB.setFont(new java.awt.Font("Arial", 0, 12));
        H5CB.setText("H5");

        javax.swing.GroupLayout PanelmitteLayout = new javax.swing.GroupLayout(Panelmitte);
        Panelmitte.setLayout(PanelmitteLayout);
        PanelmitteLayout.setHorizontalGroup(
            PanelmitteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelmitteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelmitteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelmitteLayout.createSequentialGroup()
                        .addGroup(PanelmitteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelmitteLayout.createSequentialGroup()
                                .addComponent(GrößeLabel)
                                .addGap(34, 34, 34)
                                .addComponent(kCB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(mCB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(gCB))
                            .addGroup(PanelmitteLayout.createSequentialGroup()
                                .addComponent(BelegtLabel)
                                .addGap(34, 34, 34)
                                .addComponent(jaCB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(neinCB))
                            .addGroup(PanelmitteLayout.createSequentialGroup()
                                .addGroup(PanelmitteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LagerfachbestandLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelmitteLayout.createSequentialGroup()
                                        .addComponent(LagerortLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(FCB)))
                                .addGap(18, 18, 18)
                                .addComponent(LagerfachbestandTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelmitteLayout.createSequentialGroup()
                                .addGroup(PanelmitteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SpalteLabel)
                                    .addComponent(ZeileLabel)
                                    .addComponent(RegalnrLabel))
                                .addGap(18, 18, 18)
                                .addGroup(PanelmitteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelmitteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(SpalteTextfield, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                                        .addComponent(ZeileTextfield, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGroup(PanelmitteLayout.createSequentialGroup()
                                        .addComponent(H1CB)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(PanelmitteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(HCB)
                                            .addGroup(PanelmitteLayout.createSequentialGroup()
                                                .addComponent(H2CB)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(H3CB)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(H4CB)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(H5CB)))))))
                        .addGap(0, 42, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelmitteLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(SuchenmitteButton)))
                .addContainerGap())
        );
        PanelmitteLayout.setVerticalGroup(
            PanelmitteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelmitteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelmitteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LagerfachbestandLabel)
                    .addComponent(LagerfachbestandTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelmitteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LagerortLabel)
                    .addComponent(FCB)
                    .addComponent(HCB))
                .addGap(8, 8, 8)
                .addGroup(PanelmitteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegalnrLabel)
                    .addComponent(H1CB)
                    .addComponent(H2CB)
                    .addComponent(H3CB)
                    .addComponent(H4CB)
                    .addComponent(H5CB))
                .addGap(18, 18, 18)
                .addGroup(PanelmitteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelmitteLayout.createSequentialGroup()
                        .addGroup(PanelmitteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ZeileLabel)
                            .addComponent(ZeileTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(PanelmitteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SpalteLabel)
                            .addComponent(SpalteTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelmitteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BelegtLabel)
                            .addComponent(jaCB)
                            .addComponent(neinCB))
                        .addGap(18, 18, 18)
                        .addGroup(PanelmitteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GrößeLabel)
                            .addComponent(kCB)
                            .addComponent(mCB)
                            .addComponent(gCB))
                        .addGap(0, 25, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelmitteLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(SuchenmitteButton)))
                .addContainerGap())
        );

        getContentPane().add(Panelmitte);
        Panelmitte.setBounds(475, 0, 345, 293);

        Datei.setText("Datei");
        jMenuBar1.add(Datei);

        Bearbeiten.setText("Bearbeiten");
        jMenuBar1.add(Bearbeiten);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mCBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teile_Suchen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teile_Suchen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teile_Suchen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teile_Suchen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Teile_Suchen().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BaugruppeLabel;
    private javax.swing.JTextField BaugruppeTextfield;
    private javax.swing.JMenu Bearbeiten;
    private javax.swing.JLabel BelegtLabel;
    private javax.swing.JTextField BezTextfield;
    private javax.swing.JLabel BezeichnungLabel;
    private javax.swing.JMenu Datei;
    private javax.swing.JTextField DatumTextfield;
    private javax.swing.JLabel EuroLabel;
    private javax.swing.JCheckBox FCB;
    private javax.swing.JLabel FachnrLabel;
    private javax.swing.JTextField FachnrTextfield;
    private javax.swing.JLabel GrößeLabel;
    private javax.swing.JCheckBox H1CB;
    private javax.swing.JCheckBox H2CB;
    private javax.swing.JCheckBox H3CB;
    private javax.swing.JCheckBox H4CB;
    private javax.swing.JCheckBox H5CB;
    private javax.swing.JCheckBox HCB;
    private javax.swing.JLabel HaltbarkeitsLabel;
    private javax.swing.JTextField IDTextfield;
    private javax.swing.JLabel IDlinksLabel;
    private javax.swing.JLabel LagerbestandLabel;
    private javax.swing.JTextField LagerbestandTextfield;
    private javax.swing.JLabel LagerfachbestandLabel;
    private javax.swing.JTextField LagerfachbestandTextfield;
    private javax.swing.JLabel LagerortLabel;
    private javax.swing.JLabel MAGLabel;
    private javax.swing.JTextField MAGTextfield;
    private javax.swing.JLabel MAKLabel;
    private javax.swing.JTextField MAKTextfield;
    private javax.swing.JLabel MAMLabel;
    private javax.swing.JTextField MAMTextfield;
    private javax.swing.JTextField MaterialTextfield;
    private javax.swing.JLabel MaterialgruppeLabel;
    private javax.swing.JLabel MaxMengeLabel;
    private javax.swing.JTextField MaxTextfield;
    private javax.swing.JLabel MinMengeLabel;
    private javax.swing.JTextField MinTextfield;
    private javax.swing.JPanel Panellinks;
    private javax.swing.JPanel Panelmitte;
    private javax.swing.JPanel Panelrechts;
    private javax.swing.JLabel PreisLabel;
    private javax.swing.JTextField PreisTextfield;
    private javax.swing.JLabel RegalnrLabel;
    private javax.swing.JLabel SpalteLabel;
    private javax.swing.JTextField SpalteTextfield;
    private javax.swing.JButton SuchenlinksButton;
    private javax.swing.JButton SuchenmitteButton;
    private javax.swing.JButton SuchenrechtsButton;
    private javax.swing.JLabel TeileIDLabel;
    private javax.swing.JTextField TeileIDrechtsTextfield;
    private javax.swing.JLabel TeileStammdatenLabel;
    private javax.swing.JLabel TeiletypLabel;
    private javax.swing.JTextField TeiletypTextfield;
    private javax.swing.JTextField ZNrTextfield;
    private javax.swing.JLabel ZeichnungsnrLabel;
    private javax.swing.JLabel ZeileLabel;
    private javax.swing.JTextField ZeileTextfield;
    private javax.swing.JCheckBox gCB;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JCheckBox jaCB;
    private javax.swing.JCheckBox kCB;
    private javax.swing.JCheckBox mCB;
    private javax.swing.JCheckBox neinCB;
    // End of variables declaration//GEN-END:variables
}
