/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */
package view;

/**
 *
 * @author Stephan
 */
public class Teile_umlagern extends javax.swing.JFrame {

    /**
     * Creates new form Teile_umlagern
     */
    public Teile_umlagern() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BitteeingebenLabel = new javax.swing.JLabel();
        FachnummerLabel = new javax.swing.JLabel();
        TeileLabel = new javax.swing.JLabel();
        ZielfachLabel = new javax.swing.JLabel();
        FachnrTextfield = new javax.swing.JTextField();
        BestätigenButton = new javax.swing.JButton();
        IDTextfield = new javax.swing.JTextField();
        BezeichnungLabel = new javax.swing.JLabel();
        BezeichnungTextfield = new javax.swing.JTextField();
        MengeLabel = new javax.swing.JLabel();
        MengeTextfield = new javax.swing.JTextField();
        FachnrLabel_Ziel = new javax.swing.JLabel();
        FachnrTextfield_Ziel = new javax.swing.JTextField();
        UmlagernButton = new javax.swing.JButton();
        SuchenButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        Datei = new javax.swing.JMenu();
        Bearbeiten = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BitteeingebenLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        BitteeingebenLabel.setText("Bitte geben Sie die Fachnummer ein:");

        FachnummerLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        FachnummerLabel.setText("Fachnummer:");

        TeileLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TeileLabel.setText("Teile ID:");

        ZielfachLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ZielfachLabel.setText("Bitte geben Sie das Zielfach ein:");

        FachnrTextfield.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        BestätigenButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        BestätigenButton.setText("Bestätigen");

        IDTextfield.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        BezeichnungLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        BezeichnungLabel.setText("Bezeichnung:");

        BezeichnungTextfield.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        BezeichnungTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BezeichnungTextfieldActionPerformed(evt);
            }
        });

        MengeLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        MengeLabel.setText("Menge:");

        MengeTextfield.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        FachnrLabel_Ziel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        FachnrLabel_Ziel.setText("Fachnummer:");

        FachnrTextfield_Ziel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        UmlagernButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        UmlagernButton.setText("Umlagern");

        SuchenButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        SuchenButton.setText("Suchen");

        Datei.setText("Datei");
        jMenuBar1.add(Datei);

        Bearbeiten.setText("Bearbeiten");
        jMenuBar1.add(Bearbeiten);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BitteeingebenLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ZielfachLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(FachnrTextfield_Ziel, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(TeileLabel)
                                        .addGap(69, 69, 69)
                                        .addComponent(IDTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(FachnummerLabel)
                                        .addGap(37, 37, 37)
                                        .addComponent(FachnrTextfield))))
                            .addComponent(FachnrLabel_Ziel))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BestätigenButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BezeichnungLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BezeichnungTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(24, 24, 24)
                                        .addComponent(MengeLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(MengeTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(SuchenButton)))
                            .addComponent(UmlagernButton))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BitteeingebenLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FachnummerLabel)
                    .addComponent(FachnrTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BestätigenButton)
                    .addComponent(SuchenButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TeileLabel)
                    .addComponent(IDTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BezeichnungTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MengeLabel)
                    .addComponent(MengeTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BezeichnungLabel))
                .addGap(38, 38, 38)
                .addComponent(ZielfachLabel)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FachnrLabel_Ziel)
                    .addComponent(FachnrTextfield_Ziel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UmlagernButton))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BezeichnungTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BezeichnungTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BezeichnungTextfieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teile_umlagern.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teile_umlagern.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teile_umlagern.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teile_umlagern.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Teile_umlagern().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Bearbeiten;
    private javax.swing.JButton BestätigenButton;
    private javax.swing.JLabel BezeichnungLabel;
    private javax.swing.JTextField BezeichnungTextfield;
    private javax.swing.JLabel BitteeingebenLabel;
    private javax.swing.JMenu Datei;
    private javax.swing.JLabel FachnrLabel_Ziel;
    private javax.swing.JTextField FachnrTextfield;
    private javax.swing.JTextField FachnrTextfield_Ziel;
    private javax.swing.JLabel FachnummerLabel;
    private javax.swing.JTextField IDTextfield;
    private javax.swing.JLabel MengeLabel;
    private javax.swing.JTextField MengeTextfield;
    private javax.swing.JButton SuchenButton;
    private javax.swing.JLabel TeileLabel;
    private javax.swing.JButton UmlagernButton;
    private javax.swing.JLabel ZielfachLabel;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
