/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */
package view;

import control.Suchen_Controller;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Teil_Stammdaten;
import model.TeileTypET;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.*;

/**
 *
 * @author Matthias Sommer
 */
public class Teil_Suchen extends javax.swing.JFrame {

    private Suchen_Controller suchen_controller;

    /**
     * Creates new form Teil_Suchen
     */
    public Teil_Suchen() {
        initComponents();
        suchen_controller = new Suchen_Controller();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        suche_Fach_lagerplatz = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        LagerortLabel = new javax.swing.JLabel();
        LagerfachbestandLabel = new javax.swing.JLabel();
        ZeileLabel = new javax.swing.JLabel();
        RegalnrLabel = new javax.swing.JLabel();
        BelegtLabel = new javax.swing.JLabel();
        SpalteLabel = new javax.swing.JLabel();
        FCB = new javax.swing.JCheckBox();
        H3CB = new javax.swing.JCheckBox();
        H1CB = new javax.swing.JCheckBox();
        H4CB = new javax.swing.JCheckBox();
        H2CB = new javax.swing.JCheckBox();
        HCB = new javax.swing.JCheckBox();
        gCB = new javax.swing.JCheckBox();
        GrößeLabel = new javax.swing.JLabel();
        mCB = new javax.swing.JCheckBox();
        SuchenmitteButton = new javax.swing.JButton();
        neinCB = new javax.swing.JCheckBox();
        kCB = new javax.swing.JCheckBox();
        jaCB = new javax.swing.JCheckBox();
        H5CB = new javax.swing.JCheckBox();
        zeile_label = new javax.swing.JLabel();
        spalte_label = new javax.swing.JLabel();
        lagerTextfield1 = new view.LagerTextfield();
        lagerTextfield2 = new view.LagerTextfield();
        lagerTextfield3 = new view.LagerTextfield();
        suche_Inhalt = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        TeileIDLabel = new javax.swing.JLabel();
        SuchenrechtsButton = new javax.swing.JButton();
        FachnrLabel = new javax.swing.JLabel();
        HaltbarkeitsLabel = new javax.swing.JLabel();
        MaxMengeLabel = new javax.swing.JLabel();
        MinMengeLabel = new javax.swing.JLabel();
        LagerbestandLabel = new javax.swing.JLabel();
        lagerTextfield4 = new view.LagerTextfield();
        lagerTextfield5 = new view.LagerTextfield();
        lagerTextfield6 = new view.LagerTextfield();
        lagerTextfield7 = new view.LagerTextfield();
        lagerTextfield8 = new view.LagerTextfield();
        lagerTextfield9 = new view.LagerTextfield();
        suche_Teil = new javax.swing.JPanel();
        SuchenlinksButton = new javax.swing.JButton();
        EuroLabel = new javax.swing.JLabel();
        PreisLabel = new javax.swing.JLabel();
        MAKLabel = new javax.swing.JLabel();
        TeileStammdatenLabel = new javax.swing.JLabel();
        BezeichnungLabel = new javax.swing.JLabel();
        IDlinksLabel = new javax.swing.JLabel();
        MaterialgruppeLabel = new javax.swing.JLabel();
        TeiletypLabel = new javax.swing.JLabel();
        BaugruppeLabel = new javax.swing.JLabel();
        AlleTeileAnzeigenButton = new javax.swing.JButton();
        ZeichnungsnrLabel = new javax.swing.JLabel();
        MAMLabel = new javax.swing.JLabel();
        MAGLabel = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TeilSuchenJtable = new javax.swing.JTable();
        TeiletypComboBox = new javax.swing.JComboBox();
        BemerkungLabel = new javax.swing.JLabel();
        TeileIDlagerTextfield = new view.LagerTextfield();
        BezeichnunglagerTextfield = new view.LagerTextfield();
        MaterialgruppelagerTextfield = new view.LagerTextfield();
        ZeichnungsnummerlagerTextfield = new view.LagerTextfield();
        BaugruppelagerTextfield = new view.LagerTextfield();
        BemerkungslagerTextfield = new view.LagerTextfield();
        PreislagerTextfield = new view.LagerTextfield();
        MaximaleAnzahlKleinlagerTextfield = new view.LagerTextfield();
        MaximaleAnzahlMittellagerTextfield = new view.LagerTextfield();
        MaximaleAnzahlGroßlagerTextfield = new view.LagerTextfield();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(jTable6);

        LagerortLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LagerortLabel.setText("Lagerort:");

        LagerfachbestandLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LagerfachbestandLabel.setText("Fachnummer:");

        ZeileLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ZeileLabel.setText("Zeile:");

        RegalnrLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        RegalnrLabel.setText("Regalnr.:");

        BelegtLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        BelegtLabel.setText("Belegt:");

        SpalteLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        SpalteLabel.setText("Spalte:");

        FCB.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        FCB.setText("F");

        H3CB.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        H3CB.setText("H3");

        H1CB.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        H1CB.setText("H1");

        H4CB.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        H4CB.setText("H4");

        H2CB.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        H2CB.setText("H2");

        HCB.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        HCB.setText("H");

        gCB.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        gCB.setText("G");

        GrößeLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        GrößeLabel.setText("Größe:");

        mCB.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        mCB.setText("M");

        SuchenmitteButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        SuchenmitteButton.setText("Suchen");

        neinCB.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        neinCB.setText("nein");

        kCB.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        kCB.setText("K");

        jaCB.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jaCB.setText("ja");

        H5CB.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        H5CB.setText("H5");

        zeile_label.setText("(Z1 - Z25)");

        spalte_label.setText("(S1 - S25)");

        lagerTextfield1.setText("lagerTextfield1");

        lagerTextfield2.setText("lagerTextfield2");

        lagerTextfield3.setText("lagerTextfield3");

        javax.swing.GroupLayout suche_Fach_lagerplatzLayout = new javax.swing.GroupLayout(suche_Fach_lagerplatz);
        suche_Fach_lagerplatz.setLayout(suche_Fach_lagerplatzLayout);
        suche_Fach_lagerplatzLayout.setHorizontalGroup(
            suche_Fach_lagerplatzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(suche_Fach_lagerplatzLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(suche_Fach_lagerplatzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(suche_Fach_lagerplatzLayout.createSequentialGroup()
                        .addComponent(LagerfachbestandLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lagerTextfield1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(suche_Fach_lagerplatzLayout.createSequentialGroup()
                        .addComponent(LagerortLabel)
                        .addGap(18, 18, 18)
                        .addComponent(FCB)
                        .addGap(11, 11, 11)
                        .addComponent(HCB))
                    .addGroup(suche_Fach_lagerplatzLayout.createSequentialGroup()
                        .addComponent(SpalteLabel)
                        .addGap(154, 154, 154)
                        .addComponent(spalte_label))
                    .addGroup(suche_Fach_lagerplatzLayout.createSequentialGroup()
                        .addComponent(BelegtLabel)
                        .addGap(34, 34, 34)
                        .addComponent(jaCB)
                        .addGap(2, 2, 2)
                        .addComponent(neinCB))
                    .addGroup(suche_Fach_lagerplatzLayout.createSequentialGroup()
                        .addComponent(GrößeLabel)
                        .addGap(34, 34, 34)
                        .addComponent(kCB)
                        .addGap(2, 2, 2)
                        .addComponent(mCB)
                        .addGap(2, 2, 2)
                        .addComponent(gCB))
                    .addComponent(SuchenmitteButton)
                    .addGroup(suche_Fach_lagerplatzLayout.createSequentialGroup()
                        .addGroup(suche_Fach_lagerplatzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, suche_Fach_lagerplatzLayout.createSequentialGroup()
                                .addComponent(RegalnrLabel)
                                .addGap(18, 18, 18)
                                .addComponent(H1CB)
                                .addGap(2, 2, 2)
                                .addComponent(H2CB)
                                .addGap(2, 2, 2)
                                .addComponent(H3CB)
                                .addGap(2, 2, 2)
                                .addComponent(H4CB))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, suche_Fach_lagerplatzLayout.createSequentialGroup()
                                .addGroup(suche_Fach_lagerplatzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lagerTextfield3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(suche_Fach_lagerplatzLayout.createSequentialGroup()
                                        .addComponent(ZeileLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lagerTextfield2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(zeile_label)))
                        .addGap(2, 2, 2)
                        .addComponent(H5CB)))
                .addGap(322, 322, 322))
            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        suche_Fach_lagerplatzLayout.setVerticalGroup(
            suche_Fach_lagerplatzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(suche_Fach_lagerplatzLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(suche_Fach_lagerplatzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LagerfachbestandLabel)
                    .addComponent(lagerTextfield1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(suche_Fach_lagerplatzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(suche_Fach_lagerplatzLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(LagerortLabel))
                    .addComponent(FCB)
                    .addComponent(HCB))
                .addGap(8, 8, 8)
                .addGroup(suche_Fach_lagerplatzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(suche_Fach_lagerplatzLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(RegalnrLabel))
                    .addComponent(H1CB)
                    .addComponent(H2CB)
                    .addComponent(H3CB)
                    .addComponent(H4CB)
                    .addComponent(H5CB))
                .addGap(16, 16, 16)
                .addGroup(suche_Fach_lagerplatzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(suche_Fach_lagerplatzLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(ZeileLabel)
                        .addGap(10, 10, 10)
                        .addGroup(suche_Fach_lagerplatzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(suche_Fach_lagerplatzLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(suche_Fach_lagerplatzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(SpalteLabel)
                                    .addComponent(lagerTextfield3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(spalte_label))
                        .addGap(17, 17, 17)
                        .addGroup(suche_Fach_lagerplatzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(suche_Fach_lagerplatzLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(BelegtLabel))
                            .addComponent(jaCB)
                            .addComponent(neinCB))
                        .addGap(18, 18, 18)
                        .addGroup(suche_Fach_lagerplatzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(suche_Fach_lagerplatzLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(GrößeLabel))
                            .addComponent(kCB)
                            .addComponent(mCB)
                            .addComponent(gCB))
                        .addGap(18, 18, 18)
                        .addComponent(SuchenmitteButton))
                    .addGroup(suche_Fach_lagerplatzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(zeile_label)
                        .addComponent(lagerTextfield2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Fach / Lagerplatz suchen", suche_Fach_lagerplatz);

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable5);

        TeileIDLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TeileIDLabel.setText("Teile ID:");

        SuchenrechtsButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        SuchenrechtsButton.setText("Suchen");

        FachnrLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        FachnrLabel.setText("Fachnummer:");

        HaltbarkeitsLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        HaltbarkeitsLabel.setText("Haltbarkeitsdatum:");

        MaxMengeLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        MaxMengeLabel.setText("Max. Menge im Fach:");

        MinMengeLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        MinMengeLabel.setText("Mind. Menge im Fach:");

        LagerbestandLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LagerbestandLabel.setText("Lagerbestand:");

        lagerTextfield4.setText("lagerTextfield4");

        lagerTextfield5.setText("lagerTextfield5");

        lagerTextfield6.setText("lagerTextfield6");

        lagerTextfield7.setText("lagerTextfield7");

        lagerTextfield8.setText("lagerTextfield8");

        lagerTextfield9.setText("lagerTextfield9");

        javax.swing.GroupLayout suche_InhaltLayout = new javax.swing.GroupLayout(suche_Inhalt);
        suche_Inhalt.setLayout(suche_InhaltLayout);
        suche_InhaltLayout.setHorizontalGroup(
            suche_InhaltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 741, Short.MAX_VALUE)
            .addGroup(suche_InhaltLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(suche_InhaltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SuchenrechtsButton)
                    .addGroup(suche_InhaltLayout.createSequentialGroup()
                        .addComponent(LagerbestandLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lagerTextfield4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(suche_InhaltLayout.createSequentialGroup()
                        .addComponent(MinMengeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lagerTextfield5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(suche_InhaltLayout.createSequentialGroup()
                        .addComponent(MaxMengeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lagerTextfield6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(suche_InhaltLayout.createSequentialGroup()
                        .addComponent(HaltbarkeitsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lagerTextfield7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(suche_InhaltLayout.createSequentialGroup()
                        .addComponent(FachnrLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lagerTextfield8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(suche_InhaltLayout.createSequentialGroup()
                        .addComponent(TeileIDLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lagerTextfield9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(486, Short.MAX_VALUE))
        );
        suche_InhaltLayout.setVerticalGroup(
            suche_InhaltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, suche_InhaltLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(suche_InhaltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LagerbestandLabel)
                    .addComponent(lagerTextfield4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(suche_InhaltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MinMengeLabel)
                    .addComponent(lagerTextfield5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(suche_InhaltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MaxMengeLabel)
                    .addComponent(lagerTextfield6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(suche_InhaltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HaltbarkeitsLabel)
                    .addComponent(lagerTextfield7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(suche_InhaltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FachnrLabel)
                    .addComponent(lagerTextfield8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(suche_InhaltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TeileIDLabel)
                    .addComponent(lagerTextfield9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(SuchenrechtsButton)
                .addGap(69, 69, 69)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Menge / Teil im Fach suchen", suche_Inhalt);

        SuchenlinksButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        SuchenlinksButton.setText("Suchen");
        SuchenlinksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teile_suchen(evt);
            }
        });

        EuroLabel.setText("€");

        PreisLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        PreisLabel.setText("Preis:");

        MAKLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        MAKLabel.setText("Maximale Anzahl Klein:");

        TeileStammdatenLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        TeileStammdatenLabel.setText("Teile Stammdaten:");

        BezeichnungLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        BezeichnungLabel.setText("Bezeichnung:");

        IDlinksLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        IDlinksLabel.setText("Teile ID:");

        MaterialgruppeLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        MaterialgruppeLabel.setText("Materialgrupe:");

        TeiletypLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TeiletypLabel.setText("Teiletyp:");

        BaugruppeLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        BaugruppeLabel.setText("Baugruppe:");

        AlleTeileAnzeigenButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        AlleTeileAnzeigenButton.setText("alle Teile anzeigen");
        AlleTeileAnzeigenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alle_teile_suchen(evt);
            }
        });

        ZeichnungsnrLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ZeichnungsnrLabel.setText("Zeichnungsnummer:");

        MAMLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        MAMLabel.setText("Maximale Anzahl Mittel:");

        MAGLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        MAGLabel.setText("Maximale Anzahl Groß:");

        TeilSuchenJtable.setModel(new DefaultTableModel());
        jScrollPane4.setViewportView(TeilSuchenJtable);

        TeiletypComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Kaufteile", "Werkzeuge", "Vorrichtungen", "unfertige Baugruppen", "Vorratsteile" }));

        BemerkungLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        BemerkungLabel.setText("Bemerkung:");

        javax.swing.GroupLayout suche_TeilLayout = new javax.swing.GroupLayout(suche_Teil);
        suche_Teil.setLayout(suche_TeilLayout);
        suche_TeilLayout.setHorizontalGroup(
            suche_TeilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(suche_TeilLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(suche_TeilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(suche_TeilLayout.createSequentialGroup()
                        .addComponent(AlleTeileAnzeigenButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SuchenlinksButton))
                    .addComponent(TeileStammdatenLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(suche_TeilLayout.createSequentialGroup()
                        .addGroup(suche_TeilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BaugruppeLabel)
                            .addComponent(ZeichnungsnrLabel)
                            .addComponent(MaterialgruppeLabel)
                            .addComponent(TeiletypLabel)
                            .addComponent(BezeichnungLabel)
                            .addComponent(IDlinksLabel))
                        .addGap(15, 15, 15)
                        .addGroup(suche_TeilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TeileIDlagerTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BezeichnunglagerTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TeiletypComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MaterialgruppelagerTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ZeichnungsnummerlagerTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BaugruppelagerTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(suche_TeilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BemerkungLabel)
                            .addComponent(PreisLabel)
                            .addComponent(MAKLabel)
                            .addComponent(MAMLabel)
                            .addComponent(MAGLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(suche_TeilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BemerkungslagerTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PreislagerTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MaximaleAnzahlMittellagerTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MaximaleAnzahlGroßlagerTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(suche_TeilLayout.createSequentialGroup()
                                .addComponent(MaximaleAnzahlKleinlagerTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EuroLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 55, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, suche_TeilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );

        suche_TeilLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BaugruppelagerTextfield, BemerkungslagerTextfield, BezeichnunglagerTextfield, MaterialgruppelagerTextfield, MaximaleAnzahlGroßlagerTextfield, MaximaleAnzahlKleinlagerTextfield, MaximaleAnzahlMittellagerTextfield, PreislagerTextfield, TeileIDlagerTextfield, TeiletypComboBox, ZeichnungsnummerlagerTextfield});

        suche_TeilLayout.setVerticalGroup(
            suche_TeilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(suche_TeilLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(TeileStammdatenLabel)
                .addGap(12, 12, 12)
                .addGroup(suche_TeilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDlinksLabel)
                    .addComponent(TeileIDlagerTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BemerkungLabel)
                    .addComponent(BemerkungslagerTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(suche_TeilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BezeichnungLabel)
                    .addComponent(BezeichnunglagerTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PreisLabel)
                    .addComponent(PreislagerTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(suche_TeilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TeiletypLabel)
                    .addComponent(TeiletypComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MAKLabel)
                    .addComponent(MaximaleAnzahlKleinlagerTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EuroLabel))
                .addGap(11, 11, 11)
                .addGroup(suche_TeilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MaterialgruppeLabel)
                    .addComponent(MaterialgruppelagerTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MAMLabel)
                    .addComponent(MaximaleAnzahlMittellagerTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(suche_TeilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ZeichnungsnrLabel)
                    .addComponent(ZeichnungsnummerlagerTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MAGLabel)
                    .addComponent(MaximaleAnzahlGroßlagerTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(suche_TeilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BaugruppeLabel)
                    .addComponent(BaugruppelagerTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(suche_TeilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AlleTeileAnzeigenButton)
                    .addComponent(SuchenlinksButton))
                .addGap(16, 16, 16)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        suche_TeilLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {BaugruppelagerTextfield, BemerkungslagerTextfield, BezeichnunglagerTextfield, MaterialgruppelagerTextfield, MaximaleAnzahlGroßlagerTextfield, MaximaleAnzahlKleinlagerTextfield, MaximaleAnzahlMittellagerTextfield, PreislagerTextfield, TeileIDlagerTextfield, TeiletypComboBox, ZeichnungsnummerlagerTextfield});

        jTabbedPane1.addTab("Teil suchen", suche_Teil);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alle_teile_suchen(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alle_teile_suchen
        try {
            DefaultTableModel table_model = new DefaultTableModel();
            ArrayList<Teil_Stammdaten> teile = suchen_controller.alle_teile_ausgeben();
            for (String columnname : suchen_controller.table_column_names) {
                table_model.addColumn(columnname);
            }

            for (Teil_Stammdaten teil : teile) {
                table_model.addRow(teil.toArray());
            }
            this.TeilSuchenJtable.setModel(table_model);

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Teil_Suchen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(Teil_Suchen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_alle_teile_suchen

    private void teile_suchen(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teile_suchen
        // Werte werden aus den Textfeldern und anderen Eingabefeldern ausgelesen und in ein zweidimensionales Array geschrieben
        String[][] spaltenwerte = new String[11][];
        String[] id = {"id", TeileIDlagerTextfield.getText()};
        String teilstring = (String) TeiletypComboBox.getSelectedItem();
        if (" ".equals(teilstring)) {
            teilstring = "";
        }
        String[] teiletyp = {"typ", teilstring};
        String[] zeichnungsnummer = {"zeichnungsnummer", ZeichnungsnummerlagerTextfield.getText()};
        String[] materialgruppe = {"materialgruppe", MaterialgruppelagerTextfield.getText()};

        String[] preis = {"preis", PreislagerTextfield.getText()};
        String[] bezeichnung = {"bezeichnung", BezeichnunglagerTextfield.getText()};
        String[] baugruppe = {"baugruppe", BaugruppelagerTextfield.getText()};
        String[] bemerkung = {"bemerkung", BemerkungslagerTextfield.getText()};
        String[] maxanzahlklein = {"max_anz_klein", MaximaleAnzahlKleinlagerTextfield.getText()};
        String[] maxanzahlmittel = {"max_anz_mittel", MaximaleAnzahlMittellagerTextfield.getText()};
        String[] maxanzahlgross = {"max_anz_gross", MaximaleAnzahlGroßlagerTextfield.getText()};

        spaltenwerte[0] = id;
        spaltenwerte[1] = teiletyp;
        spaltenwerte[2] = zeichnungsnummer;
        spaltenwerte[3] = materialgruppe;
        spaltenwerte[4] = preis;
        spaltenwerte[5] = bezeichnung;
        spaltenwerte[6] = baugruppe;
        spaltenwerte[7] = maxanzahlklein;
        spaltenwerte[8] = maxanzahlmittel;
        spaltenwerte[9] = maxanzahlgross;
        spaltenwerte[10] = bemerkung;
        try {
            // Mit den ausgelesenen Daten wird mit hilfe des Controllers gesucht
            ArrayList<Teil_Stammdaten> teile = suchen_controller.teile_suchen(spaltenwerte);
            DefaultTableModel table_model = new DefaultTableModel();
            // Spaltennamen werden festgeelegt
            for (String columnname : suchen_controller.table_column_names) {
                table_model.addColumn(columnname);
            }
            // JTable wird mit Werten gefüllt
            for (Teil_Stammdaten teil : teile) {
                table_model.addRow(teil.toArray());
            }
            this.TeilSuchenJtable.setModel(table_model);
        } catch (ClassNotFoundException e) {
            Logger.getLogger(Teil_Suchen.class.getName()).log(Level.SEVERE, null, e);
        } catch (Exception e) {
            Logger.getLogger(Teil_Suchen.class.getName()).log(Level.SEVERE, null, e);
        }

    }//GEN-LAST:event_teile_suchen
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teil_Suchen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teil_Suchen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teil_Suchen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teil_Suchen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Teil_Suchen().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AlleTeileAnzeigenButton;
    private javax.swing.JLabel BaugruppeLabel;
    private view.LagerTextfield BaugruppelagerTextfield;
    private javax.swing.JLabel BelegtLabel;
    private javax.swing.JLabel BemerkungLabel;
    private view.LagerTextfield BemerkungslagerTextfield;
    private javax.swing.JLabel BezeichnungLabel;
    private view.LagerTextfield BezeichnunglagerTextfield;
    private javax.swing.JLabel EuroLabel;
    private javax.swing.JCheckBox FCB;
    private javax.swing.JLabel FachnrLabel;
    private javax.swing.JLabel GrößeLabel;
    private javax.swing.JCheckBox H1CB;
    private javax.swing.JCheckBox H2CB;
    private javax.swing.JCheckBox H3CB;
    private javax.swing.JCheckBox H4CB;
    private javax.swing.JCheckBox H5CB;
    private javax.swing.JCheckBox HCB;
    private javax.swing.JLabel HaltbarkeitsLabel;
    private javax.swing.JLabel IDlinksLabel;
    private javax.swing.JLabel LagerbestandLabel;
    private javax.swing.JLabel LagerfachbestandLabel;
    private javax.swing.JLabel LagerortLabel;
    private javax.swing.JLabel MAGLabel;
    private javax.swing.JLabel MAKLabel;
    private javax.swing.JLabel MAMLabel;
    private javax.swing.JLabel MaterialgruppeLabel;
    private view.LagerTextfield MaterialgruppelagerTextfield;
    private javax.swing.JLabel MaxMengeLabel;
    private view.LagerTextfield MaximaleAnzahlGroßlagerTextfield;
    private view.LagerTextfield MaximaleAnzahlKleinlagerTextfield;
    private view.LagerTextfield MaximaleAnzahlMittellagerTextfield;
    private javax.swing.JLabel MinMengeLabel;
    private javax.swing.JLabel PreisLabel;
    private view.LagerTextfield PreislagerTextfield;
    private javax.swing.JLabel RegalnrLabel;
    private javax.swing.JLabel SpalteLabel;
    private javax.swing.JButton SuchenlinksButton;
    private javax.swing.JButton SuchenmitteButton;
    private javax.swing.JButton SuchenrechtsButton;
    private javax.swing.JTable TeilSuchenJtable;
    private javax.swing.JLabel TeileIDLabel;
    private view.LagerTextfield TeileIDlagerTextfield;
    private javax.swing.JLabel TeileStammdatenLabel;
    private javax.swing.JComboBox TeiletypComboBox;
    private javax.swing.JLabel TeiletypLabel;
    private javax.swing.JLabel ZeichnungsnrLabel;
    private view.LagerTextfield ZeichnungsnummerlagerTextfield;
    private javax.swing.JLabel ZeileLabel;
    private javax.swing.JCheckBox gCB;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JCheckBox jaCB;
    private javax.swing.JCheckBox kCB;
    private view.LagerTextfield lagerTextfield1;
    private view.LagerTextfield lagerTextfield2;
    private view.LagerTextfield lagerTextfield3;
    private view.LagerTextfield lagerTextfield4;
    private view.LagerTextfield lagerTextfield5;
    private view.LagerTextfield lagerTextfield6;
    private view.LagerTextfield lagerTextfield7;
    private view.LagerTextfield lagerTextfield8;
    private view.LagerTextfield lagerTextfield9;
    private javax.swing.JCheckBox mCB;
    private javax.swing.JCheckBox neinCB;
    private javax.swing.JLabel spalte_label;
    private javax.swing.JPanel suche_Fach_lagerplatz;
    private javax.swing.JPanel suche_Inhalt;
    private javax.swing.JPanel suche_Teil;
    private javax.swing.JLabel zeile_label;
    // End of variables declaration//GEN-END:variables
}
