/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */
package view;

/**
 *
 * @author felix
 */
public class Teilestamm_verwalten extends javax.swing.JFrame {

    /**
     * Creates new form Teilestamm_erweitern
     */
    public Teilestamm_verwalten() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_eingabeaufforderung = new javax.swing.JLabel();
        label_id = new javax.swing.JLabel();
        textfeld_id = new javax.swing.JTextField();
        label_bezeichnung = new javax.swing.JLabel();
        label_teiltyp = new javax.swing.JLabel();
        label_materialgruppe = new javax.swing.JLabel();
        label_zeichnungsnummer = new javax.swing.JLabel();
        label_baugruppe = new javax.swing.JLabel();
        textfeld_bezeichnung = new javax.swing.JTextField();
        textfeld_materialgruppe = new javax.swing.JTextField();
        textfeld_zeichnungsnummer = new javax.swing.JTextField();
        textfeld_baugruppe = new javax.swing.JTextField();
        label_preis = new javax.swing.JLabel();
        label_max_anz_klein = new javax.swing.JLabel();
        label_max_anz_mittel = new javax.swing.JLabel();
        label_max_anz_gross = new javax.swing.JLabel();
        label_bemerkung = new javax.swing.JLabel();
        textfeld_preis = new javax.swing.JTextField();
        textfeld_max_anz_klein = new javax.swing.JTextField();
        textfeld_max_anz_mittel = new javax.swing.JTextField();
        textfeld_max_anz_gross = new javax.swing.JTextField();
        textfeld_bemerkung = new javax.swing.JTextField();
        label_waehrung = new javax.swing.JLabel();
        button_loeschen = new javax.swing.JButton();
        textfeld_teiltyp = new javax.swing.JTextField();
        button_suchen = new javax.swing.JButton();
        anzeigen_button = new javax.swing.JButton();
        aendern_button = new javax.swing.JButton();
        menubar_teilestamm_verwalten = new javax.swing.JMenuBar();
        menu_datei = new javax.swing.JMenu();
        menu_bearbeiten = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().setLayout(null);

        label_eingabeaufforderung.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label_eingabeaufforderung.setText("Bitte geben Sie die ID des Teiles ein:");
        getContentPane().add(label_eingabeaufforderung);
        label_eingabeaufforderung.setBounds(10, 11, 433, 15);

        label_id.setFont(new java.awt.Font("Arial", 0, 12));
        label_id.setText("ID:");
        getContentPane().add(label_id);
        label_id.setBounds(10, 48, 15, 15);

        textfeld_id.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textfeld_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfeld_idActionPerformed(evt);
            }
        });
        getContentPane().add(textfeld_id);
        textfeld_id.setBounds(29, 45, 59, 21);

        label_bezeichnung.setFont(new java.awt.Font("Arial", 0, 12));
        label_bezeichnung.setText("Bezeichnnung:");
        getContentPane().add(label_bezeichnung);
        label_bezeichnung.setBounds(10, 88, 81, 15);

        label_teiltyp.setFont(new java.awt.Font("Arial", 0, 12));
        label_teiltyp.setText("Teiltyp:");
        getContentPane().add(label_teiltyp);
        label_teiltyp.setBounds(10, 120, 38, 15);

        label_materialgruppe.setFont(new java.awt.Font("Arial", 0, 12));
        label_materialgruppe.setText("Materialgruppe:");
        getContentPane().add(label_materialgruppe);
        label_materialgruppe.setBounds(10, 152, 85, 15);

        label_zeichnungsnummer.setFont(new java.awt.Font("Arial", 0, 12));
        label_zeichnungsnummer.setText("Zeichnungsnr.:");
        getContentPane().add(label_zeichnungsnummer);
        label_zeichnungsnummer.setBounds(10, 184, 82, 15);

        label_baugruppe.setFont(new java.awt.Font("Arial", 0, 12));
        label_baugruppe.setText("Baugruppe:");
        getContentPane().add(label_baugruppe);
        label_baugruppe.setBounds(10, 216, 64, 15);

        textfeld_bezeichnung.setEditable(false);
        textfeld_bezeichnung.setFont(new java.awt.Font("Arial", 0, 12));
        getContentPane().add(textfeld_bezeichnung);
        textfeld_bezeichnung.setBounds(99, 85, 161, 21);

        textfeld_materialgruppe.setEditable(false);
        textfeld_materialgruppe.setFont(new java.awt.Font("Arial", 0, 12));
        getContentPane().add(textfeld_materialgruppe);
        textfeld_materialgruppe.setBounds(99, 149, 161, 21);

        textfeld_zeichnungsnummer.setEditable(false);
        textfeld_zeichnungsnummer.setFont(new java.awt.Font("Arial", 0, 12));
        getContentPane().add(textfeld_zeichnungsnummer);
        textfeld_zeichnungsnummer.setBounds(99, 181, 161, 21);

        textfeld_baugruppe.setEditable(false);
        textfeld_baugruppe.setFont(new java.awt.Font("Arial", 0, 12));
        getContentPane().add(textfeld_baugruppe);
        textfeld_baugruppe.setBounds(99, 213, 161, 21);

        label_preis.setFont(new java.awt.Font("Arial", 0, 12));
        label_preis.setText("Preis:");
        getContentPane().add(label_preis);
        label_preis.setBounds(278, 88, 32, 15);

        label_max_anz_klein.setFont(new java.awt.Font("Arial", 0, 12));
        label_max_anz_klein.setText("Max. Anz. Klein:");
        getContentPane().add(label_max_anz_klein);
        label_max_anz_klein.setBounds(278, 120, 83, 15);

        label_max_anz_mittel.setFont(new java.awt.Font("Arial", 0, 12));
        label_max_anz_mittel.setText("Max. Anz. Mittel:");
        getContentPane().add(label_max_anz_mittel);
        label_max_anz_mittel.setBounds(278, 152, 83, 15);

        label_max_anz_gross.setFont(new java.awt.Font("Arial", 0, 12));
        label_max_anz_gross.setText("Max. Anz. Groß:");
        getContentPane().add(label_max_anz_gross);
        label_max_anz_gross.setBounds(278, 184, 83, 15);

        label_bemerkung.setFont(new java.awt.Font("Arial", 0, 12));
        label_bemerkung.setText("Bemerkung:");
        getContentPane().add(label_bemerkung);
        label_bemerkung.setBounds(278, 216, 67, 15);

        textfeld_preis.setEditable(false);
        textfeld_preis.setFont(new java.awt.Font("Arial", 0, 12));
        getContentPane().add(textfeld_preis);
        textfeld_preis.setBounds(371, 85, 161, 21);

        textfeld_max_anz_klein.setEditable(false);
        textfeld_max_anz_klein.setFont(new java.awt.Font("Arial", 0, 12));
        getContentPane().add(textfeld_max_anz_klein);
        textfeld_max_anz_klein.setBounds(371, 117, 161, 21);

        textfeld_max_anz_mittel.setEditable(false);
        textfeld_max_anz_mittel.setFont(new java.awt.Font("Arial", 0, 12));
        getContentPane().add(textfeld_max_anz_mittel);
        textfeld_max_anz_mittel.setBounds(371, 149, 161, 21);

        textfeld_max_anz_gross.setEditable(false);
        textfeld_max_anz_gross.setFont(new java.awt.Font("Arial", 0, 12));
        getContentPane().add(textfeld_max_anz_gross);
        textfeld_max_anz_gross.setBounds(371, 181, 161, 21);

        textfeld_bemerkung.setEditable(false);
        textfeld_bemerkung.setFont(new java.awt.Font("Arial", 0, 12));
        getContentPane().add(textfeld_bemerkung);
        textfeld_bemerkung.setBounds(371, 213, 161, 21);

        label_waehrung.setFont(new java.awt.Font("Arial", 0, 12));
        label_waehrung.setText("€");
        getContentPane().add(label_waehrung);
        label_waehrung.setBounds(536, 88, 7, 15);

        button_loeschen.setFont(new java.awt.Font("Arial", 1, 12));
        button_loeschen.setText("Löschen");
        getContentPane().add(button_loeschen);
        button_loeschen.setBounds(451, 44, 81, 23);

        textfeld_teiltyp.setEditable(false);
        getContentPane().add(textfeld_teiltyp);
        textfeld_teiltyp.setBounds(99, 118, 161, 20);

        button_suchen.setFont(new java.awt.Font("Arial", 1, 12));
        button_suchen.setText("Suchen");
        getContentPane().add(button_suchen);
        button_suchen.setBounds(197, 44, 75, 23);

        anzeigen_button.setFont(new java.awt.Font("Arial", 1, 12));
        anzeigen_button.setText("Anzeigen");
        getContentPane().add(anzeigen_button);
        anzeigen_button.setBounds(106, 44, 85, 23);

        aendern_button.setFont(new java.awt.Font("Arial", 1, 12));
        aendern_button.setText("Ändern");
        getContentPane().add(aendern_button);
        aendern_button.setBounds(459, 252, 73, 23);

        menu_datei.setText("File");
        menubar_teilestamm_verwalten.add(menu_datei);

        menu_bearbeiten.setText("Edit");
        menubar_teilestamm_verwalten.add(menu_bearbeiten);

        setJMenuBar(menubar_teilestamm_verwalten);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textfeld_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfeld_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfeld_idActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teilestamm_verwalten.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teilestamm_verwalten.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teilestamm_verwalten.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teilestamm_verwalten.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Teilestamm_verwalten().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aendern_button;
    private javax.swing.JButton anzeigen_button;
    private javax.swing.JButton button_loeschen;
    private javax.swing.JButton button_suchen;
    private javax.swing.JLabel label_baugruppe;
    private javax.swing.JLabel label_bemerkung;
    private javax.swing.JLabel label_bezeichnung;
    private javax.swing.JLabel label_eingabeaufforderung;
    private javax.swing.JLabel label_id;
    private javax.swing.JLabel label_materialgruppe;
    private javax.swing.JLabel label_max_anz_gross;
    private javax.swing.JLabel label_max_anz_klein;
    private javax.swing.JLabel label_max_anz_mittel;
    private javax.swing.JLabel label_preis;
    private javax.swing.JLabel label_teiltyp;
    private javax.swing.JLabel label_waehrung;
    private javax.swing.JLabel label_zeichnungsnummer;
    private javax.swing.JMenu menu_bearbeiten;
    private javax.swing.JMenu menu_datei;
    private javax.swing.JMenuBar menubar_teilestamm_verwalten;
    private javax.swing.JTextField textfeld_baugruppe;
    private javax.swing.JTextField textfeld_bemerkung;
    private javax.swing.JTextField textfeld_bezeichnung;
    private javax.swing.JTextField textfeld_id;
    private javax.swing.JTextField textfeld_materialgruppe;
    private javax.swing.JTextField textfeld_max_anz_gross;
    private javax.swing.JTextField textfeld_max_anz_klein;
    private javax.swing.JTextField textfeld_max_anz_mittel;
    private javax.swing.JTextField textfeld_preis;
    private javax.swing.JTextField textfeld_teiltyp;
    private javax.swing.JTextField textfeld_zeichnungsnummer;
    // End of variables declaration//GEN-END:variables
}
