/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */
package view;

import control.Suchen_Controller;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonModel;
import javax.swing.table.DefaultTableModel;
import model.Lagerbestandskonto;
import model.Lagerfachstamm;
import model.Teil_Stammdaten;
import view.LagerTextfield.AllowedSequences;

/**
 *
 * @author Matthias Sommer
 */
public class Teil_Suchen extends javax.swing.JFrame {

    private Suchen_Controller suchen_controller;

    /**
     * Creates new form Teil_Suchen
     */
    public Teil_Suchen() {
        initComponents();
        suchen_controller = new Suchen_Controller();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegalnummerbuttonGroup = new javax.swing.ButtonGroup();
        GroesseButtonGroup = new javax.swing.ButtonGroup();
        BelegtButtonGroup = new javax.swing.ButtonGroup();
        LagerortButtonGroup = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        suche_Fach_lagerplatz = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        FachSuchenJtable = new javax.swing.JTable();
        LagerortLabel = new javax.swing.JLabel();
        LagerfachbestandLabel = new javax.swing.JLabel();
        ZeileLabel = new javax.swing.JLabel();
        RegalnrLabel = new javax.swing.JLabel();
        BelegtLabel = new javax.swing.JLabel();
        SpalteLabel = new javax.swing.JLabel();
        GrößeLabel = new javax.swing.JLabel();
        SuchenmitteButton = new javax.swing.JButton();
        zeile_label = new javax.swing.JLabel();
        spalte_label = new javax.swing.JLabel();
        FachnummerlagerTextfield3 = new view.LagerTextfield();
        ZeilelagerTextfield3 = new view.LagerTextfield();
        SpaltelagerTextfield3 = new view.LagerTextfield();
        H1JRadioButton = new javax.swing.JRadioButton();
        H2JRadioButton = new javax.swing.JRadioButton();
        H3JRadioButton = new javax.swing.JRadioButton();
        H4JRadioButton = new javax.swing.JRadioButton();
        H5JRadioButton = new javax.swing.JRadioButton();
        KleinJRadiobutton = new javax.swing.JRadioButton();
        MittelJRadioButton = new javax.swing.JRadioButton();
        GrossJRadiobutton = new javax.swing.JRadioButton();
        BelegtJRadioButton = new javax.swing.JRadioButton();
        NichtBelegtJRadioButton = new javax.swing.JRadioButton();
        HochregallagerJRadioButton = new javax.swing.JRadioButton();
        FreilagerJRadioButton = new javax.swing.JRadioButton();
        KeineAngabeRegalnummerJRadioButton = new javax.swing.JRadioButton();
        KeineAngabeGroesseJRadioButton = new javax.swing.JRadioButton();
        KeineAngabeBelegtJRadioButton = new javax.swing.JRadioButton();
        KeineAngabeLagerortJRadioButton = new javax.swing.JRadioButton();
        suche_Inhalt = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        TeileImFachSuchenJtable = new javax.swing.JTable();
        TeileIDLabel = new javax.swing.JLabel();
        SuchenrechtsButton = new javax.swing.JButton();
        FachnrLabel = new javax.swing.JLabel();
        MaxMengeLabel = new javax.swing.JLabel();
        MinMengeLabel = new javax.swing.JLabel();
        LagerbestandLabel = new javax.swing.JLabel();
        LagerbestandlagerTextfield2 = new view.LagerTextfield(AllowedSequences.ZIFFERN);
        FachnummerlagerTextfield2 = new view.LagerTextfield();
        MindestensMengeimFachlagerTextfield2 = new view.LagerTextfield(AllowedSequences.ZIFFERN);
        MaximaleMengeimFachlagerTextfield2 = new view.LagerTextfield(AllowedSequences.ZIFFERN);
        TeileIdlagerTextfield2 = new view.LagerTextfield(AllowedSequences.ZIFFERN);
        AnschaffungsgrundlagerTextfield2 = new view.LagerTextfield();
        AnschaffungsgrundLabel = new javax.swing.JLabel();
        suche_Teil = new javax.swing.JPanel();
        SuchenlinksButton = new javax.swing.JButton();
        EuroLabel = new javax.swing.JLabel();
        PreisLabel = new javax.swing.JLabel();
        MAKLabel = new javax.swing.JLabel();
        TeileStammdatenLabel = new javax.swing.JLabel();
        BezeichnungLabel = new javax.swing.JLabel();
        IDlinksLabel = new javax.swing.JLabel();
        MaterialgruppeLabel = new javax.swing.JLabel();
        TeiletypLabel = new javax.swing.JLabel();
        BaugruppeLabel = new javax.swing.JLabel();
        AlleTeileAnzeigenButton = new javax.swing.JButton();
        ZeichnungsnrLabel = new javax.swing.JLabel();
        MAMLabel = new javax.swing.JLabel();
        MAGLabel = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TeilSuchenJtable = new javax.swing.JTable();
        TeiletypComboBox = new javax.swing.JComboBox();
        BemerkungLabel = new javax.swing.JLabel();
        TeileIdlagerTextfield = new view.LagerTextfield(AllowedSequences.ZIFFERN);
        BezeichnunglagerTextfield = new view.LagerTextfield();
        MaterialgruppelagerTextfield = new view.LagerTextfield();
        ZeichnungsnummerlagerTextfield = new view.LagerTextfield();
        BaugruppelagerTextfield = new view.LagerTextfield();
        BemerkungslagerTextfield = new view.LagerTextfield();
        PreislagerTextfield = new view.LagerTextfield(AllowedSequences.PREIS);
        MaximaleAnzahlKleinlagerTextfield = new view.LagerTextfield(AllowedSequences.ZIFFERN);
        MaximaleAnzahlMittellagerTextfield = new view.LagerTextfield(AllowedSequences.ZIFFERN);
        MaximaleAnzahlGroßlagerTextfield = new view.LagerTextfield(AllowedSequences.ZIFFERN);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        FachSuchenJtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(FachSuchenJtable);

        LagerortLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LagerortLabel.setText("Lagerort:");

        LagerfachbestandLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LagerfachbestandLabel.setText("Fachnummer:");

        ZeileLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ZeileLabel.setText("Zeile:");

        RegalnrLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        RegalnrLabel.setText("Regalnr.:");

        BelegtLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        BelegtLabel.setText("Belegt:");

        SpalteLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        SpalteLabel.setText("Spalte:");

        GrößeLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        GrößeLabel.setText("Größe:");

        SuchenmitteButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        SuchenmitteButton.setText("Suchen");
        SuchenmitteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fach_suchen(evt);
            }
        });

        zeile_label.setText("(Z01 - Z25)");

        spalte_label.setText("(S01 - S25)");

        RegalnummerbuttonGroup.add(H1JRadioButton);
        H1JRadioButton.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        H1JRadioButton.setText("H1");
        H1JRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                H1JRadioButtonActionPerformed(evt);
            }
        });

        RegalnummerbuttonGroup.add(H2JRadioButton);
        H2JRadioButton.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        H2JRadioButton.setText("H2");

        RegalnummerbuttonGroup.add(H3JRadioButton);
        H3JRadioButton.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        H3JRadioButton.setText("H3");

        RegalnummerbuttonGroup.add(H4JRadioButton);
        H4JRadioButton.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        H4JRadioButton.setText("H4");

        RegalnummerbuttonGroup.add(H5JRadioButton);
        H5JRadioButton.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        H5JRadioButton.setText("H5");

        GroesseButtonGroup.add(KleinJRadiobutton);
        KleinJRadiobutton.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        KleinJRadiobutton.setText("Klein");

        GroesseButtonGroup.add(MittelJRadioButton);
        MittelJRadioButton.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        MittelJRadioButton.setText("Mittel");

        GroesseButtonGroup.add(GrossJRadiobutton);
        GrossJRadiobutton.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        GrossJRadiobutton.setText("Groß");

        BelegtButtonGroup.add(BelegtJRadioButton);
        BelegtJRadioButton.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        BelegtJRadioButton.setText("ja");

        BelegtButtonGroup.add(NichtBelegtJRadioButton);
        NichtBelegtJRadioButton.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        NichtBelegtJRadioButton.setText("nein");

        LagerortButtonGroup.add(HochregallagerJRadioButton);
        HochregallagerJRadioButton.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        HochregallagerJRadioButton.setText("Hochregallager");

        LagerortButtonGroup.add(FreilagerJRadioButton);
        FreilagerJRadioButton.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        FreilagerJRadioButton.setText("Freilager");

        RegalnummerbuttonGroup.add(KeineAngabeRegalnummerJRadioButton);
        KeineAngabeRegalnummerJRadioButton.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        KeineAngabeRegalnummerJRadioButton.setSelected(true);
        KeineAngabeRegalnummerJRadioButton.setText("k.a.");

        GroesseButtonGroup.add(KeineAngabeGroesseJRadioButton);
        KeineAngabeGroesseJRadioButton.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        KeineAngabeGroesseJRadioButton.setSelected(true);
        KeineAngabeGroesseJRadioButton.setText("k.a.");

        BelegtButtonGroup.add(KeineAngabeBelegtJRadioButton);
        KeineAngabeBelegtJRadioButton.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        KeineAngabeBelegtJRadioButton.setSelected(true);
        KeineAngabeBelegtJRadioButton.setText("k.a.");

        LagerortButtonGroup.add(KeineAngabeLagerortJRadioButton);
        KeineAngabeLagerortJRadioButton.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        KeineAngabeLagerortJRadioButton.setSelected(true);
        KeineAngabeLagerortJRadioButton.setText("k.a.");

        javax.swing.GroupLayout suche_Fach_lagerplatzLayout = new javax.swing.GroupLayout(suche_Fach_lagerplatz);
        suche_Fach_lagerplatz.setLayout(suche_Fach_lagerplatzLayout);
        suche_Fach_lagerplatzLayout.setHorizontalGroup(
            suche_Fach_lagerplatzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(suche_Fach_lagerplatzLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(suche_Fach_lagerplatzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6)
                    .addGroup(suche_Fach_lagerplatzLayout.createSequentialGroup()
                        .addGroup(suche_Fach_lagerplatzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(suche_Fach_lagerplatzLayout.createSequentialGroup()
                                .addGroup(suche_Fach_lagerplatzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(suche_Fach_lagerplatzLayout.createSequentialGroup()
                                        .addComponent(LagerfachbestandLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(FachnummerlagerTextfield3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(suche_Fach_lagerplatzLayout.createSequentialGroup()
                                        .addGroup(suche_Fach_lagerplatzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(RegalnrLabel)
                                            .addComponent(GrößeLabel)
                                            .addComponent(BelegtLabel))
                                        .addGap(18, 18, 18)
                                        .addGroup(suche_Fach_lagerplatzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(suche_Fach_lagerplatzLayout.createSequentialGroup()
                                                .addGroup(suche_Fach_lagerplatzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(KleinJRadiobutton)
                                                    .addComponent(BelegtJRadioButton))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(suche_Fach_lagerplatzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(suche_Fach_lagerplatzLayout.createSequentialGroup()
                                                        .addComponent(NichtBelegtJRadioButton)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(KeineAngabeBelegtJRadioButton))
                                                    .addGroup(suche_Fach_lagerplatzLayout.createSequentialGroup()
                                                        .addComponent(MittelJRadioButton)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(GrossJRadiobutton)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(KeineAngabeGroesseJRadioButton))
                                                    .addGroup(suche_Fach_lagerplatzLayout.createSequentialGroup()
                                                        .addGap(72, 72, 72)
                                                        .addComponent(H4JRadioButton)
                                                        .addGap(5, 5, 5)
                                                        .addComponent(H5JRadioButton)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(KeineAngabeRegalnummerJRadioButton))))
                                            .addGroup(suche_Fach_lagerplatzLayout.createSequentialGroup()
                                                .addComponent(H1JRadioButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(H2JRadioButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(H3JRadioButton)))))
                                .addGap(220, 220, 220)
                                .addGroup(suche_Fach_lagerplatzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LagerortLabel)
                                    .addComponent(ZeileLabel)
                                    .addComponent(SpalteLabel))
                                .addGroup(suche_Fach_lagerplatzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(suche_Fach_lagerplatzLayout.createSequentialGroup()
                                        .addGroup(suche_Fach_lagerplatzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(suche_Fach_lagerplatzLayout.createSequentialGroup()
                                                .addGap(37, 37, 37)
                                                .addComponent(SpaltelagerTextfield3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, suche_Fach_lagerplatzLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ZeilelagerTextfield3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(suche_Fach_lagerplatzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(zeile_label)
                                            .addComponent(spalte_label)))
                                    .addGroup(suche_Fach_lagerplatzLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(HochregallagerJRadioButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(FreilagerJRadioButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(KeineAngabeLagerortJRadioButton))))
                            .addComponent(SuchenmitteButton))
                        .addGap(0, 11, Short.MAX_VALUE)))
                .addContainerGap())
        );
        suche_Fach_lagerplatzLayout.setVerticalGroup(
            suche_Fach_lagerplatzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(suche_Fach_lagerplatzLayout.createSequentialGroup()
                .addGroup(suche_Fach_lagerplatzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(suche_Fach_lagerplatzLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(suche_Fach_lagerplatzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LagerfachbestandLabel)
                            .addComponent(FachnummerlagerTextfield3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, suche_Fach_lagerplatzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LagerortLabel)
                        .addComponent(HochregallagerJRadioButton)
                        .addComponent(FreilagerJRadioButton)
                        .addComponent(KeineAngabeLagerortJRadioButton)))
                .addGap(4, 4, 4)
                .addGroup(suche_Fach_lagerplatzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegalnrLabel)
                    .addComponent(H1JRadioButton)
                    .addComponent(H2JRadioButton)
                    .addComponent(H3JRadioButton)
                    .addComponent(H4JRadioButton)
                    .addComponent(H5JRadioButton)
                    .addComponent(KeineAngabeRegalnummerJRadioButton)
                    .addComponent(ZeileLabel)
                    .addComponent(ZeilelagerTextfield3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zeile_label))
                .addGap(2, 2, 2)
                .addGroup(suche_Fach_lagerplatzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(suche_Fach_lagerplatzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SpalteLabel)
                        .addComponent(SpaltelagerTextfield3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(spalte_label))
                    .addGroup(suche_Fach_lagerplatzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(GrößeLabel)
                        .addComponent(KleinJRadiobutton)
                        .addComponent(MittelJRadioButton)
                        .addComponent(GrossJRadiobutton)
                        .addComponent(KeineAngabeGroesseJRadioButton)))
                .addGap(8, 8, 8)
                .addGroup(suche_Fach_lagerplatzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BelegtLabel)
                    .addComponent(BelegtJRadioButton)
                    .addComponent(NichtBelegtJRadioButton)
                    .addComponent(KeineAngabeBelegtJRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SuchenmitteButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Fach / Lagerplatz suchen", suche_Fach_lagerplatz);

        TeileImFachSuchenJtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(TeileImFachSuchenJtable);

        TeileIDLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TeileIDLabel.setText("Teile ID:");

        SuchenrechtsButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        SuchenrechtsButton.setText("Suchen");
        SuchenrechtsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeilImFachSuchenActionPerformed(evt);
            }
        });

        FachnrLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        FachnrLabel.setText("Fachnummer:");

        MaxMengeLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        MaxMengeLabel.setText("Max. Menge im Fach:");

        MinMengeLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        MinMengeLabel.setText("Mind. Menge im Fach:");

        LagerbestandLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LagerbestandLabel.setText("Lagerbestand:");

        AnschaffungsgrundLabel.setFont(AnschaffungsgrundLabel.getFont().deriveFont(AnschaffungsgrundLabel.getFont().getStyle() & ~java.awt.Font.BOLD));
        AnschaffungsgrundLabel.setText("Anschaffungsgrund:");

        javax.swing.GroupLayout suche_InhaltLayout = new javax.swing.GroupLayout(suche_Inhalt);
        suche_Inhalt.setLayout(suche_InhaltLayout);
        suche_InhaltLayout.setHorizontalGroup(
            suche_InhaltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(suche_InhaltLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(suche_InhaltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addGroup(suche_InhaltLayout.createSequentialGroup()
                        .addGroup(suche_InhaltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(suche_InhaltLayout.createSequentialGroup()
                                .addGroup(suche_InhaltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LagerbestandLabel)
                                    .addComponent(TeileIDLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(suche_InhaltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TeileIdlagerTextfield2, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                    .addComponent(LagerbestandlagerTextfield2, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(suche_InhaltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(FachnrLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(AnschaffungsgrundLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(suche_InhaltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FachnummerlagerTextfield2, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                    .addComponent(AnschaffungsgrundlagerTextfield2, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(suche_InhaltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MaxMengeLabel)
                                    .addComponent(MinMengeLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(suche_InhaltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MindestensMengeimFachlagerTextfield2, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                    .addComponent(MaximaleMengeimFachlagerTextfield2, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)))
                            .addComponent(SuchenrechtsButton))
                        .addGap(108, 108, 108)))
                .addContainerGap())
        );
        suche_InhaltLayout.setVerticalGroup(
            suche_InhaltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, suche_InhaltLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(suche_InhaltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TeileIDLabel)
                    .addComponent(TeileIdlagerTextfield2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FachnummerlagerTextfield2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FachnrLabel)
                    .addComponent(MaxMengeLabel)
                    .addComponent(MaximaleMengeimFachlagerTextfield2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(suche_InhaltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LagerbestandLabel)
                    .addComponent(LagerbestandlagerTextfield2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MinMengeLabel)
                    .addComponent(MindestensMengeimFachlagerTextfield2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AnschaffungsgrundlagerTextfield2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AnschaffungsgrundLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(SuchenrechtsButton)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        suche_InhaltLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {AnschaffungsgrundlagerTextfield2, FachnummerlagerTextfield2, LagerbestandlagerTextfield2, MaximaleMengeimFachlagerTextfield2, MindestensMengeimFachlagerTextfield2, TeileIdlagerTextfield2});

        jTabbedPane1.addTab("Menge / Teil im Fach suchen", suche_Inhalt);

        SuchenlinksButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        SuchenlinksButton.setText("Suchen");
        SuchenlinksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teile_suchen(evt);
            }
        });

        EuroLabel.setText("€");

        PreisLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        PreisLabel.setText("Preis:");

        MAKLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        MAKLabel.setText("Maximale Anzahl Klein:");

        TeileStammdatenLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        TeileStammdatenLabel.setText("Teile Stammdaten:");

        BezeichnungLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        BezeichnungLabel.setText("Bezeichnung:");

        IDlinksLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        IDlinksLabel.setText("Teile ID:");

        MaterialgruppeLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        MaterialgruppeLabel.setText("Materialgrupe:");

        TeiletypLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TeiletypLabel.setText("Teiletyp:");

        BaugruppeLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        BaugruppeLabel.setText("Baugruppe:");

        AlleTeileAnzeigenButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        AlleTeileAnzeigenButton.setText("alle Teile anzeigen");
        AlleTeileAnzeigenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alle_teile_suchen(evt);
            }
        });

        ZeichnungsnrLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ZeichnungsnrLabel.setText("Zeichnungsnummer:");

        MAMLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        MAMLabel.setText("Maximale Anzahl Mittel:");

        MAGLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        MAGLabel.setText("Maximale Anzahl Groß:");

        TeilSuchenJtable.setModel(new DefaultTableModel());
        jScrollPane4.setViewportView(TeilSuchenJtable);

        TeiletypComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "alle", "Kaufteile", "Werkzeuge", "Vorrichtungen", "unfertige Baugruppen", "Vorratsteile" }));

        BemerkungLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        BemerkungLabel.setText("Bemerkung:");

        javax.swing.GroupLayout suche_TeilLayout = new javax.swing.GroupLayout(suche_Teil);
        suche_Teil.setLayout(suche_TeilLayout);
        suche_TeilLayout.setHorizontalGroup(
            suche_TeilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(suche_TeilLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(suche_TeilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(suche_TeilLayout.createSequentialGroup()
                        .addGroup(suche_TeilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BaugruppeLabel)
                            .addComponent(ZeichnungsnrLabel)
                            .addComponent(MaterialgruppeLabel)
                            .addComponent(TeiletypLabel)
                            .addComponent(BezeichnungLabel)
                            .addComponent(IDlinksLabel))
                        .addGap(15, 15, 15)
                        .addGroup(suche_TeilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TeileIdlagerTextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(BezeichnunglagerTextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(MaterialgruppelagerTextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(ZeichnungsnummerlagerTextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(TeiletypComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BaugruppelagerTextfield, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addGroup(suche_TeilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BemerkungLabel)
                            .addComponent(PreisLabel)
                            .addComponent(MAKLabel)
                            .addComponent(MAMLabel)
                            .addComponent(MAGLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(suche_TeilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(PreislagerTextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(MaximaleAnzahlKleinlagerTextfield, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MaximaleAnzahlMittellagerTextfield, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MaximaleAnzahlGroßlagerTextfield, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BemerkungslagerTextfield, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EuroLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(112, Short.MAX_VALUE))
                    .addGroup(suche_TeilLayout.createSequentialGroup()
                        .addComponent(TeileStammdatenLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))))
            .addGroup(suche_TeilLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(suche_TeilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(suche_TeilLayout.createSequentialGroup()
                        .addComponent(AlleTeileAnzeigenButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SuchenlinksButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        suche_TeilLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BezeichnunglagerTextfield, MaterialgruppelagerTextfield, TeileIdlagerTextfield, ZeichnungsnummerlagerTextfield});

        suche_TeilLayout.setVerticalGroup(
            suche_TeilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(suche_TeilLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(TeileStammdatenLabel)
                .addGap(12, 12, 12)
                .addGroup(suche_TeilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDlinksLabel)
                    .addComponent(TeileIdlagerTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BemerkungLabel)
                    .addComponent(BemerkungslagerTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(suche_TeilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BezeichnungLabel)
                    .addComponent(BezeichnunglagerTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PreisLabel)
                    .addComponent(PreislagerTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EuroLabel))
                .addGap(13, 13, 13)
                .addGroup(suche_TeilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TeiletypLabel)
                    .addComponent(TeiletypComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MAKLabel)
                    .addComponent(MaximaleAnzahlKleinlagerTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(suche_TeilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MaterialgruppeLabel)
                    .addComponent(MaterialgruppelagerTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MAMLabel)
                    .addComponent(MaximaleAnzahlMittellagerTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(suche_TeilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ZeichnungsnrLabel)
                    .addComponent(ZeichnungsnummerlagerTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MAGLabel)
                    .addComponent(MaximaleAnzahlGroßlagerTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(suche_TeilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BaugruppeLabel)
                    .addComponent(BaugruppelagerTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(suche_TeilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AlleTeileAnzeigenButton)
                    .addComponent(SuchenlinksButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addContainerGap())
        );

        suche_TeilLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {BaugruppelagerTextfield, BemerkungslagerTextfield, BezeichnunglagerTextfield, MaterialgruppelagerTextfield, MaximaleAnzahlGroßlagerTextfield, MaximaleAnzahlKleinlagerTextfield, MaximaleAnzahlMittellagerTextfield, PreislagerTextfield, TeileIdlagerTextfield, TeiletypComboBox, ZeichnungsnummerlagerTextfield});

        jTabbedPane1.addTab("Teil suchen", suche_Teil);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alle_teile_suchen(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alle_teile_suchen
        try {
            DefaultTableModel table_model = new DefaultTableModel();
            ArrayList<Teil_Stammdaten> teile = suchen_controller.alle_teile_ausgeben();
            for (String columnname : suchen_controller.table_column_names_teilestamm) {
                table_model.addColumn(columnname);
            }

            for (Teil_Stammdaten teil : teile) {
                table_model.addRow(teil.toArray());
            }
            this.TeilSuchenJtable.setModel(table_model);

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Teil_Suchen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(Teil_Suchen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_alle_teile_suchen

    private void teile_suchen(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teile_suchen
        // Werte werden aus den Textfeldern und anderen Eingabefeldern ausgelesen und in ein zweidimensionales Array geschrieben
        // Es wird das Array erstellt was für die Erstellung des SELECTS wichtig ist
        String[][] suchwerte = new String[11][];
        String[] id = {"id", TeileIdlagerTextfield.getText()};
        String teilstring = (String) TeiletypComboBox.getSelectedItem();
        if ("alle".equals(teilstring)) {
            teilstring = "";
        }
        String[] teiletyp = {"typ", teilstring};
        String[] zeichnungsnummer = {"zeichnungsnummer", ZeichnungsnummerlagerTextfield.getText()};
        String[] materialgruppe = {"materialgruppe", MaterialgruppelagerTextfield.getText()};

        String[] preis = {"preis", PreislagerTextfield.getText()};
        String[] bezeichnung = {"bezeichnung", BezeichnunglagerTextfield.getText()};
        String[] baugruppe = {"baugruppe", BaugruppelagerTextfield.getText()};
        String[] bemerkung = {"bemerkung", BemerkungslagerTextfield.getText()};
        String[] maxanzahlklein = {"max_anz_klein", MaximaleAnzahlKleinlagerTextfield.getText()};
        String[] maxanzahlmittel = {"max_anz_mittel", MaximaleAnzahlMittellagerTextfield.getText()};
        String[] maxanzahlgross = {"max_anz_gross", MaximaleAnzahlGroßlagerTextfield.getText()};

        suchwerte[0] = id;
        suchwerte[1] = teiletyp;
        suchwerte[2] = zeichnungsnummer;
        suchwerte[3] = materialgruppe;
        suchwerte[4] = preis;
        suchwerte[5] = bezeichnung;
        suchwerte[6] = baugruppe;
        suchwerte[7] = maxanzahlklein;
        suchwerte[8] = maxanzahlmittel;
        suchwerte[9] = maxanzahlgross;
        suchwerte[10] = bemerkung;
        try {
            // Mit den ausgelesenen Daten wird mit hilfe des Controllers gesucht
            ArrayList<Teil_Stammdaten> teile = suchen_controller.teile_suchen(suchwerte);

            // Es erfolgt die erstellung des TableModels für JTable zur darstellung der Ergebnisse

            DefaultTableModel table_model = new DefaultTableModel();
            // Spaltennamen werden festgeelegt
            for (String columnname : suchen_controller.table_column_names_teilestamm) {
                table_model.addColumn(columnname);
            }
            // JTable wird mit Werten gefüllt
            for (Teil_Stammdaten teil : teile) {
                table_model.addRow(teil.toArray());
            }
            this.TeilSuchenJtable.setModel(table_model);
        } catch (ClassNotFoundException e) {
            Logger.getLogger(Teil_Suchen.class.getName()).log(Level.SEVERE, null, e);
        } catch (Exception e) {
            Logger.getLogger(Teil_Suchen.class.getName()).log(Level.SEVERE, null, e);
        }

    }//GEN-LAST:event_teile_suchen

    private void TeilImFachSuchenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeilImFachSuchenActionPerformed

        // Es wird das Array erstellt was für die Erstellung des SELECTS wichtig ist
        String[] teileid = {"teile_id", TeileIdlagerTextfield2.getText()};
        String[] lagerbestand = {"menge", LagerbestandlagerTextfield2.getText()};
        String[] fachnummer = {"fachnummer", FachnummerlagerTextfield2.getText()};
        String[] anschaffungsgrund = {"anschaffungsgrund", AnschaffungsgrundlagerTextfield2.getText()};
        String[] maximale_menge = {"max_menge", MaximaleMengeimFachlagerTextfield2.getText()};
        String[] mindestens_menge = {"mind_menge", MindestensMengeimFachlagerTextfield2.getText()};
        //String[] haltbarkeitsdatum = {"haltbarkeitsdatum", HaltbarkeitsdatumlagerTextfield2.getText()};

        String[][] suchwerte = new String[7][];
        suchwerte[0] = fachnummer;
        suchwerte[1] = teileid;
        suchwerte[2] = lagerbestand;
        suchwerte[3] = maximale_menge;
        suchwerte[4] = mindestens_menge;
        suchwerte[5] = anschaffungsgrund;
        //suchwerte[6] = haltbarkeitsdatum;

        // Es erfolgt die erstellung des TableModels für JTable zur darstellung der Ergebnisse
        DefaultTableModel table_model = new DefaultTableModel();
        for (String columnname : suchen_controller.table_column_names_lagerbestandskonto) {
            table_model.addColumn(columnname);
        }
        System.out.println(suchwerte[0][0] + "  " + suchwerte[0][1]);
        try {
            ArrayList<Lagerbestandskonto> lagerbestandskontos = suchen_controller.teile_im_fach_suchen(suchwerte);
            for (Lagerbestandskonto lagerbestandskonto : lagerbestandskontos) {
                lagerbestandskonto.toArray();
                table_model.addRow(lagerbestandskonto.get_Attribute());
            }
        } catch (Exception ex) {
            Logger.getLogger(Teil_Suchen.class.getName()).log(Level.SEVERE, null, ex);
        }

        this.TeileImFachSuchenJtable.setModel(table_model);


    }//GEN-LAST:event_TeilImFachSuchenActionPerformed

    private void fach_suchen(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fach_suchen

        // Auslesen aller Textfelder und RadioButtons
        String fachnummer = FachnummerlagerTextfield3.getText();
        String regalnummer = null;
        String groesse = null;
        String belegt = null;
        String lagerort = null;
        String zeile = ZeilelagerTextfield3.getText();
        String spalte = SpaltelagerTextfield3.getText();


        ButtonModel selected_regalnummer = RegalnummerbuttonGroup.getSelection();
        // Es wird nachgeschaut welcher RadioButton Selektiert ist indem die models verglichen werden
        if (H1JRadioButton.getModel() == selected_regalnummer) {
            regalnummer = "H1";
        } else if (H2JRadioButton.getModel() == selected_regalnummer) {
            regalnummer = "H2";
        } else if (H3JRadioButton.getModel() == selected_regalnummer) {
            regalnummer = "H3";
        } else if (H4JRadioButton.getModel() == selected_regalnummer) {
            regalnummer = "H4";
        } else if (H5JRadioButton.getModel() == selected_regalnummer) {
            regalnummer = "H5";
        } else if (KeineAngabeRegalnummerJRadioButton.getModel() == selected_regalnummer) {
            regalnummer = "";
        }

        ButtonModel selected_groesse = GroesseButtonGroup.getSelection();
        if (KleinJRadiobutton.getModel() == selected_groesse) {
            groesse = "K";
        } else if (MittelJRadioButton.getModel() == selected_groesse) {
            groesse = "M";
        } else if (GrossJRadiobutton.getModel() == selected_groesse) {
            groesse = "G";
        } else if (KeineAngabeGroesseJRadioButton.getModel() == selected_groesse) {
            groesse = "";
        }

        ButtonModel selected_belegt = BelegtButtonGroup.getSelection();
        if (BelegtJRadioButton.getModel() == selected_belegt) {
            belegt = "true";
        } else if (NichtBelegtJRadioButton.getModel() == selected_belegt) {
            belegt = "false";
        } else {
            belegt = "";
        }

        ButtonModel selected_lagerort = LagerortButtonGroup.getSelection();
        if (HochregallagerJRadioButton.getModel() == selected_lagerort) {
            lagerort = "H";
        } else if (FreilagerJRadioButton.getModel() == selected_lagerort) {
            lagerort = "F";
        } else {
            lagerort = "";
        }
        // Es wird das Array erstellt was für die Erstellung des SELECTS wichtig ist
        String[][] suchwerte = {
            {"fachnummer", fachnummer},
            {"lagerort", lagerort},
            {"hochregalnummer", regalnummer},
            {"zeile", zeile},
            {"spalte", spalte},
            {"groesse", groesse},
            {"belegt", belegt},};

        // Es erfolgt die erstellung des TableModels für JTable zur darstellung der Ergebnisse
        DefaultTableModel table_model = new DefaultTableModel();
        for (String columnname : suchen_controller.tabble_column_names_lagerfachstamm) {
            table_model.addColumn(columnname);
        }

        try {
            ArrayList<Lagerfachstamm> lagerfachstaemme = suchen_controller.fach_suchen(suchwerte);
            for (Lagerfachstamm lagerfachstamm : lagerfachstaemme) {
                table_model.addRow(lagerfachstamm.get_Attribute());
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Teil_Suchen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(Teil_Suchen.class.getName()).log(Level.SEVERE, null, ex);
        }

        FachSuchenJtable.setModel(table_model);

    }//GEN-LAST:event_fach_suchen

    private void H1JRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_H1JRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_H1JRadioButtonActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teil_Suchen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teil_Suchen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teil_Suchen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teil_Suchen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Teil_Suchen().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AlleTeileAnzeigenButton;
    private javax.swing.JLabel AnschaffungsgrundLabel;
    private view.LagerTextfield AnschaffungsgrundlagerTextfield2;
    private javax.swing.JLabel BaugruppeLabel;
    private view.LagerTextfield BaugruppelagerTextfield;
    private javax.swing.ButtonGroup BelegtButtonGroup;
    private javax.swing.JRadioButton BelegtJRadioButton;
    private javax.swing.JLabel BelegtLabel;
    private javax.swing.JLabel BemerkungLabel;
    private view.LagerTextfield BemerkungslagerTextfield;
    private javax.swing.JLabel BezeichnungLabel;
    private view.LagerTextfield BezeichnunglagerTextfield;
    private javax.swing.JLabel EuroLabel;
    private javax.swing.JTable FachSuchenJtable;
    private javax.swing.JLabel FachnrLabel;
    private view.LagerTextfield FachnummerlagerTextfield2;
    private view.LagerTextfield FachnummerlagerTextfield3;
    private javax.swing.JRadioButton FreilagerJRadioButton;
    private javax.swing.ButtonGroup GroesseButtonGroup;
    private javax.swing.JRadioButton GrossJRadiobutton;
    private javax.swing.JLabel GrößeLabel;
    private javax.swing.JRadioButton H1JRadioButton;
    private javax.swing.JRadioButton H2JRadioButton;
    private javax.swing.JRadioButton H3JRadioButton;
    private javax.swing.JRadioButton H4JRadioButton;
    private javax.swing.JRadioButton H5JRadioButton;
    private javax.swing.JRadioButton HochregallagerJRadioButton;
    private javax.swing.JLabel IDlinksLabel;
    private javax.swing.JRadioButton KeineAngabeBelegtJRadioButton;
    private javax.swing.JRadioButton KeineAngabeGroesseJRadioButton;
    private javax.swing.JRadioButton KeineAngabeLagerortJRadioButton;
    private javax.swing.JRadioButton KeineAngabeRegalnummerJRadioButton;
    private javax.swing.JRadioButton KleinJRadiobutton;
    private javax.swing.JLabel LagerbestandLabel;
    private view.LagerTextfield LagerbestandlagerTextfield2;
    private javax.swing.JLabel LagerfachbestandLabel;
    private javax.swing.ButtonGroup LagerortButtonGroup;
    private javax.swing.JLabel LagerortLabel;
    private javax.swing.JLabel MAGLabel;
    private javax.swing.JLabel MAKLabel;
    private javax.swing.JLabel MAMLabel;
    private javax.swing.JLabel MaterialgruppeLabel;
    private view.LagerTextfield MaterialgruppelagerTextfield;
    private javax.swing.JLabel MaxMengeLabel;
    private view.LagerTextfield MaximaleAnzahlGroßlagerTextfield;
    private view.LagerTextfield MaximaleAnzahlKleinlagerTextfield;
    private view.LagerTextfield MaximaleAnzahlMittellagerTextfield;
    private view.LagerTextfield MaximaleMengeimFachlagerTextfield2;
    private javax.swing.JLabel MinMengeLabel;
    private view.LagerTextfield MindestensMengeimFachlagerTextfield2;
    private javax.swing.JRadioButton MittelJRadioButton;
    private javax.swing.JRadioButton NichtBelegtJRadioButton;
    private javax.swing.JLabel PreisLabel;
    private view.LagerTextfield PreislagerTextfield;
    private javax.swing.JLabel RegalnrLabel;
    private javax.swing.ButtonGroup RegalnummerbuttonGroup;
    private javax.swing.JLabel SpalteLabel;
    private view.LagerTextfield SpaltelagerTextfield3;
    private javax.swing.JButton SuchenlinksButton;
    private javax.swing.JButton SuchenmitteButton;
    private javax.swing.JButton SuchenrechtsButton;
    private javax.swing.JTable TeilSuchenJtable;
    private javax.swing.JLabel TeileIDLabel;
    private view.LagerTextfield TeileIdlagerTextfield;
    private view.LagerTextfield TeileIdlagerTextfield2;
    private javax.swing.JTable TeileImFachSuchenJtable;
    private javax.swing.JLabel TeileStammdatenLabel;
    private javax.swing.JComboBox TeiletypComboBox;
    private javax.swing.JLabel TeiletypLabel;
    private javax.swing.JLabel ZeichnungsnrLabel;
    private view.LagerTextfield ZeichnungsnummerlagerTextfield;
    private javax.swing.JLabel ZeileLabel;
    private view.LagerTextfield ZeilelagerTextfield3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel spalte_label;
    private javax.swing.JPanel suche_Fach_lagerplatz;
    private javax.swing.JPanel suche_Inhalt;
    private javax.swing.JPanel suche_Teil;
    private javax.swing.JLabel zeile_label;
    // End of variables declaration//GEN-END:variables
}
