/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */
package view;

/**
 *
 * @author Stephan
 */
public class Teile_Suchen extends javax.swing.JFrame {

    /**
     * Creates new form Teile_Suchen
     */
    public Teile_Suchen() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Panellinks = new javax.swing.JPanel();
        TeileStammdatenLabel = new javax.swing.JLabel();
        IDlinksLabel = new javax.swing.JLabel();
        BezeichnungLabel = new javax.swing.JLabel();
        TeiletypLabel = new javax.swing.JLabel();
        MaterialgruppeLabel = new javax.swing.JLabel();
        ZeichnungsnrLabel = new javax.swing.JLabel();
        BaugruppeLabel = new javax.swing.JLabel();
        MAGLabel = new javax.swing.JLabel();
        MAMLabel = new javax.swing.JLabel();
        MAKLabel = new javax.swing.JLabel();
        PreisLabel = new javax.swing.JLabel();
        IDTextfield = new javax.swing.JTextField();
        BezTextfield = new javax.swing.JTextField();
        MaterialTextfield = new javax.swing.JTextField();
        ZNrTextfield = new javax.swing.JTextField();
        TeiletypTextfield = new javax.swing.JTextField();
        BaugruppeTextfield = new javax.swing.JTextField();
        PreisTextfield = new javax.swing.JTextField();
        MAKTextfield = new javax.swing.JTextField();
        MAMTextfield = new javax.swing.JTextField();
        MAGTextfield = new javax.swing.JTextField();
        SuchenlinksButton = new javax.swing.JButton();
        EuroLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Panelrechts = new javax.swing.JPanel();
        LagerbestandLabel = new javax.swing.JLabel();
        MinMengeLabel = new javax.swing.JLabel();
        MaxMengeLabel = new javax.swing.JLabel();
        HaltbarkeitsLabel = new javax.swing.JLabel();
        FachnrLabel = new javax.swing.JLabel();
        TeileIDLabel = new javax.swing.JLabel();
        SuchenrechtsButton = new javax.swing.JButton();
        LagerbestandTextfield = new javax.swing.JTextField();
        MinTextfield = new javax.swing.JTextField();
        MaxTextfield = new javax.swing.JTextField();
        DatumTextfield = new javax.swing.JTextField();
        FachnrTextfield = new javax.swing.JTextField();
        TeileIDrechtsTextfield = new javax.swing.JTextField();
        Panelmitte = new javax.swing.JPanel();
        LagerfachbestandLabel = new javax.swing.JLabel();
        LagerortLabel = new javax.swing.JLabel();
        RegalnrLabel = new javax.swing.JLabel();
        ZeileLabel = new javax.swing.JLabel();
        SpalteLabel = new javax.swing.JLabel();
        BelegtLabel = new javax.swing.JLabel();
        GrößeLabel = new javax.swing.JLabel();
        SuchenmitteButton = new javax.swing.JButton();
        neinCB = new javax.swing.JCheckBox();
        jaCB = new javax.swing.JCheckBox();
        mCB = new javax.swing.JCheckBox();
        gCB = new javax.swing.JCheckBox();
        kCB = new javax.swing.JCheckBox();
        ZeileTextfield = new javax.swing.JTextField();
        SpalteTextfield = new javax.swing.JTextField();
        H1CB = new javax.swing.JCheckBox();
        H2CB = new javax.swing.JCheckBox();
        H4CB = new javax.swing.JCheckBox();
        H3CB = new javax.swing.JCheckBox();
        FCB = new javax.swing.JCheckBox();
        HCB = new javax.swing.JCheckBox();
        LagerfachbestandTextfield = new javax.swing.JTextField();
        H5CB = new javax.swing.JCheckBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        Datei = new javax.swing.JMenu();
        Bearbeiten = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        Panellinks.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TeileStammdatenLabel.setFont(new java.awt.Font("Arial", 0, 12));
        TeileStammdatenLabel.setText("Teile Stammdaten:");

        IDlinksLabel.setFont(new java.awt.Font("Arial", 0, 12));
        IDlinksLabel.setText("Teile ID:");

        BezeichnungLabel.setFont(new java.awt.Font("Arial", 0, 12));
        BezeichnungLabel.setText("Bezeichnung:");

        TeiletypLabel.setFont(new java.awt.Font("Arial", 0, 12));
        TeiletypLabel.setText("Teiletyp:");

        MaterialgruppeLabel.setFont(new java.awt.Font("Arial", 0, 12));
        MaterialgruppeLabel.setText("Materialgrupe:");

        ZeichnungsnrLabel.setFont(new java.awt.Font("Arial", 0, 12));
        ZeichnungsnrLabel.setText("Zeichnungsnr.:");

        BaugruppeLabel.setFont(new java.awt.Font("Arial", 0, 12));
        BaugruppeLabel.setText("Baugruppe:");

        MAGLabel.setFont(new java.awt.Font("Arial", 0, 12));
        MAGLabel.setText("MAG:");

        MAMLabel.setFont(new java.awt.Font("Arial", 0, 12));
        MAMLabel.setText("MAM:");

        MAKLabel.setFont(new java.awt.Font("Arial", 0, 12));
        MAKLabel.setText("MAK:");

        PreisLabel.setFont(new java.awt.Font("Arial", 0, 12));
        PreisLabel.setText("Preis:");

        IDTextfield.setFont(new java.awt.Font("Arial", 0, 12));

        BezTextfield.setFont(new java.awt.Font("Arial", 0, 12));

        MaterialTextfield.setFont(new java.awt.Font("Arial", 0, 12));

        ZNrTextfield.setFont(new java.awt.Font("Arial", 0, 12));

        TeiletypTextfield.setFont(new java.awt.Font("Arial", 0, 12));

        BaugruppeTextfield.setFont(new java.awt.Font("Arial", 0, 12));

        PreisTextfield.setFont(new java.awt.Font("Arial", 0, 12));

        MAKTextfield.setFont(new java.awt.Font("Arial", 0, 12));

        MAMTextfield.setFont(new java.awt.Font("Arial", 0, 12));

        MAGTextfield.setFont(new java.awt.Font("Arial", 0, 12));

        SuchenlinksButton.setFont(new java.awt.Font("Arial", 0, 12));
        SuchenlinksButton.setText("Suchen");

        EuroLabel.setText("€");

        jButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton1.setText("alle Teile anzeigen");

        javax.swing.GroupLayout PanellinksLayout = new javax.swing.GroupLayout(Panellinks);
        Panellinks.setLayout(PanellinksLayout);
        PanellinksLayout.setHorizontalGroup(
            PanellinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanellinksLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanellinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanellinksLayout.createSequentialGroup()
                        .addGroup(PanellinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PanellinksLayout.createSequentialGroup()
                                .addGroup(PanellinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MaterialgruppeLabel)
                                    .addComponent(IDlinksLabel)
                                    .addComponent(BezeichnungLabel)
                                    .addComponent(TeiletypLabel)
                                    .addComponent(BaugruppeLabel)
                                    .addComponent(ZeichnungsnrLabel))
                                .addGap(22, 22, 22)
                                .addGroup(PanellinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(BaugruppeTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(PanellinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(BezTextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                        .addComponent(IDTextfield)
                                        .addComponent(TeiletypTextfield)
                                        .addComponent(MaterialTextfield)
                                        .addComponent(ZNrTextfield))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanellinksLayout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(SuchenlinksButton)))
                        .addGap(37, 37, 37)
                        .addGroup(PanellinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PreisLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanellinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(MAMLabel)
                                .addComponent(MAKLabel)
                                .addComponent(MAGLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanellinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MAKTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MAMTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MAGTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanellinksLayout.createSequentialGroup()
                                .addComponent(PreisTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(EuroLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(TeileStammdatenLabel))
                .addContainerGap())
        );
        PanellinksLayout.setVerticalGroup(
            PanellinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanellinksLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TeileStammdatenLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanellinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDlinksLabel)
                    .addComponent(IDTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanellinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TeiletypLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanellinksLayout.createSequentialGroup()
                        .addGroup(PanellinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BezTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BezeichnungLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanellinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TeiletypTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PreisTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PreisLabel)
                            .addComponent(EuroLabel))))
                .addGap(11, 11, 11)
                .addGroup(PanellinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanellinksLayout.createSequentialGroup()
                        .addGroup(PanellinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MAKTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MAKLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanellinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MAMTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MAMLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanellinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MAGTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MAGLabel)))
                    .addGroup(PanellinksLayout.createSequentialGroup()
                        .addGroup(PanellinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MaterialTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MaterialgruppeLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanellinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ZNrTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ZeichnungsnrLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanellinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BaugruppeTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BaugruppeLabel))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanellinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SuchenlinksButton)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        Panelrechts.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        LagerbestandLabel.setFont(new java.awt.Font("Arial", 0, 12));
        LagerbestandLabel.setText("Lagerbestand:");

        MinMengeLabel.setFont(new java.awt.Font("Arial", 0, 12));
        MinMengeLabel.setText("Mind. Menge im Fach:");

        MaxMengeLabel.setFont(new java.awt.Font("Arial", 0, 12));
        MaxMengeLabel.setText("Max. Menge im Fach:");

        HaltbarkeitsLabel.setFont(new java.awt.Font("Arial", 0, 12));
        HaltbarkeitsLabel.setText("Haltbarkeitsdatum:");

        FachnrLabel.setFont(new java.awt.Font("Arial", 0, 12));
        FachnrLabel.setText("Fachnummer:");

        TeileIDLabel.setFont(new java.awt.Font("Arial", 0, 12));
        TeileIDLabel.setText("Teile ID:");

        SuchenrechtsButton.setFont(new java.awt.Font("Arial", 0, 12));
        SuchenrechtsButton.setText("Suchen");

        LagerbestandTextfield.setFont(new java.awt.Font("Arial", 0, 12));

        MinTextfield.setFont(new java.awt.Font("Arial", 0, 12));

        MaxTextfield.setFont(new java.awt.Font("Arial", 0, 12));

        DatumTextfield.setFont(new java.awt.Font("Arial", 0, 12));

        FachnrTextfield.setFont(new java.awt.Font("Arial", 0, 12));

        TeileIDrechtsTextfield.setFont(new java.awt.Font("Arial", 0, 12));

        javax.swing.GroupLayout PanelrechtsLayout = new javax.swing.GroupLayout(Panelrechts);
        Panelrechts.setLayout(PanelrechtsLayout);
        PanelrechtsLayout.setHorizontalGroup(
            PanelrechtsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelrechtsLayout.createSequentialGroup()
                .addGroup(PanelrechtsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelrechtsLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(LagerbestandLabel)
                        .addGap(83, 83, 83)
                        .addComponent(LagerbestandTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelrechtsLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(MinMengeLabel)
                        .addGap(44, 44, 44)
                        .addComponent(MinTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelrechtsLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(MaxMengeLabel)
                        .addGap(49, 49, 49)
                        .addComponent(MaxTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelrechtsLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(HaltbarkeitsLabel)
                        .addGap(59, 59, 59)
                        .addComponent(DatumTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelrechtsLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(FachnrLabel)
                        .addGap(86, 86, 86)
                        .addComponent(FachnrTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelrechtsLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(TeileIDLabel)
                        .addGap(118, 118, 118)
                        .addComponent(TeileIDrechtsTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelrechtsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(SuchenrechtsButton)))
                .addContainerGap())
        );
        PanelrechtsLayout.setVerticalGroup(
            PanelrechtsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelrechtsLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(PanelrechtsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelrechtsLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(LagerbestandLabel))
                    .addComponent(LagerbestandTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelrechtsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelrechtsLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(MinMengeLabel))
                    .addComponent(MinTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelrechtsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelrechtsLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(MaxMengeLabel))
                    .addComponent(MaxTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelrechtsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelrechtsLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(HaltbarkeitsLabel))
                    .addComponent(DatumTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelrechtsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelrechtsLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(FachnrLabel))
                    .addComponent(FachnrTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelrechtsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelrechtsLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(TeileIDLabel))
                    .addComponent(TeileIDrechtsTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SuchenrechtsButton)
                .addContainerGap())
        );

        Panelmitte.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        LagerfachbestandLabel.setFont(new java.awt.Font("Arial", 0, 12));
        LagerfachbestandLabel.setText("Lagerfachbestand:");

        LagerortLabel.setFont(new java.awt.Font("Arial", 0, 12));
        LagerortLabel.setText("Lagerort:");

        RegalnrLabel.setFont(new java.awt.Font("Arial", 0, 12));
        RegalnrLabel.setText("Regalnr.:");

        ZeileLabel.setFont(new java.awt.Font("Arial", 0, 12));
        ZeileLabel.setText("Zeile:");

        SpalteLabel.setFont(new java.awt.Font("Arial", 0, 12));
        SpalteLabel.setText("Spalte:");

        BelegtLabel.setFont(new java.awt.Font("Arial", 0, 12));
        BelegtLabel.setText("Belegt:");

        GrößeLabel.setFont(new java.awt.Font("Arial", 0, 12));
        GrößeLabel.setText("Größe:");

        SuchenmitteButton.setFont(new java.awt.Font("Arial", 0, 12));
        SuchenmitteButton.setText("Suchen");

        neinCB.setFont(new java.awt.Font("Arial", 0, 12));
        neinCB.setText("nein");

        jaCB.setFont(new java.awt.Font("Arial", 0, 12));
        jaCB.setText("ja");

        mCB.setFont(new java.awt.Font("Arial", 0, 12));
        mCB.setText("M");
        mCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCBActionPerformed(evt);
            }
        });

        gCB.setFont(new java.awt.Font("Arial", 0, 12));
        gCB.setText("G");

        kCB.setFont(new java.awt.Font("Arial", 0, 12));
        kCB.setText("K");

        ZeileTextfield.setFont(new java.awt.Font("Arial", 0, 12));

        SpalteTextfield.setFont(new java.awt.Font("Arial", 0, 12));

        H1CB.setFont(new java.awt.Font("Arial", 0, 12));
        H1CB.setText("H1");

        H2CB.setFont(new java.awt.Font("Arial", 0, 12));
        H2CB.setText("H2");

        H4CB.setFont(new java.awt.Font("Arial", 0, 12));
        H4CB.setText("H4");

        H3CB.setFont(new java.awt.Font("Arial", 0, 12));
        H3CB.setText("H3");

        FCB.setFont(new java.awt.Font("Arial", 0, 12));
        FCB.setText("F");

        HCB.setFont(new java.awt.Font("Arial", 0, 12));
        HCB.setText("H");

        LagerfachbestandTextfield.setFont(new java.awt.Font("Arial", 0, 12));

        H5CB.setFont(new java.awt.Font("Arial", 0, 12));
        H5CB.setText("H5");

        javax.swing.GroupLayout PanelmitteLayout = new javax.swing.GroupLayout(Panelmitte);
        Panelmitte.setLayout(PanelmitteLayout);
        PanelmitteLayout.setHorizontalGroup(
            PanelmitteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelmitteLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(PanelmitteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelmitteLayout.createSequentialGroup()
                        .addComponent(LagerfachbestandLabel)
                        .addGap(18, 18, 18)
                        .addComponent(LagerfachbestandTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelmitteLayout.createSequentialGroup()
                        .addComponent(LagerortLabel)
                        .addGap(18, 18, 18)
                        .addComponent(FCB)
                        .addGap(11, 11, 11)
                        .addComponent(HCB))
                    .addGroup(PanelmitteLayout.createSequentialGroup()
                        .addComponent(RegalnrLabel)
                        .addGap(18, 18, 18)
                        .addComponent(H1CB)
                        .addGap(2, 2, 2)
                        .addComponent(H2CB)
                        .addGap(2, 2, 2)
                        .addComponent(H3CB)
                        .addGap(2, 2, 2)
                        .addComponent(H4CB)
                        .addGap(2, 2, 2)
                        .addComponent(H5CB))
                    .addGroup(PanelmitteLayout.createSequentialGroup()
                        .addComponent(ZeileLabel)
                        .addGap(38, 38, 38)
                        .addComponent(ZeileTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelmitteLayout.createSequentialGroup()
                        .addComponent(SpalteLabel)
                        .addGap(30, 30, 30)
                        .addComponent(SpalteTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelmitteLayout.createSequentialGroup()
                        .addComponent(BelegtLabel)
                        .addGap(34, 34, 34)
                        .addComponent(jaCB)
                        .addGap(2, 2, 2)
                        .addComponent(neinCB))
                    .addGroup(PanelmitteLayout.createSequentialGroup()
                        .addComponent(GrößeLabel)
                        .addGap(34, 34, 34)
                        .addComponent(kCB)
                        .addGap(2, 2, 2)
                        .addComponent(mCB)
                        .addGap(2, 2, 2)
                        .addComponent(gCB))
                    .addComponent(SuchenmitteButton))
                .addContainerGap())
        );
        PanelmitteLayout.setVerticalGroup(
            PanelmitteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelmitteLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(PanelmitteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelmitteLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(LagerfachbestandLabel))
                    .addComponent(LagerfachbestandTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelmitteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelmitteLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(LagerortLabel))
                    .addComponent(FCB)
                    .addComponent(HCB))
                .addGap(8, 8, 8)
                .addGroup(PanelmitteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelmitteLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(RegalnrLabel))
                    .addComponent(H1CB)
                    .addComponent(H2CB)
                    .addComponent(H3CB)
                    .addComponent(H4CB)
                    .addComponent(H5CB))
                .addGap(18, 18, 18)
                .addGroup(PanelmitteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelmitteLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(ZeileLabel))
                    .addComponent(ZeileTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(PanelmitteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelmitteLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(SpalteLabel))
                    .addComponent(SpalteTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelmitteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelmitteLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(BelegtLabel))
                    .addComponent(jaCB)
                    .addComponent(neinCB))
                .addGap(18, 18, 18)
                .addGroup(PanelmitteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelmitteLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(GrößeLabel))
                    .addComponent(kCB)
                    .addComponent(mCB)
                    .addComponent(gCB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(SuchenmitteButton)
                .addContainerGap())
        );

        Datei.setText("Datei");
        jMenuBar1.add(Datei);

        Bearbeiten.setText("Bearbeiten");
        jMenuBar1.add(Bearbeiten);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panellinks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panelmitte, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panelrechts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1157, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Panelrechts, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panellinks, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panelmitte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mCBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teile_Suchen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teile_Suchen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teile_Suchen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teile_Suchen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Teile_Suchen().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BaugruppeLabel;
    private javax.swing.JTextField BaugruppeTextfield;
    private javax.swing.JMenu Bearbeiten;
    private javax.swing.JLabel BelegtLabel;
    private javax.swing.JTextField BezTextfield;
    private javax.swing.JLabel BezeichnungLabel;
    private javax.swing.JMenu Datei;
    private javax.swing.JTextField DatumTextfield;
    private javax.swing.JLabel EuroLabel;
    private javax.swing.JCheckBox FCB;
    private javax.swing.JLabel FachnrLabel;
    private javax.swing.JTextField FachnrTextfield;
    private javax.swing.JLabel GrößeLabel;
    private javax.swing.JCheckBox H1CB;
    private javax.swing.JCheckBox H2CB;
    private javax.swing.JCheckBox H3CB;
    private javax.swing.JCheckBox H4CB;
    private javax.swing.JCheckBox H5CB;
    private javax.swing.JCheckBox HCB;
    private javax.swing.JLabel HaltbarkeitsLabel;
    private javax.swing.JTextField IDTextfield;
    private javax.swing.JLabel IDlinksLabel;
    private javax.swing.JLabel LagerbestandLabel;
    private javax.swing.JTextField LagerbestandTextfield;
    private javax.swing.JLabel LagerfachbestandLabel;
    private javax.swing.JTextField LagerfachbestandTextfield;
    private javax.swing.JLabel LagerortLabel;
    private javax.swing.JLabel MAGLabel;
    private javax.swing.JTextField MAGTextfield;
    private javax.swing.JLabel MAKLabel;
    private javax.swing.JTextField MAKTextfield;
    private javax.swing.JLabel MAMLabel;
    private javax.swing.JTextField MAMTextfield;
    private javax.swing.JTextField MaterialTextfield;
    private javax.swing.JLabel MaterialgruppeLabel;
    private javax.swing.JLabel MaxMengeLabel;
    private javax.swing.JTextField MaxTextfield;
    private javax.swing.JLabel MinMengeLabel;
    private javax.swing.JTextField MinTextfield;
    private javax.swing.JPanel Panellinks;
    private javax.swing.JPanel Panelmitte;
    private javax.swing.JPanel Panelrechts;
    private javax.swing.JLabel PreisLabel;
    private javax.swing.JTextField PreisTextfield;
    private javax.swing.JLabel RegalnrLabel;
    private javax.swing.JLabel SpalteLabel;
    private javax.swing.JTextField SpalteTextfield;
    private javax.swing.JButton SuchenlinksButton;
    private javax.swing.JButton SuchenmitteButton;
    private javax.swing.JButton SuchenrechtsButton;
    private javax.swing.JLabel TeileIDLabel;
    private javax.swing.JTextField TeileIDrechtsTextfield;
    private javax.swing.JLabel TeileStammdatenLabel;
    private javax.swing.JLabel TeiletypLabel;
    private javax.swing.JTextField TeiletypTextfield;
    private javax.swing.JTextField ZNrTextfield;
    private javax.swing.JLabel ZeichnungsnrLabel;
    private javax.swing.JLabel ZeileLabel;
    private javax.swing.JTextField ZeileTextfield;
    private javax.swing.JCheckBox gCB;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JCheckBox jaCB;
    private javax.swing.JCheckBox kCB;
    private javax.swing.JCheckBox mCB;
    private javax.swing.JCheckBox neinCB;
    // End of variables declaration//GEN-END:variables
}
