/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */
package view;

/**
 *
 * @author Keleseth
 */
public class Teilestamm_Einsehen extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Teilestamm_Einsehen() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField12 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel1.setText("Teile Stammdaten");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 70, 101, 15);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel2.setText("ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 100, 12, 15);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel3.setText("Zeichn.Nr.");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 130, 56, 15);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel4.setText("MAM");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 170, 25, 15);

        jTextField1.setMinimumSize(new java.awt.Dimension(100, 0));
        getContentPane().add(jTextField1);
        jTextField1.setBounds(80, 90, 100, 20);

        jTextField2.setMinimumSize(new java.awt.Dimension(100, 0));
        getContentPane().add(jTextField2);
        jTextField2.setBounds(80, 120, 100, 20);

        jTextField3.setMinimumSize(new java.awt.Dimension(100, 0));
        getContentPane().add(jTextField3);
        jTextField3.setBounds(80, 160, 100, 20);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel5.setText("Bezeichnung");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(190, 100, 71, 15);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel6.setText("Baugruppe");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(200, 130, 61, 15);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel7.setText("MAG");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(210, 170, 25, 15);

        jTextField4.setMinimumSize(new java.awt.Dimension(100, 0));
        getContentPane().add(jTextField4);
        jTextField4.setBounds(270, 90, 108, 20);

        jTextField5.setMinimumSize(new java.awt.Dimension(100, 0));
        getContentPane().add(jTextField5);
        jTextField5.setBounds(270, 120, 108, 20);

        jTextField6.setMinimumSize(new java.awt.Dimension(100, 0));
        getContentPane().add(jTextField6);
        jTextField6.setBounds(270, 160, 108, 20);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel8.setText("Teiletyp");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(400, 100, 42, 15);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel9.setText("Preis");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(400, 130, 29, 15);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel10.setText("Bestände");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(400, 170, 53, 15);

        jTextField7.setMinimumSize(new java.awt.Dimension(100, 0));
        getContentPane().add(jTextField7);
        jTextField7.setBounds(470, 160, 100, 20);

        jTextField8.setMinimumSize(new java.awt.Dimension(100, 0));
        getContentPane().add(jTextField8);
        jTextField8.setBounds(470, 120, 100, 20);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel11.setText("Materialgruppe");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(610, 100, 82, 15);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel12.setText("MAK");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(610, 130, 24, 15);

        jButton1.setText("anzeigen");
        getContentPane().add(jButton1);
        jButton1.setBounds(610, 160, 82, 23);

        jTextField12.setFont(new java.awt.Font("Arial", 0, 12));
        getContentPane().add(jTextField12);
        jTextField12.setBounds(470, 90, 100, 21);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 286, 1128, 168);

        jMenu1.setText("Datei");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Bearbeiten");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teilestamm_Einsehen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teilestamm_Einsehen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teilestamm_Einsehen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teilestamm_Einsehen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Teilestamm_Einsehen().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
