/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */
package view;

import control.Suchen_Controller;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Teil_Stammdaten;
import model.TeileTypET;
import javax.swing.DefaultComboBoxModel;
import model.Datenbankverbindung;
import model.Select_Allgemein;

/**
 *
 * @author Matthias Sommer
 */
public class Teil_Suchen extends javax.swing.JFrame {
    
    private Suchen_Controller suchen_controller;

    /**
     * Creates new form Teil_Suchen
     */
    public Teil_Suchen() {
        initComponents();
        suchen_controller = new Suchen_Controller();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        suche_Fach_lagerplatz = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        LagerortLabel = new javax.swing.JLabel();
        LagerfachbestandLabel = new javax.swing.JLabel();
        ZeileLabel = new javax.swing.JLabel();
        RegalnrLabel = new javax.swing.JLabel();
        BelegtLabel = new javax.swing.JLabel();
        SpalteLabel = new javax.swing.JLabel();
        FCB = new javax.swing.JCheckBox();
        H3CB = new javax.swing.JCheckBox();
        H1CB = new javax.swing.JCheckBox();
        SpalteTextfield = new javax.swing.JTextField();
        H4CB = new javax.swing.JCheckBox();
        H2CB = new javax.swing.JCheckBox();
        HCB = new javax.swing.JCheckBox();
        gCB = new javax.swing.JCheckBox();
        GrößeLabel = new javax.swing.JLabel();
        mCB = new javax.swing.JCheckBox();
        SuchenmitteButton = new javax.swing.JButton();
        ZeileTextfield = new javax.swing.JTextField();
        neinCB = new javax.swing.JCheckBox();
        kCB = new javax.swing.JCheckBox();
        jaCB = new javax.swing.JCheckBox();
        H5CB = new javax.swing.JCheckBox();
        LagerfachbestandTextfield = new javax.swing.JTextField();
        zeile_label = new javax.swing.JLabel();
        spalte_label = new javax.swing.JLabel();
        suche_Inhalt = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        LagerbestandTextfield = new javax.swing.JTextField();
        MinTextfield = new javax.swing.JTextField();
        TeileIDLabel = new javax.swing.JLabel();
        SuchenrechtsButton = new javax.swing.JButton();
        FachnrLabel = new javax.swing.JLabel();
        HaltbarkeitsLabel = new javax.swing.JLabel();
        MaxMengeLabel = new javax.swing.JLabel();
        TeileIDrechtsTextfield = new javax.swing.JTextField();
        FachnrTextfield = new javax.swing.JTextField();
        DatumTextfield = new javax.swing.JTextField();
        MinMengeLabel = new javax.swing.JLabel();
        MaxTextfield = new javax.swing.JTextField();
        LagerbestandLabel = new javax.swing.JLabel();
        suche_Teil = new javax.swing.JPanel();
        MAMTextfield = new javax.swing.JTextField();
        MAGTextfield = new javax.swing.JTextField();
        SuchenlinksButton = new javax.swing.JButton();
        EuroLabel = new javax.swing.JLabel();
        PreisLabel = new javax.swing.JLabel();
        IDTextfield = new javax.swing.JTextField();
        MAKLabel = new javax.swing.JLabel();
        TeileStammdatenLabel = new javax.swing.JLabel();
        BezeichnungLabel = new javax.swing.JLabel();
        ZNrTextfield = new javax.swing.JTextField();
        IDlinksLabel = new javax.swing.JLabel();
        MaterialTextfield = new javax.swing.JTextField();
        MaterialgruppeLabel = new javax.swing.JLabel();
        BezTextfield = new javax.swing.JTextField();
        TeiletypLabel = new javax.swing.JLabel();
        BaugruppeLabel = new javax.swing.JLabel();
        AlleTeileAnzeigenButton = new javax.swing.JButton();
        MAKTextfield = new javax.swing.JTextField();
        ZeichnungsnrLabel = new javax.swing.JLabel();
        PreisTextfield = new javax.swing.JTextField();
        MAMLabel = new javax.swing.JLabel();
        BaugruppeTextfield = new javax.swing.JTextField();
        MAGLabel = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        TeiletypComboBox = new javax.swing.JComboBox();
        BemerkungLabel = new javax.swing.JLabel();
        BemerkungLagerTextfield = new view.LagerTextfield();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(jTable6);

        LagerortLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LagerortLabel.setText("Lagerort:");

        LagerfachbestandLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LagerfachbestandLabel.setText("Fachnummer:");

        ZeileLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ZeileLabel.setText("Zeile:");

        RegalnrLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        RegalnrLabel.setText("Regalnr.:");

        BelegtLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        BelegtLabel.setText("Belegt:");

        SpalteLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        SpalteLabel.setText("Spalte:");

        FCB.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        FCB.setText("F");

        H3CB.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        H3CB.setText("H3");

        H1CB.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        H1CB.setText("H1");

        SpalteTextfield.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        H4CB.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        H4CB.setText("H4");

        H2CB.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        H2CB.setText("H2");

        HCB.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        HCB.setText("H");

        gCB.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        gCB.setText("G");

        GrößeLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        GrößeLabel.setText("Größe:");

        mCB.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        mCB.setText("M");

        SuchenmitteButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        SuchenmitteButton.setText("Suchen");

        ZeileTextfield.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        neinCB.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        neinCB.setText("nein");

        kCB.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        kCB.setText("K");

        jaCB.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jaCB.setText("ja");

        H5CB.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        H5CB.setText("H5");

        LagerfachbestandTextfield.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        zeile_label.setText("(Z1 - Z25)");

        spalte_label.setText("(S1 - S25)");

        javax.swing.GroupLayout suche_Fach_lagerplatzLayout = new javax.swing.GroupLayout(suche_Fach_lagerplatz);
        suche_Fach_lagerplatz.setLayout(suche_Fach_lagerplatzLayout);
        suche_Fach_lagerplatzLayout.setHorizontalGroup(
            suche_Fach_lagerplatzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(suche_Fach_lagerplatzLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(suche_Fach_lagerplatzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(suche_Fach_lagerplatzLayout.createSequentialGroup()
                        .addComponent(LagerfachbestandLabel)
                        .addGap(18, 18, 18)
                        .addComponent(LagerfachbestandTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(suche_Fach_lagerplatzLayout.createSequentialGroup()
                        .addComponent(LagerortLabel)
                        .addGap(18, 18, 18)
                        .addComponent(FCB)
                        .addGap(11, 11, 11)
                        .addComponent(HCB))
                    .addGroup(suche_Fach_lagerplatzLayout.createSequentialGroup()
                        .addComponent(SpalteLabel)
                        .addGap(30, 30, 30)
                        .addComponent(SpalteTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(spalte_label))
                    .addGroup(suche_Fach_lagerplatzLayout.createSequentialGroup()
                        .addComponent(BelegtLabel)
                        .addGap(34, 34, 34)
                        .addComponent(jaCB)
                        .addGap(2, 2, 2)
                        .addComponent(neinCB))
                    .addGroup(suche_Fach_lagerplatzLayout.createSequentialGroup()
                        .addComponent(GrößeLabel)
                        .addGap(34, 34, 34)
                        .addComponent(kCB)
                        .addGap(2, 2, 2)
                        .addComponent(mCB)
                        .addGap(2, 2, 2)
                        .addComponent(gCB))
                    .addComponent(SuchenmitteButton)
                    .addGroup(suche_Fach_lagerplatzLayout.createSequentialGroup()
                        .addGroup(suche_Fach_lagerplatzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, suche_Fach_lagerplatzLayout.createSequentialGroup()
                                .addComponent(ZeileLabel)
                                .addGap(38, 38, 38)
                                .addComponent(ZeileTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(zeile_label))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, suche_Fach_lagerplatzLayout.createSequentialGroup()
                                .addComponent(RegalnrLabel)
                                .addGap(18, 18, 18)
                                .addComponent(H1CB)
                                .addGap(2, 2, 2)
                                .addComponent(H2CB)
                                .addGap(2, 2, 2)
                                .addComponent(H3CB)
                                .addGap(2, 2, 2)
                                .addComponent(H4CB)))
                        .addGap(2, 2, 2)
                        .addComponent(H5CB)))
                .addGap(322, 322, 322))
            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        suche_Fach_lagerplatzLayout.setVerticalGroup(
            suche_Fach_lagerplatzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(suche_Fach_lagerplatzLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(suche_Fach_lagerplatzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(suche_Fach_lagerplatzLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(LagerfachbestandLabel))
                    .addComponent(LagerfachbestandTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(suche_Fach_lagerplatzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(suche_Fach_lagerplatzLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(LagerortLabel))
                    .addComponent(FCB)
                    .addComponent(HCB))
                .addGap(8, 8, 8)
                .addGroup(suche_Fach_lagerplatzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(suche_Fach_lagerplatzLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(RegalnrLabel))
                    .addComponent(H1CB)
                    .addComponent(H2CB)
                    .addComponent(H3CB)
                    .addComponent(H4CB)
                    .addComponent(H5CB))
                .addGap(18, 18, 18)
                .addGroup(suche_Fach_lagerplatzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(suche_Fach_lagerplatzLayout.createSequentialGroup()
                        .addGroup(suche_Fach_lagerplatzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(suche_Fach_lagerplatzLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(ZeileLabel))
                            .addComponent(ZeileTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(suche_Fach_lagerplatzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(suche_Fach_lagerplatzLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(SpalteLabel))
                            .addGroup(suche_Fach_lagerplatzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(SpalteTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(spalte_label)))
                        .addGap(18, 18, 18)
                        .addGroup(suche_Fach_lagerplatzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(suche_Fach_lagerplatzLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(BelegtLabel))
                            .addComponent(jaCB)
                            .addComponent(neinCB))
                        .addGap(18, 18, 18)
                        .addGroup(suche_Fach_lagerplatzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(suche_Fach_lagerplatzLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(GrößeLabel))
                            .addComponent(kCB)
                            .addComponent(mCB)
                            .addComponent(gCB))
                        .addGap(18, 18, 18)
                        .addComponent(SuchenmitteButton))
                    .addComponent(zeile_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Fach / Lagerplatz suchen", suche_Fach_lagerplatz);

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable5);

        LagerbestandTextfield.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        MinTextfield.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        TeileIDLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TeileIDLabel.setText("Teile ID:");

        SuchenrechtsButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        SuchenrechtsButton.setText("Suchen");

        FachnrLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        FachnrLabel.setText("Fachnummer:");

        HaltbarkeitsLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        HaltbarkeitsLabel.setText("Haltbarkeitsdatum:");

        MaxMengeLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        MaxMengeLabel.setText("Max. Menge im Fach:");

        TeileIDrechtsTextfield.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        FachnrTextfield.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        DatumTextfield.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        MinMengeLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        MinMengeLabel.setText("Mind. Menge im Fach:");

        MaxTextfield.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        LagerbestandLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LagerbestandLabel.setText("Lagerbestand:");

        javax.swing.GroupLayout suche_InhaltLayout = new javax.swing.GroupLayout(suche_Inhalt);
        suche_Inhalt.setLayout(suche_InhaltLayout);
        suche_InhaltLayout.setHorizontalGroup(
            suche_InhaltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE)
            .addGroup(suche_InhaltLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(suche_InhaltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SuchenrechtsButton)
                    .addGroup(suche_InhaltLayout.createSequentialGroup()
                        .addComponent(LagerbestandLabel)
                        .addGap(83, 83, 83)
                        .addComponent(LagerbestandTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(suche_InhaltLayout.createSequentialGroup()
                        .addComponent(MinMengeLabel)
                        .addGap(44, 44, 44)
                        .addComponent(MinTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(suche_InhaltLayout.createSequentialGroup()
                        .addComponent(MaxMengeLabel)
                        .addGap(49, 49, 49)
                        .addComponent(MaxTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(suche_InhaltLayout.createSequentialGroup()
                        .addComponent(HaltbarkeitsLabel)
                        .addGap(59, 59, 59)
                        .addComponent(DatumTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(suche_InhaltLayout.createSequentialGroup()
                        .addComponent(FachnrLabel)
                        .addGap(86, 86, 86)
                        .addComponent(FachnrTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(suche_InhaltLayout.createSequentialGroup()
                        .addComponent(TeileIDLabel)
                        .addGap(118, 118, 118)
                        .addComponent(TeileIDrechtsTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        suche_InhaltLayout.setVerticalGroup(
            suche_InhaltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, suche_InhaltLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(suche_InhaltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(suche_InhaltLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(LagerbestandLabel))
                    .addComponent(LagerbestandTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(suche_InhaltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(suche_InhaltLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(MinMengeLabel))
                    .addComponent(MinTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(suche_InhaltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(suche_InhaltLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(MaxMengeLabel))
                    .addComponent(MaxTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(suche_InhaltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(suche_InhaltLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(HaltbarkeitsLabel))
                    .addComponent(DatumTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(suche_InhaltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(suche_InhaltLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(FachnrLabel))
                    .addComponent(FachnrTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(suche_InhaltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(suche_InhaltLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(TeileIDLabel))
                    .addComponent(TeileIDrechtsTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(SuchenrechtsButton)
                .addGap(69, 69, 69)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Menge / Teil im Fach suchen", suche_Inhalt);

        MAMTextfield.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        MAGTextfield.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        SuchenlinksButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        SuchenlinksButton.setText("Suchen");
        SuchenlinksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teile_suchen(evt);
            }
        });

        EuroLabel.setText("€");

        PreisLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        PreisLabel.setText("Preis:");

        IDTextfield.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        MAKLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        MAKLabel.setText("MAK:");

        TeileStammdatenLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        TeileStammdatenLabel.setText("Teile Stammdaten:");

        BezeichnungLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        BezeichnungLabel.setText("Bezeichnung:");

        ZNrTextfield.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        IDlinksLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        IDlinksLabel.setText("Teile ID:");

        MaterialTextfield.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        MaterialgruppeLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        MaterialgruppeLabel.setText("Materialgrupe:");

        BezTextfield.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        TeiletypLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TeiletypLabel.setText("Teiletyp:");

        BaugruppeLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        BaugruppeLabel.setText("Baugruppe:");

        AlleTeileAnzeigenButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        AlleTeileAnzeigenButton.setText("alle Teile anzeigen");
        AlleTeileAnzeigenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alle_teile_suchen(evt);
            }
        });

        MAKTextfield.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        ZeichnungsnrLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ZeichnungsnrLabel.setText("Zeichnungsnr.:");

        PreisTextfield.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        MAMLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        MAMLabel.setText("MAM:");

        BaugruppeTextfield.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        MAGLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        MAGLabel.setText("MAG:");

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        TeiletypComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Kaufteile", "Werkzeuge", "Vorrichtungen", "unfertige Baugruppen", "Vorratsteile" }));

        BemerkungLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        BemerkungLabel.setText("Bemerkung:");

        javax.swing.GroupLayout suche_TeilLayout = new javax.swing.GroupLayout(suche_Teil);
        suche_Teil.setLayout(suche_TeilLayout);
        suche_TeilLayout.setHorizontalGroup(
            suche_TeilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(suche_TeilLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
            .addGroup(suche_TeilLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(suche_TeilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TeileStammdatenLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(suche_TeilLayout.createSequentialGroup()
                        .addComponent(IDlinksLabel)
                        .addGap(55, 55, 55)
                        .addComponent(IDTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(suche_TeilLayout.createSequentialGroup()
                        .addComponent(ZeichnungsnrLabel)
                        .addGap(9, 9, 9)
                        .addComponent(ZNrTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(MAMLabel)
                        .addGap(10, 10, 10)
                        .addComponent(MAMTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(suche_TeilLayout.createSequentialGroup()
                        .addComponent(BaugruppeLabel)
                        .addGap(31, 31, 31)
                        .addComponent(BaugruppeTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(MAGLabel)
                        .addGap(11, 11, 11)
                        .addComponent(MAGTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(suche_TeilLayout.createSequentialGroup()
                        .addComponent(AlleTeileAnzeigenButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SuchenlinksButton))
                    .addGroup(suche_TeilLayout.createSequentialGroup()
                        .addComponent(MaterialgruppeLabel)
                        .addGap(13, 13, 13)
                        .addGroup(suche_TeilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TeiletypComboBox, 0, 1, Short.MAX_VALUE)
                            .addComponent(MaterialTextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                        .addGap(38, 38, 38)
                        .addComponent(MAKLabel)
                        .addGap(12, 12, 12)
                        .addComponent(MAKTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(suche_TeilLayout.createSequentialGroup()
                        .addGroup(suche_TeilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TeiletypLabel)
                            .addGroup(suche_TeilLayout.createSequentialGroup()
                                .addComponent(BezeichnungLabel)
                                .addGap(21, 21, 21)
                                .addComponent(BezTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(37, 37, 37)
                        .addGroup(suche_TeilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(suche_TeilLayout.createSequentialGroup()
                                .addComponent(BemerkungLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BemerkungLagerTextfield, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(suche_TeilLayout.createSequentialGroup()
                                .addComponent(PreisLabel)
                                .addGap(7, 7, 7)
                                .addComponent(PreisTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(EuroLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        suche_TeilLayout.setVerticalGroup(
            suche_TeilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(suche_TeilLayout.createSequentialGroup()
                .addGroup(suche_TeilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(suche_TeilLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(TeileStammdatenLabel)
                        .addGap(11, 11, 11)
                        .addGroup(suche_TeilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(suche_TeilLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(IDlinksLabel))
                            .addComponent(IDTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(suche_TeilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(suche_TeilLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(BezeichnungLabel))
                            .addComponent(BezTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, suche_TeilLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(suche_TeilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BemerkungLabel)
                            .addComponent(BemerkungLagerTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(suche_TeilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(suche_TeilLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(suche_TeilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TeiletypLabel)
                            .addComponent(TeiletypComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(suche_TeilLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(PreisLabel))
                    .addComponent(PreisTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(suche_TeilLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(EuroLabel)))
                .addGap(12, 12, 12)
                .addGroup(suche_TeilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MaterialTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MAKTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(suche_TeilLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(suche_TeilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MaterialgruppeLabel)
                            .addComponent(MAKLabel))))
                .addGap(13, 13, 13)
                .addGroup(suche_TeilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ZNrTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MAMTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(suche_TeilLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(suche_TeilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ZeichnungsnrLabel)
                            .addComponent(MAMLabel))))
                .addGap(13, 13, 13)
                .addGroup(suche_TeilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BaugruppeTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MAGTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(suche_TeilLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(suche_TeilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BaugruppeLabel)
                            .addComponent(MAGLabel))))
                .addGap(43, 43, 43)
                .addGroup(suche_TeilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AlleTeileAnzeigenButton)
                    .addComponent(SuchenlinksButton))
                .addGap(16, 16, 16)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Teil suchen", suche_Teil);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alle_teile_suchen(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alle_teile_suchen
        try {
            suchen_controller.alle_teile_ausgeben();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Teil_Suchen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_alle_teile_suchen

    private void teile_suchen(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teile_suchen

        String[][] spaltenwerte = new String[10][];
        String[] id = {"id", IDTextfield.getText()};
        String teilstring = (String)TeiletypComboBox.getSelectedItem();
        if (" ".equals(teilstring)) {
            teilstring = "";
        }
        String[] teiletyp = {"typ", teilstring};
        String[] zeichnungsnummer = {"zeichnungsnummer", ZNrTextfield.getText()};
        String[] materialgruppe = {"materialgruppe", MaterialTextfield.getText()};

        String[] preis = {"preis", PreisTextfield.getText()};
        String[] bezeichnung = {"bezeichnung", BezTextfield.getText()};
        String[] baugruppe = {"baugruppe", BaugruppeTextfield.getText()};
        String[] bemerkung = {"bemerkung", BemerkungLagerTextfield.getText()};
        String[] maxanzahlklein = {"max_anz_klein", MAKTextfield.getText()};
        String[] maxanzahlmittel = {"max_anz_mittel", MAMTextfield.getText()};
        String[] maxanzahlgross = {"max_anz_gross", MAGTextfield.getText()};

        spaltenwerte[0] = id;
        spaltenwerte[1] = teiletyp;
        spaltenwerte[2] = zeichnungsnummer;
        spaltenwerte[3] = materialgruppe;
        spaltenwerte[4] = preis;
        spaltenwerte[5] = bezeichnung;
        spaltenwerte[6] = baugruppe;
        spaltenwerte[7] = maxanzahlklein;
        spaltenwerte[8] = maxanzahlmittel;
        spaltenwerte[9] = maxanzahlgross;
        
        String query = Select_Allgemein.create_select_suchen("Teilestammdaten", spaltenwerte);
        System.out.println(query);
        Datenbankverbindung db = new Datenbankverbindung();
        try {
            ArrayList<Teil_Stammdaten> teile_stammdaten_array = db.connect_Teil_Stammdaten(query);
            for (Iterator<Teil_Stammdaten> it = teile_stammdaten_array.iterator(); it.hasNext();) {
                Teil_Stammdaten teil = it.next();
                System.out.println(
                        teil.get_Id() + "\n" +
                        teil.get_Teiletyp() + "\n" +
                        teil.get_Zeichnungsnummer() + "\n" + 
                        teil.get_Baugruppe() + "\n" +
                        teil.get_Bemerkung() + "\n" +
                        teil.get_Preis() + "\n" +
                        teil.get_Materialgruppe() + "\n"
                        ); 
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Teil_Suchen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(Teil_Suchen.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        

    }//GEN-LAST:event_teile_suchen
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teil_Suchen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teil_Suchen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teil_Suchen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teil_Suchen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Teil_Suchen().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AlleTeileAnzeigenButton;
    private javax.swing.JLabel BaugruppeLabel;
    private javax.swing.JTextField BaugruppeTextfield;
    private javax.swing.JLabel BelegtLabel;
    private javax.swing.JLabel BemerkungLabel;
    private view.LagerTextfield BemerkungLagerTextfield;
    private javax.swing.JTextField BezTextfield;
    private javax.swing.JLabel BezeichnungLabel;
    private javax.swing.JTextField DatumTextfield;
    private javax.swing.JLabel EuroLabel;
    private javax.swing.JCheckBox FCB;
    private javax.swing.JLabel FachnrLabel;
    private javax.swing.JTextField FachnrTextfield;
    private javax.swing.JLabel GrößeLabel;
    private javax.swing.JCheckBox H1CB;
    private javax.swing.JCheckBox H2CB;
    private javax.swing.JCheckBox H3CB;
    private javax.swing.JCheckBox H4CB;
    private javax.swing.JCheckBox H5CB;
    private javax.swing.JCheckBox HCB;
    private javax.swing.JLabel HaltbarkeitsLabel;
    private javax.swing.JTextField IDTextfield;
    private javax.swing.JLabel IDlinksLabel;
    private javax.swing.JLabel LagerbestandLabel;
    private javax.swing.JTextField LagerbestandTextfield;
    private javax.swing.JLabel LagerfachbestandLabel;
    private javax.swing.JTextField LagerfachbestandTextfield;
    private javax.swing.JLabel LagerortLabel;
    private javax.swing.JLabel MAGLabel;
    private javax.swing.JTextField MAGTextfield;
    private javax.swing.JLabel MAKLabel;
    private javax.swing.JTextField MAKTextfield;
    private javax.swing.JLabel MAMLabel;
    private javax.swing.JTextField MAMTextfield;
    private javax.swing.JTextField MaterialTextfield;
    private javax.swing.JLabel MaterialgruppeLabel;
    private javax.swing.JLabel MaxMengeLabel;
    private javax.swing.JTextField MaxTextfield;
    private javax.swing.JLabel MinMengeLabel;
    private javax.swing.JTextField MinTextfield;
    private javax.swing.JLabel PreisLabel;
    private javax.swing.JTextField PreisTextfield;
    private javax.swing.JLabel RegalnrLabel;
    private javax.swing.JLabel SpalteLabel;
    private javax.swing.JTextField SpalteTextfield;
    private javax.swing.JButton SuchenlinksButton;
    private javax.swing.JButton SuchenmitteButton;
    private javax.swing.JButton SuchenrechtsButton;
    private javax.swing.JLabel TeileIDLabel;
    private javax.swing.JTextField TeileIDrechtsTextfield;
    private javax.swing.JLabel TeileStammdatenLabel;
    private javax.swing.JComboBox TeiletypComboBox;
    private javax.swing.JLabel TeiletypLabel;
    private javax.swing.JTextField ZNrTextfield;
    private javax.swing.JLabel ZeichnungsnrLabel;
    private javax.swing.JLabel ZeileLabel;
    private javax.swing.JTextField ZeileTextfield;
    private javax.swing.JCheckBox gCB;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JCheckBox jaCB;
    private javax.swing.JCheckBox kCB;
    private javax.swing.JCheckBox mCB;
    private javax.swing.JCheckBox neinCB;
    private javax.swing.JLabel spalte_label;
    private javax.swing.JPanel suche_Fach_lagerplatz;
    private javax.swing.JPanel suche_Inhalt;
    private javax.swing.JPanel suche_Teil;
    private javax.swing.JLabel zeile_label;
    // End of variables declaration//GEN-END:variables
}
