/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */
package view;

/**
 *
 * @author felix
 */
public class Teilestamm_verwalten extends javax.swing.JFrame {

    /**
     * Creates new form Teilestamm_erweitern
     */
    public Teilestamm_verwalten() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_eingabeaufforderung = new javax.swing.JLabel();
        label_id = new javax.swing.JLabel();
        textfeld_id = new javax.swing.JTextField();
        label_bezeichnung = new javax.swing.JLabel();
        label_teiltyp = new javax.swing.JLabel();
        label_materialgruppe = new javax.swing.JLabel();
        label_zeichnungsnummer = new javax.swing.JLabel();
        label_baugruppe = new javax.swing.JLabel();
        textfeld_bezeichnung = new javax.swing.JTextField();
        textfeld_materialgruppe = new javax.swing.JTextField();
        textfeld_zeichnungsnummer = new javax.swing.JTextField();
        textfeld_baugruppe = new javax.swing.JTextField();
        label_preis = new javax.swing.JLabel();
        label_max_anz_klein = new javax.swing.JLabel();
        label_max_anz_mittel = new javax.swing.JLabel();
        label_max_anz_gross = new javax.swing.JLabel();
        label_bemerkung = new javax.swing.JLabel();
        textfeld_preis = new javax.swing.JTextField();
        textfeld_max_anz_klein = new javax.swing.JTextField();
        textfeld_max_anz_mittel = new javax.swing.JTextField();
        textfeld_max_anz_gross = new javax.swing.JTextField();
        textfeld_bemerkung = new javax.swing.JTextField();
        label_waehrung = new javax.swing.JLabel();
        button_loeschen = new javax.swing.JButton();
        textfeld_teiltyp = new javax.swing.JTextField();
        button_suchen = new javax.swing.JButton();
        anzeigen_button = new javax.swing.JButton();
        aendern_button = new javax.swing.JButton();
        menubar_teilestamm_verwalten = new javax.swing.JMenuBar();
        menu_datei = new javax.swing.JMenu();
        menu_bearbeiten = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Arial", 0, 12));

        label_eingabeaufforderung.setFont(new java.awt.Font("Arial", 1, 12));
        label_eingabeaufforderung.setText("Bitte geben Sie die ID des Teiles ein:");

        label_id.setFont(new java.awt.Font("Arial", 0, 12));
        label_id.setText("ID:");

        textfeld_id.setEditable(false);
        textfeld_id.setFont(new java.awt.Font("Arial", 0, 12));
        textfeld_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfeld_idActionPerformed(evt);
            }
        });

        label_bezeichnung.setFont(new java.awt.Font("Arial", 0, 12));
        label_bezeichnung.setText("Bezeichnnung:");

        label_teiltyp.setFont(new java.awt.Font("Arial", 0, 12));
        label_teiltyp.setText("Teiltyp:");

        label_materialgruppe.setFont(new java.awt.Font("Arial", 0, 12));
        label_materialgruppe.setText("Materialgruppe:");

        label_zeichnungsnummer.setFont(new java.awt.Font("Arial", 0, 12));
        label_zeichnungsnummer.setText("Zeichnungsnr.:");

        label_baugruppe.setFont(new java.awt.Font("Arial", 0, 12));
        label_baugruppe.setText("Baugruppe:");

        textfeld_bezeichnung.setEditable(false);
        textfeld_bezeichnung.setFont(new java.awt.Font("Arial", 0, 12));

        textfeld_materialgruppe.setEditable(false);
        textfeld_materialgruppe.setFont(new java.awt.Font("Arial", 0, 12));

        textfeld_zeichnungsnummer.setEditable(false);
        textfeld_zeichnungsnummer.setFont(new java.awt.Font("Arial", 0, 12));

        textfeld_baugruppe.setEditable(false);
        textfeld_baugruppe.setFont(new java.awt.Font("Arial", 0, 12));

        label_preis.setFont(new java.awt.Font("Arial", 0, 12));
        label_preis.setText("Preis:");

        label_max_anz_klein.setFont(new java.awt.Font("Arial", 0, 12));
        label_max_anz_klein.setText("Max. Anz. Klein:");

        label_max_anz_mittel.setFont(new java.awt.Font("Arial", 0, 12));
        label_max_anz_mittel.setText("Max. Anz. Mittel:");

        label_max_anz_gross.setFont(new java.awt.Font("Arial", 0, 12));
        label_max_anz_gross.setText("Max. Anz. Groß:");

        label_bemerkung.setFont(new java.awt.Font("Arial", 0, 12));
        label_bemerkung.setText("Bemerkung:");

        textfeld_preis.setEditable(false);
        textfeld_preis.setFont(new java.awt.Font("Arial", 0, 12));

        textfeld_max_anz_klein.setEditable(false);
        textfeld_max_anz_klein.setFont(new java.awt.Font("Arial", 0, 12));

        textfeld_max_anz_mittel.setEditable(false);
        textfeld_max_anz_mittel.setFont(new java.awt.Font("Arial", 0, 12));

        textfeld_max_anz_gross.setEditable(false);
        textfeld_max_anz_gross.setFont(new java.awt.Font("Arial", 0, 12));

        textfeld_bemerkung.setEditable(false);
        textfeld_bemerkung.setFont(new java.awt.Font("Arial", 0, 12));

        label_waehrung.setFont(new java.awt.Font("Arial", 0, 12));
        label_waehrung.setText("€");

        button_loeschen.setFont(new java.awt.Font("Arial", 1, 12));
        button_loeschen.setText("Löschen");

        textfeld_teiltyp.setEditable(false);

        button_suchen.setFont(new java.awt.Font("Arial", 1, 12));
        button_suchen.setText("Suchen");

        anzeigen_button.setFont(new java.awt.Font("Arial", 1, 12));
        anzeigen_button.setText("Anzeigen");

        aendern_button.setFont(new java.awt.Font("Arial", 1, 12));
        aendern_button.setText("Ändern");

        menu_datei.setText("File");
        menubar_teilestamm_verwalten.add(menu_datei);

        menu_bearbeiten.setText("Edit");
        menubar_teilestamm_verwalten.add(menu_bearbeiten);

        setJMenuBar(menubar_teilestamm_verwalten);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(aendern_button))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(label_id)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textfeld_id, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(anzeigen_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_suchen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_loeschen))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_eingabeaufforderung, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                        .addGap(89, 89, 89))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_bezeichnung)
                            .addComponent(label_teiltyp)
                            .addComponent(label_materialgruppe)
                            .addComponent(label_zeichnungsnummer)
                            .addComponent(label_baugruppe))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textfeld_teiltyp)
                            .addComponent(textfeld_materialgruppe)
                            .addComponent(textfeld_zeichnungsnummer)
                            .addComponent(textfeld_baugruppe)
                            .addComponent(textfeld_bezeichnung))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_max_anz_mittel)
                            .addComponent(label_max_anz_gross)
                            .addComponent(label_preis)
                            .addComponent(label_max_anz_klein)
                            .addComponent(label_bemerkung))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textfeld_preis)
                            .addComponent(textfeld_max_anz_mittel)
                            .addComponent(textfeld_max_anz_gross)
                            .addComponent(textfeld_bemerkung, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textfeld_max_anz_klein))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_waehrung)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_eingabeaufforderung)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_id)
                    .addComponent(textfeld_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anzeigen_button)
                    .addComponent(button_suchen)
                    .addComponent(button_loeschen))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_bezeichnung)
                    .addComponent(textfeld_bezeichnung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_preis)
                    .addComponent(textfeld_preis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_waehrung))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_teiltyp)
                    .addComponent(label_max_anz_klein)
                    .addComponent(textfeld_max_anz_klein, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfeld_teiltyp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_materialgruppe)
                    .addComponent(textfeld_materialgruppe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_max_anz_mittel)
                    .addComponent(textfeld_max_anz_mittel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_zeichnungsnummer)
                    .addComponent(textfeld_zeichnungsnummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_max_anz_gross)
                    .addComponent(textfeld_max_anz_gross, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_baugruppe)
                    .addComponent(textfeld_baugruppe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_bemerkung)
                    .addComponent(textfeld_bemerkung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(aendern_button)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textfeld_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfeld_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfeld_idActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teilestamm_verwalten.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teilestamm_verwalten.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teilestamm_verwalten.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teilestamm_verwalten.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Teilestamm_verwalten().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aendern_button;
    private javax.swing.JButton anzeigen_button;
    private javax.swing.JButton button_loeschen;
    private javax.swing.JButton button_suchen;
    private javax.swing.JLabel label_baugruppe;
    private javax.swing.JLabel label_bemerkung;
    private javax.swing.JLabel label_bezeichnung;
    private javax.swing.JLabel label_eingabeaufforderung;
    private javax.swing.JLabel label_id;
    private javax.swing.JLabel label_materialgruppe;
    private javax.swing.JLabel label_max_anz_gross;
    private javax.swing.JLabel label_max_anz_klein;
    private javax.swing.JLabel label_max_anz_mittel;
    private javax.swing.JLabel label_preis;
    private javax.swing.JLabel label_teiltyp;
    private javax.swing.JLabel label_waehrung;
    private javax.swing.JLabel label_zeichnungsnummer;
    private javax.swing.JMenu menu_bearbeiten;
    private javax.swing.JMenu menu_datei;
    private javax.swing.JMenuBar menubar_teilestamm_verwalten;
    private javax.swing.JTextField textfeld_baugruppe;
    private javax.swing.JTextField textfeld_bemerkung;
    private javax.swing.JTextField textfeld_bezeichnung;
    private javax.swing.JTextField textfeld_id;
    private javax.swing.JTextField textfeld_materialgruppe;
    private javax.swing.JTextField textfeld_max_anz_gross;
    private javax.swing.JTextField textfeld_max_anz_klein;
    private javax.swing.JTextField textfeld_max_anz_mittel;
    private javax.swing.JTextField textfeld_preis;
    private javax.swing.JTextField textfeld_teiltyp;
    private javax.swing.JTextField textfeld_zeichnungsnummer;
    // End of variables declaration//GEN-END:variables
}
