/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */
package view;

/**
 *
 * @author felix
 */
public class Teilestamm_erweitern extends javax.swing.JFrame {

    /**
     * Creates new form Teilestamm_erweitern
     */
    public Teilestamm_erweitern() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_eingabeaufforderung = new javax.swing.JLabel();
        label_id = new javax.swing.JLabel();
        textfeld_id = new javax.swing.JTextField();
        label_bezeichnung = new javax.swing.JLabel();
        label_teiltyp = new javax.swing.JLabel();
        label_materialgruppe = new javax.swing.JLabel();
        label_zeichnungsnummer = new javax.swing.JLabel();
        label_baugruppe = new javax.swing.JLabel();
        textfeld_bezeichnung = new javax.swing.JTextField();
        combobox_teiltyp = new javax.swing.JComboBox();
        textfeld_materialgruppe = new javax.swing.JTextField();
        textfeld_zeichnungsnummer = new javax.swing.JTextField();
        textfeld_baugruppe = new javax.swing.JTextField();
        label_preis = new javax.swing.JLabel();
        label_max_anz_klein = new javax.swing.JLabel();
        label_max_anz_mittel = new javax.swing.JLabel();
        label_max_anz_gross = new javax.swing.JLabel();
        label_bemerkung = new javax.swing.JLabel();
        textfeld_preis = new javax.swing.JTextField();
        textfeld_max_anz_klein = new javax.swing.JTextField();
        textfeld_max_anz_mittel = new javax.swing.JTextField();
        textfeld_max_anz_gross = new javax.swing.JTextField();
        textfeld_bemerkung = new javax.swing.JTextField();
        label_waehrung = new javax.swing.JLabel();
        button_anlegen = new javax.swing.JButton();
        menubar_teilestamm_erweitern = new javax.swing.JMenuBar();
        menu_datei = new javax.swing.JMenu();
        menu_bearbeiten = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Arial", 0, 12));
        getContentPane().setLayout(null);

        label_eingabeaufforderung.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        label_eingabeaufforderung.setText("Bitte geben Sie die Stammdaten für ein neues Teil ein:");
        getContentPane().add(label_eingabeaufforderung);
        label_eingabeaufforderung.setBounds(10, 11, 515, 15);

        label_id.setFont(new java.awt.Font("Arial", 0, 12));
        label_id.setText("ID:");
        getContentPane().add(label_id);
        label_id.setBounds(10, 47, 15, 15);

        textfeld_id.setFont(new java.awt.Font("Arial", 0, 12));
        textfeld_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfeld_idActionPerformed(evt);
            }
        });
        getContentPane().add(textfeld_id);
        textfeld_id.setBounds(29, 44, 59, 21);

        label_bezeichnung.setFont(new java.awt.Font("Arial", 0, 12));
        label_bezeichnung.setText("Bezeichnnung:");
        getContentPane().add(label_bezeichnung);
        label_bezeichnung.setBounds(10, 86, 81, 15);

        label_teiltyp.setFont(new java.awt.Font("Arial", 0, 12));
        label_teiltyp.setText("Teiltyp:");
        getContentPane().add(label_teiltyp);
        label_teiltyp.setBounds(10, 118, 38, 15);

        label_materialgruppe.setFont(new java.awt.Font("Arial", 0, 12));
        label_materialgruppe.setText("Materialgruppe:");
        getContentPane().add(label_materialgruppe);
        label_materialgruppe.setBounds(10, 150, 85, 15);

        label_zeichnungsnummer.setFont(new java.awt.Font("Arial", 0, 12));
        label_zeichnungsnummer.setText("Zeichnungsnr.:");
        getContentPane().add(label_zeichnungsnummer);
        label_zeichnungsnummer.setBounds(10, 182, 82, 15);

        label_baugruppe.setFont(new java.awt.Font("Arial", 0, 12));
        label_baugruppe.setText("Baugruppe:");
        getContentPane().add(label_baugruppe);
        label_baugruppe.setBounds(10, 214, 64, 15);

        textfeld_bezeichnung.setFont(new java.awt.Font("Arial", 0, 12));
        getContentPane().add(textfeld_bezeichnung);
        textfeld_bezeichnung.setBounds(99, 83, 150, 21);

        combobox_teiltyp.setFont(new java.awt.Font("Arial", 0, 12));
        combobox_teiltyp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(combobox_teiltyp);
        combobox_teiltyp.setBounds(99, 115, 150, 21);

        textfeld_materialgruppe.setFont(new java.awt.Font("Arial", 0, 12));
        getContentPane().add(textfeld_materialgruppe);
        textfeld_materialgruppe.setBounds(99, 147, 150, 21);

        textfeld_zeichnungsnummer.setFont(new java.awt.Font("Arial", 0, 12));
        getContentPane().add(textfeld_zeichnungsnummer);
        textfeld_zeichnungsnummer.setBounds(99, 179, 150, 21);

        textfeld_baugruppe.setFont(new java.awt.Font("Arial", 0, 12));
        getContentPane().add(textfeld_baugruppe);
        textfeld_baugruppe.setBounds(99, 211, 150, 21);

        label_preis.setFont(new java.awt.Font("Arial", 0, 12));
        label_preis.setText("Preis:");
        getContentPane().add(label_preis);
        label_preis.setBounds(267, 86, 32, 15);

        label_max_anz_klein.setFont(new java.awt.Font("Arial", 0, 12));
        label_max_anz_klein.setText("Max. Anz. Klein:");
        getContentPane().add(label_max_anz_klein);
        label_max_anz_klein.setBounds(267, 118, 83, 15);

        label_max_anz_mittel.setFont(new java.awt.Font("Arial", 0, 12));
        label_max_anz_mittel.setText("Max. Anz. Mittel:");
        getContentPane().add(label_max_anz_mittel);
        label_max_anz_mittel.setBounds(267, 150, 83, 15);

        label_max_anz_gross.setFont(new java.awt.Font("Arial", 0, 12));
        label_max_anz_gross.setText("Max. Anz. Groß:");
        getContentPane().add(label_max_anz_gross);
        label_max_anz_gross.setBounds(267, 182, 83, 15);

        label_bemerkung.setFont(new java.awt.Font("Arial", 0, 12));
        label_bemerkung.setText("Bemerkung:");
        getContentPane().add(label_bemerkung);
        label_bemerkung.setBounds(267, 214, 67, 15);

        textfeld_preis.setFont(new java.awt.Font("Arial", 0, 12));
        getContentPane().add(textfeld_preis);
        textfeld_preis.setBounds(360, 83, 154, 21);

        textfeld_max_anz_klein.setFont(new java.awt.Font("Arial", 0, 12));
        getContentPane().add(textfeld_max_anz_klein);
        textfeld_max_anz_klein.setBounds(360, 115, 154, 21);

        textfeld_max_anz_mittel.setFont(new java.awt.Font("Arial", 0, 12));
        getContentPane().add(textfeld_max_anz_mittel);
        textfeld_max_anz_mittel.setBounds(360, 147, 154, 21);

        textfeld_max_anz_gross.setFont(new java.awt.Font("Arial", 0, 12));
        getContentPane().add(textfeld_max_anz_gross);
        textfeld_max_anz_gross.setBounds(360, 179, 154, 21);

        textfeld_bemerkung.setFont(new java.awt.Font("Arial", 0, 12));
        getContentPane().add(textfeld_bemerkung);
        textfeld_bemerkung.setBounds(360, 211, 154, 21);

        label_waehrung.setFont(new java.awt.Font("Arial", 0, 12));
        label_waehrung.setText("€");
        getContentPane().add(label_waehrung);
        label_waehrung.setBounds(518, 86, 7, 15);

        button_anlegen.setFont(new java.awt.Font("Arial", 0, 12));
        button_anlegen.setText("Anlegen");
        getContentPane().add(button_anlegen);
        button_anlegen.setBounds(437, 250, 77, 23);

        menu_datei.setText("File");
        menubar_teilestamm_erweitern.add(menu_datei);

        menu_bearbeiten.setText("Edit");
        menubar_teilestamm_erweitern.add(menu_bearbeiten);

        setJMenuBar(menubar_teilestamm_erweitern);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textfeld_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfeld_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfeld_idActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teilestamm_erweitern.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teilestamm_erweitern.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teilestamm_erweitern.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teilestamm_erweitern.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Teilestamm_erweitern().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_anlegen;
    private javax.swing.JComboBox combobox_teiltyp;
    private javax.swing.JLabel label_baugruppe;
    private javax.swing.JLabel label_bemerkung;
    private javax.swing.JLabel label_bezeichnung;
    private javax.swing.JLabel label_eingabeaufforderung;
    private javax.swing.JLabel label_id;
    private javax.swing.JLabel label_materialgruppe;
    private javax.swing.JLabel label_max_anz_gross;
    private javax.swing.JLabel label_max_anz_klein;
    private javax.swing.JLabel label_max_anz_mittel;
    private javax.swing.JLabel label_preis;
    private javax.swing.JLabel label_teiltyp;
    private javax.swing.JLabel label_waehrung;
    private javax.swing.JLabel label_zeichnungsnummer;
    private javax.swing.JMenu menu_bearbeiten;
    private javax.swing.JMenu menu_datei;
    private javax.swing.JMenuBar menubar_teilestamm_erweitern;
    private javax.swing.JTextField textfeld_baugruppe;
    private javax.swing.JTextField textfeld_bemerkung;
    private javax.swing.JTextField textfeld_bezeichnung;
    private javax.swing.JTextField textfeld_id;
    private javax.swing.JTextField textfeld_materialgruppe;
    private javax.swing.JTextField textfeld_max_anz_gross;
    private javax.swing.JTextField textfeld_max_anz_klein;
    private javax.swing.JTextField textfeld_max_anz_mittel;
    private javax.swing.JTextField textfeld_preis;
    private javax.swing.JTextField textfeld_zeichnungsnummer;
    // End of variables declaration//GEN-END:variables
}
