/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */
package view;

/**
 *
 * @author Wayne
 */
public class Teile_Splitten extends javax.swing.JFrame {

    /**
     * Creates new form Teile_Splitten
     */
    public Teile_Splitten() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        suchen_button = new javax.swing.JButton();
        label_eingabe_aufforderung_fachnummer = new javax.swing.JLabel();
        label_ausgangsfachnummer = new javax.swing.JLabel();
        ausgangsfachnummer_textfeld = new javax.swing.JTextField();
        bestaetigen_button = new javax.swing.JButton();
        label_teil_eingelagert = new javax.swing.JLabel();
        label_anzeige_teile_id = new javax.swing.JLabel();
        label_bezeichnung = new javax.swing.JLabel();
        label_anzeige_bezeichnung = new javax.swing.JLabel();
        label_eingabeaufforderung_splitten = new javax.swing.JLabel();
        label_splitten_nummer1 = new javax.swing.JLabel();
        label_fachnummer1 = new javax.swing.JLabel();
        fachnummer_textfeld1 = new javax.swing.JTextField();
        label_menge1 = new javax.swing.JLabel();
        menge_textfeld1 = new javax.swing.JTextField();
        kapazitaet_pruefen_button1 = new javax.swing.JButton();
        label_splitten_nummer2 = new javax.swing.JLabel();
        label_fachnummer2 = new javax.swing.JLabel();
        fachnummer_textfeld2 = new javax.swing.JTextField();
        label_menge2 = new javax.swing.JLabel();
        menge_textfeld2 = new javax.swing.JTextField();
        kapazitaet_pruefen_button2 = new javax.swing.JButton();
        fachnummer_textfeld3 = new javax.swing.JTextField();
        label_splitten_nummer3 = new javax.swing.JLabel();
        menge_textfeld3 = new javax.swing.JTextField();
        label_menge3 = new javax.swing.JLabel();
        kapazitaet_pruefen_button3 = new javax.swing.JButton();
        label_fachnummer3 = new javax.swing.JLabel();
        menge_textfeld4 = new javax.swing.JTextField();
        label_fachnummer4 = new javax.swing.JLabel();
        kapazitaet_pruefen_button4 = new javax.swing.JButton();
        label_splitten_nummer4 = new javax.swing.JLabel();
        label_menge4 = new javax.swing.JLabel();
        fachnummer_textfeld4 = new javax.swing.JTextField();
        label_fachnummer5 = new javax.swing.JLabel();
        kapazitaet_pruefen_button5 = new javax.swing.JButton();
        fachnummer_textfeld5 = new javax.swing.JTextField();
        menge_textfeld5 = new javax.swing.JTextField();
        label_splitten_nummer5 = new javax.swing.JLabel();
        label_menge5 = new javax.swing.JLabel();
        label_fachnummer6 = new javax.swing.JLabel();
        menge_textfeld6 = new javax.swing.JTextField();
        label_menge6 = new javax.swing.JLabel();
        label_splitten_nummer6 = new javax.swing.JLabel();
        fachnummer_textfeld6 = new javax.swing.JTextField();
        kapazitaet_pruefen_button6 = new javax.swing.JButton();
        menge_textfeld7 = new javax.swing.JTextField();
        label_splitten_nummer7 = new javax.swing.JLabel();
        fachnummer_textfeld7 = new javax.swing.JTextField();
        kapazitaet_pruefen_button7 = new javax.swing.JButton();
        label_menge7 = new javax.swing.JLabel();
        label_fachnummer7 = new javax.swing.JLabel();
        label_splitten_nummer8 = new javax.swing.JLabel();
        label_fachnummer8 = new javax.swing.JLabel();
        fachnummer_textfeld8 = new javax.swing.JTextField();
        menge_textfeld8 = new javax.swing.JTextField();
        label_menge8 = new javax.swing.JLabel();
        kapazitaet_pruefen_button8 = new javax.swing.JButton();
        label_fachnummer9 = new javax.swing.JLabel();
        fachnummer_textfeld9 = new javax.swing.JTextField();
        kapazitaet_pruefen_button9 = new javax.swing.JButton();
        label_splitten_nummer9 = new javax.swing.JLabel();
        menge_textfeld9 = new javax.swing.JTextField();
        label_menge9 = new javax.swing.JLabel();
        menge_textfeld10 = new javax.swing.JTextField();
        fachnummer_textfeld10 = new javax.swing.JTextField();
        kapazitaet_pruefen_button10 = new javax.swing.JButton();
        label_menge10 = new javax.swing.JLabel();
        label_splitten_nummer10 = new javax.swing.JLabel();
        label_fachnummer10 = new javax.swing.JLabel();
        splitten_button = new javax.swing.JButton();
        label_mindestgroesse = new javax.swing.JLabel();
        label_anzeige_mindestgroesse = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        datei_menu = new javax.swing.JMenu();
        bearbeiten_menu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Teil Splitten");
        setMinimumSize(new java.awt.Dimension(750, 600));
        getContentPane().setLayout(null);

        suchen_button.setFont(new java.awt.Font("Arial", 0, 12));
        suchen_button.setText("Suchen");
        getContentPane().add(suchen_button);
        suchen_button.setBounds(570, 20, 90, 23);

        label_eingabe_aufforderung_fachnummer.setFont(new java.awt.Font("Arial", 0, 12));
        label_eingabe_aufforderung_fachnummer.setText("Bitte geben Sie die Fachnummer ein aus der gesplittet werden soll:");
        getContentPane().add(label_eingabe_aufforderung_fachnummer);
        label_eingabe_aufforderung_fachnummer.setBounds(30, 30, 370, 20);

        label_ausgangsfachnummer.setFont(new java.awt.Font("Arial", 0, 12));
        label_ausgangsfachnummer.setText("Fachnummer:");
        getContentPane().add(label_ausgangsfachnummer);
        label_ausgangsfachnummer.setBounds(30, 60, 80, 20);

        ausgangsfachnummer_textfeld.setFont(new java.awt.Font("Arial", 0, 12));
        ausgangsfachnummer_textfeld.setToolTipText("");
        getContentPane().add(ausgangsfachnummer_textfeld);
        ausgangsfachnummer_textfeld.setBounds(110, 60, 100, 21);

        bestaetigen_button.setFont(new java.awt.Font("Arial", 0, 12));
        bestaetigen_button.setText("Bestätigen");
        getContentPane().add(bestaetigen_button);
        bestaetigen_button.setBounds(220, 60, 100, 23);

        label_teil_eingelagert.setFont(new java.awt.Font("Arial", 0, 12));
        label_teil_eingelagert.setText("Eingelagertes Teil:");
        getContentPane().add(label_teil_eingelagert);
        label_teil_eingelagert.setBounds(30, 100, 103, 20);

        label_anzeige_teile_id.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(label_anzeige_teile_id);
        label_anzeige_teile_id.setBounds(140, 100, 40, 20);

        label_bezeichnung.setFont(new java.awt.Font("Arial", 0, 12));
        label_bezeichnung.setText("Bezeichnung:");
        getContentPane().add(label_bezeichnung);
        label_bezeichnung.setBounds(190, 100, 80, 20);

        label_anzeige_bezeichnung.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(label_anzeige_bezeichnung);
        label_anzeige_bezeichnung.setBounds(270, 100, 150, 20);

        label_eingabeaufforderung_splitten.setFont(new java.awt.Font("Arial", 0, 12));
        label_eingabeaufforderung_splitten.setText("Bitte geben Sie die Fächer und die Menge an in die gesplittet werden soll:");
        getContentPane().add(label_eingabeaufforderung_splitten);
        label_eingabeaufforderung_splitten.setBounds(30, 130, 410, 20);

        label_splitten_nummer1.setFont(new java.awt.Font("Arial", 0, 12));
        label_splitten_nummer1.setText("1.");
        getContentPane().add(label_splitten_nummer1);
        label_splitten_nummer1.setBounds(30, 170, 20, 20);

        label_fachnummer1.setFont(new java.awt.Font("Arial", 0, 12));
        label_fachnummer1.setText("Fachnummer:");
        label_fachnummer1.setInheritsPopupMenu(false);
        getContentPane().add(label_fachnummer1);
        label_fachnummer1.setBounds(60, 170, 80, 20);

        fachnummer_textfeld1.setFont(new java.awt.Font("Arial", 0, 12));
        fachnummer_textfeld1.setFocusTraversalPolicyProvider(true);
        getContentPane().add(fachnummer_textfeld1);
        fachnummer_textfeld1.setBounds(150, 170, 80, 21);

        label_menge1.setFont(new java.awt.Font("Arial", 0, 12));
        label_menge1.setText("Menge:");
        getContentPane().add(label_menge1);
        label_menge1.setBounds(260, 170, 50, 20);

        menge_textfeld1.setFont(new java.awt.Font("Arial", 0, 12));
        getContentPane().add(menge_textfeld1);
        menge_textfeld1.setBounds(320, 170, 80, 21);

        kapazitaet_pruefen_button1.setFont(new java.awt.Font("Arial", 0, 12));
        kapazitaet_pruefen_button1.setText("Kapazität prüfen");
        getContentPane().add(kapazitaet_pruefen_button1);
        kapazitaet_pruefen_button1.setBounds(420, 170, 120, 23);

        label_splitten_nummer2.setFont(new java.awt.Font("Arial", 0, 12));
        label_splitten_nummer2.setText("2.");
        getContentPane().add(label_splitten_nummer2);
        label_splitten_nummer2.setBounds(30, 200, 20, 20);

        label_fachnummer2.setFont(new java.awt.Font("Arial", 0, 12));
        label_fachnummer2.setText("Fachnummer:");
        label_fachnummer2.setInheritsPopupMenu(false);
        getContentPane().add(label_fachnummer2);
        label_fachnummer2.setBounds(60, 200, 80, 20);

        fachnummer_textfeld2.setFont(new java.awt.Font("Arial", 0, 12));
        fachnummer_textfeld2.setFocusTraversalPolicyProvider(true);
        getContentPane().add(fachnummer_textfeld2);
        fachnummer_textfeld2.setBounds(150, 200, 80, 21);

        label_menge2.setFont(new java.awt.Font("Arial", 0, 12));
        label_menge2.setText("Menge:");
        getContentPane().add(label_menge2);
        label_menge2.setBounds(260, 200, 50, 20);

        menge_textfeld2.setFont(new java.awt.Font("Arial", 0, 12));
        getContentPane().add(menge_textfeld2);
        menge_textfeld2.setBounds(320, 200, 80, 21);

        kapazitaet_pruefen_button2.setFont(new java.awt.Font("Arial", 0, 12));
        kapazitaet_pruefen_button2.setText("Kapazität prüfen");
        getContentPane().add(kapazitaet_pruefen_button2);
        kapazitaet_pruefen_button2.setBounds(420, 200, 120, 23);

        fachnummer_textfeld3.setFont(new java.awt.Font("Arial", 0, 12));
        fachnummer_textfeld3.setFocusTraversalPolicyProvider(true);
        getContentPane().add(fachnummer_textfeld3);
        fachnummer_textfeld3.setBounds(150, 230, 80, 21);

        label_splitten_nummer3.setFont(new java.awt.Font("Arial", 0, 12));
        label_splitten_nummer3.setText("3.");
        getContentPane().add(label_splitten_nummer3);
        label_splitten_nummer3.setBounds(30, 230, 20, 20);

        menge_textfeld3.setFont(new java.awt.Font("Arial", 0, 12));
        getContentPane().add(menge_textfeld3);
        menge_textfeld3.setBounds(320, 230, 80, 21);

        label_menge3.setFont(new java.awt.Font("Arial", 0, 12));
        label_menge3.setText("Menge:");
        getContentPane().add(label_menge3);
        label_menge3.setBounds(260, 230, 50, 20);

        kapazitaet_pruefen_button3.setFont(new java.awt.Font("Arial", 0, 12));
        kapazitaet_pruefen_button3.setText("Kapazität prüfen");
        getContentPane().add(kapazitaet_pruefen_button3);
        kapazitaet_pruefen_button3.setBounds(420, 230, 120, 23);

        label_fachnummer3.setFont(new java.awt.Font("Arial", 0, 12));
        label_fachnummer3.setText("Fachnummer:");
        label_fachnummer3.setInheritsPopupMenu(false);
        getContentPane().add(label_fachnummer3);
        label_fachnummer3.setBounds(60, 230, 80, 20);

        menge_textfeld4.setFont(new java.awt.Font("Arial", 0, 12));
        getContentPane().add(menge_textfeld4);
        menge_textfeld4.setBounds(320, 260, 80, 21);

        label_fachnummer4.setFont(new java.awt.Font("Arial", 0, 12));
        label_fachnummer4.setText("Fachnummer:");
        label_fachnummer4.setInheritsPopupMenu(false);
        getContentPane().add(label_fachnummer4);
        label_fachnummer4.setBounds(60, 260, 80, 20);

        kapazitaet_pruefen_button4.setFont(new java.awt.Font("Arial", 0, 12));
        kapazitaet_pruefen_button4.setText("Kapazität prüfen");
        getContentPane().add(kapazitaet_pruefen_button4);
        kapazitaet_pruefen_button4.setBounds(420, 260, 120, 23);

        label_splitten_nummer4.setFont(new java.awt.Font("Arial", 0, 12));
        label_splitten_nummer4.setText("4.");
        getContentPane().add(label_splitten_nummer4);
        label_splitten_nummer4.setBounds(30, 260, 20, 20);

        label_menge4.setFont(new java.awt.Font("Arial", 0, 12));
        label_menge4.setText("Menge:");
        getContentPane().add(label_menge4);
        label_menge4.setBounds(260, 260, 50, 20);

        fachnummer_textfeld4.setFont(new java.awt.Font("Arial", 0, 12));
        fachnummer_textfeld4.setFocusTraversalPolicyProvider(true);
        getContentPane().add(fachnummer_textfeld4);
        fachnummer_textfeld4.setBounds(150, 260, 80, 21);

        label_fachnummer5.setFont(new java.awt.Font("Arial", 0, 12));
        label_fachnummer5.setText("Fachnummer:");
        label_fachnummer5.setInheritsPopupMenu(false);
        getContentPane().add(label_fachnummer5);
        label_fachnummer5.setBounds(60, 290, 80, 20);

        kapazitaet_pruefen_button5.setFont(new java.awt.Font("Arial", 0, 12));
        kapazitaet_pruefen_button5.setText("Kapazität prüfen");
        getContentPane().add(kapazitaet_pruefen_button5);
        kapazitaet_pruefen_button5.setBounds(420, 290, 120, 23);

        fachnummer_textfeld5.setFont(new java.awt.Font("Arial", 0, 12));
        fachnummer_textfeld5.setFocusTraversalPolicyProvider(true);
        getContentPane().add(fachnummer_textfeld5);
        fachnummer_textfeld5.setBounds(150, 290, 80, 21);

        menge_textfeld5.setFont(new java.awt.Font("Arial", 0, 12));
        getContentPane().add(menge_textfeld5);
        menge_textfeld5.setBounds(320, 290, 80, 21);

        label_splitten_nummer5.setFont(new java.awt.Font("Arial", 0, 12));
        label_splitten_nummer5.setText("5.");
        getContentPane().add(label_splitten_nummer5);
        label_splitten_nummer5.setBounds(30, 290, 20, 20);

        label_menge5.setFont(new java.awt.Font("Arial", 0, 12));
        label_menge5.setText("Menge:");
        getContentPane().add(label_menge5);
        label_menge5.setBounds(260, 290, 50, 20);

        label_fachnummer6.setFont(new java.awt.Font("Arial", 0, 12));
        label_fachnummer6.setText("Fachnummer:");
        label_fachnummer6.setInheritsPopupMenu(false);
        getContentPane().add(label_fachnummer6);
        label_fachnummer6.setBounds(60, 320, 80, 20);

        menge_textfeld6.setFont(new java.awt.Font("Arial", 0, 12));
        getContentPane().add(menge_textfeld6);
        menge_textfeld6.setBounds(320, 320, 80, 21);

        label_menge6.setFont(new java.awt.Font("Arial", 0, 12));
        label_menge6.setText("Menge:");
        getContentPane().add(label_menge6);
        label_menge6.setBounds(260, 320, 50, 20);

        label_splitten_nummer6.setFont(new java.awt.Font("Arial", 0, 12));
        label_splitten_nummer6.setText("6.");
        getContentPane().add(label_splitten_nummer6);
        label_splitten_nummer6.setBounds(30, 320, 20, 20);

        fachnummer_textfeld6.setFont(new java.awt.Font("Arial", 0, 12));
        fachnummer_textfeld6.setFocusTraversalPolicyProvider(true);
        getContentPane().add(fachnummer_textfeld6);
        fachnummer_textfeld6.setBounds(150, 320, 80, 21);

        kapazitaet_pruefen_button6.setFont(new java.awt.Font("Arial", 0, 12));
        kapazitaet_pruefen_button6.setText("Kapazität prüfen");
        getContentPane().add(kapazitaet_pruefen_button6);
        kapazitaet_pruefen_button6.setBounds(420, 320, 120, 23);

        menge_textfeld7.setFont(new java.awt.Font("Arial", 0, 12));
        getContentPane().add(menge_textfeld7);
        menge_textfeld7.setBounds(320, 350, 80, 21);

        label_splitten_nummer7.setFont(new java.awt.Font("Arial", 0, 12));
        label_splitten_nummer7.setText("7.");
        getContentPane().add(label_splitten_nummer7);
        label_splitten_nummer7.setBounds(30, 350, 20, 20);

        fachnummer_textfeld7.setFont(new java.awt.Font("Arial", 0, 12));
        fachnummer_textfeld7.setFocusTraversalPolicyProvider(true);
        getContentPane().add(fachnummer_textfeld7);
        fachnummer_textfeld7.setBounds(150, 350, 80, 21);

        kapazitaet_pruefen_button7.setFont(new java.awt.Font("Arial", 0, 12));
        kapazitaet_pruefen_button7.setText("Kapazität prüfen");
        getContentPane().add(kapazitaet_pruefen_button7);
        kapazitaet_pruefen_button7.setBounds(420, 350, 120, 23);

        label_menge7.setFont(new java.awt.Font("Arial", 0, 12));
        label_menge7.setText("Menge:");
        getContentPane().add(label_menge7);
        label_menge7.setBounds(260, 350, 50, 20);

        label_fachnummer7.setFont(new java.awt.Font("Arial", 0, 12));
        label_fachnummer7.setText("Fachnummer:");
        label_fachnummer7.setInheritsPopupMenu(false);
        getContentPane().add(label_fachnummer7);
        label_fachnummer7.setBounds(60, 350, 80, 20);

        label_splitten_nummer8.setFont(new java.awt.Font("Arial", 0, 12));
        label_splitten_nummer8.setText("8.");
        getContentPane().add(label_splitten_nummer8);
        label_splitten_nummer8.setBounds(30, 380, 20, 20);

        label_fachnummer8.setFont(new java.awt.Font("Arial", 0, 12));
        label_fachnummer8.setText("Fachnummer:");
        label_fachnummer8.setInheritsPopupMenu(false);
        getContentPane().add(label_fachnummer8);
        label_fachnummer8.setBounds(60, 380, 80, 20);

        fachnummer_textfeld8.setFont(new java.awt.Font("Arial", 0, 12));
        fachnummer_textfeld8.setFocusTraversalPolicyProvider(true);
        getContentPane().add(fachnummer_textfeld8);
        fachnummer_textfeld8.setBounds(150, 380, 80, 21);

        menge_textfeld8.setFont(new java.awt.Font("Arial", 0, 12));
        getContentPane().add(menge_textfeld8);
        menge_textfeld8.setBounds(320, 380, 80, 21);

        label_menge8.setFont(new java.awt.Font("Arial", 0, 12));
        label_menge8.setText("Menge:");
        getContentPane().add(label_menge8);
        label_menge8.setBounds(260, 380, 50, 20);

        kapazitaet_pruefen_button8.setFont(new java.awt.Font("Arial", 0, 12));
        kapazitaet_pruefen_button8.setText("Kapazität prüfen");
        getContentPane().add(kapazitaet_pruefen_button8);
        kapazitaet_pruefen_button8.setBounds(420, 380, 120, 23);

        label_fachnummer9.setFont(new java.awt.Font("Arial", 0, 12));
        label_fachnummer9.setText("Fachnummer:");
        label_fachnummer9.setInheritsPopupMenu(false);
        getContentPane().add(label_fachnummer9);
        label_fachnummer9.setBounds(60, 410, 80, 20);

        fachnummer_textfeld9.setFont(new java.awt.Font("Arial", 0, 12));
        fachnummer_textfeld9.setFocusTraversalPolicyProvider(true);
        getContentPane().add(fachnummer_textfeld9);
        fachnummer_textfeld9.setBounds(150, 410, 80, 21);

        kapazitaet_pruefen_button9.setFont(new java.awt.Font("Arial", 0, 12));
        kapazitaet_pruefen_button9.setText("Kapazität prüfen");
        getContentPane().add(kapazitaet_pruefen_button9);
        kapazitaet_pruefen_button9.setBounds(420, 410, 120, 23);

        label_splitten_nummer9.setFont(new java.awt.Font("Arial", 0, 12));
        label_splitten_nummer9.setText("9.");
        getContentPane().add(label_splitten_nummer9);
        label_splitten_nummer9.setBounds(30, 410, 20, 20);

        menge_textfeld9.setFont(new java.awt.Font("Arial", 0, 12));
        getContentPane().add(menge_textfeld9);
        menge_textfeld9.setBounds(320, 410, 80, 21);

        label_menge9.setFont(new java.awt.Font("Arial", 0, 12));
        label_menge9.setText("Menge:");
        getContentPane().add(label_menge9);
        label_menge9.setBounds(260, 410, 50, 20);

        menge_textfeld10.setFont(new java.awt.Font("Arial", 0, 12));
        getContentPane().add(menge_textfeld10);
        menge_textfeld10.setBounds(320, 440, 80, 21);

        fachnummer_textfeld10.setFont(new java.awt.Font("Arial", 0, 12));
        fachnummer_textfeld10.setFocusTraversalPolicyProvider(true);
        getContentPane().add(fachnummer_textfeld10);
        fachnummer_textfeld10.setBounds(150, 440, 80, 21);

        kapazitaet_pruefen_button10.setFont(new java.awt.Font("Arial", 0, 12));
        kapazitaet_pruefen_button10.setText("Kapazität prüfen");
        getContentPane().add(kapazitaet_pruefen_button10);
        kapazitaet_pruefen_button10.setBounds(420, 440, 120, 23);

        label_menge10.setFont(new java.awt.Font("Arial", 0, 12));
        label_menge10.setText("Menge:");
        getContentPane().add(label_menge10);
        label_menge10.setBounds(260, 440, 50, 20);

        label_splitten_nummer10.setFont(new java.awt.Font("Arial", 0, 12));
        label_splitten_nummer10.setText("10.");
        getContentPane().add(label_splitten_nummer10);
        label_splitten_nummer10.setBounds(30, 440, 20, 20);

        label_fachnummer10.setFont(new java.awt.Font("Arial", 0, 12));
        label_fachnummer10.setText("Fachnummer:");
        label_fachnummer10.setInheritsPopupMenu(false);
        getContentPane().add(label_fachnummer10);
        label_fachnummer10.setBounds(60, 440, 80, 20);

        splitten_button.setFont(new java.awt.Font("Arial", 0, 12));
        splitten_button.setText("Splitten");
        getContentPane().add(splitten_button);
        splitten_button.setBounds(570, 470, 90, 23);

        label_mindestgroesse.setFont(new java.awt.Font("Arial", 0, 12));
        label_mindestgroesse.setText("Mindestgröße:");
        getContentPane().add(label_mindestgroesse);
        label_mindestgroesse.setBounds(430, 100, 90, 20);

        label_anzeige_mindestgroesse.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(label_anzeige_mindestgroesse);
        label_anzeige_mindestgroesse.setBounds(530, 100, 30, 20);

        datei_menu.setText("Datei");
        jMenuBar1.add(datei_menu);

        bearbeiten_menu.setText("Bearbeiten");
        bearbeiten_menu.setDoubleBuffered(true);
        jMenuBar1.add(bearbeiten_menu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teile_Splitten.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teile_Splitten.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teile_Splitten.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teile_Splitten.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Teile_Splitten().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ausgangsfachnummer_textfeld;
    private javax.swing.JMenu bearbeiten_menu;
    private javax.swing.JButton bestaetigen_button;
    private javax.swing.JMenu datei_menu;
    private javax.swing.JTextField fachnummer_textfeld1;
    private javax.swing.JTextField fachnummer_textfeld10;
    private javax.swing.JTextField fachnummer_textfeld2;
    private javax.swing.JTextField fachnummer_textfeld3;
    private javax.swing.JTextField fachnummer_textfeld4;
    private javax.swing.JTextField fachnummer_textfeld5;
    private javax.swing.JTextField fachnummer_textfeld6;
    private javax.swing.JTextField fachnummer_textfeld7;
    private javax.swing.JTextField fachnummer_textfeld8;
    private javax.swing.JTextField fachnummer_textfeld9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton kapazitaet_pruefen_button1;
    private javax.swing.JButton kapazitaet_pruefen_button10;
    private javax.swing.JButton kapazitaet_pruefen_button2;
    private javax.swing.JButton kapazitaet_pruefen_button3;
    private javax.swing.JButton kapazitaet_pruefen_button4;
    private javax.swing.JButton kapazitaet_pruefen_button5;
    private javax.swing.JButton kapazitaet_pruefen_button6;
    private javax.swing.JButton kapazitaet_pruefen_button7;
    private javax.swing.JButton kapazitaet_pruefen_button8;
    private javax.swing.JButton kapazitaet_pruefen_button9;
    private javax.swing.JLabel label_anzeige_bezeichnung;
    private javax.swing.JLabel label_anzeige_mindestgroesse;
    private javax.swing.JLabel label_anzeige_teile_id;
    private javax.swing.JLabel label_ausgangsfachnummer;
    private javax.swing.JLabel label_bezeichnung;
    private javax.swing.JLabel label_eingabe_aufforderung_fachnummer;
    private javax.swing.JLabel label_eingabeaufforderung_splitten;
    private javax.swing.JLabel label_fachnummer1;
    private javax.swing.JLabel label_fachnummer10;
    private javax.swing.JLabel label_fachnummer2;
    private javax.swing.JLabel label_fachnummer3;
    private javax.swing.JLabel label_fachnummer4;
    private javax.swing.JLabel label_fachnummer5;
    private javax.swing.JLabel label_fachnummer6;
    private javax.swing.JLabel label_fachnummer7;
    private javax.swing.JLabel label_fachnummer8;
    private javax.swing.JLabel label_fachnummer9;
    private javax.swing.JLabel label_menge1;
    private javax.swing.JLabel label_menge10;
    private javax.swing.JLabel label_menge2;
    private javax.swing.JLabel label_menge3;
    private javax.swing.JLabel label_menge4;
    private javax.swing.JLabel label_menge5;
    private javax.swing.JLabel label_menge6;
    private javax.swing.JLabel label_menge7;
    private javax.swing.JLabel label_menge8;
    private javax.swing.JLabel label_menge9;
    private javax.swing.JLabel label_mindestgroesse;
    private javax.swing.JLabel label_splitten_nummer1;
    private javax.swing.JLabel label_splitten_nummer10;
    private javax.swing.JLabel label_splitten_nummer2;
    private javax.swing.JLabel label_splitten_nummer3;
    private javax.swing.JLabel label_splitten_nummer4;
    private javax.swing.JLabel label_splitten_nummer5;
    private javax.swing.JLabel label_splitten_nummer6;
    private javax.swing.JLabel label_splitten_nummer7;
    private javax.swing.JLabel label_splitten_nummer8;
    private javax.swing.JLabel label_splitten_nummer9;
    private javax.swing.JLabel label_teil_eingelagert;
    private javax.swing.JTextField menge_textfeld1;
    private javax.swing.JTextField menge_textfeld10;
    private javax.swing.JTextField menge_textfeld2;
    private javax.swing.JTextField menge_textfeld3;
    private javax.swing.JTextField menge_textfeld4;
    private javax.swing.JTextField menge_textfeld5;
    private javax.swing.JTextField menge_textfeld6;
    private javax.swing.JTextField menge_textfeld7;
    private javax.swing.JTextField menge_textfeld8;
    private javax.swing.JTextField menge_textfeld9;
    private javax.swing.JButton splitten_button;
    private javax.swing.JButton suchen_button;
    // End of variables declaration//GEN-END:variables
}
