/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */
package view;

/**
 *
 * @author Stephan
 */
public class Übersicht_Lagerverwaltung extends javax.swing.JFrame {

    /**
     * Creates new form Übersicht_Lagerverwaltung
     */
    public Übersicht_Lagerverwaltung() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        einlagernButton = new javax.swing.JButton();
        splittenButton = new javax.swing.JButton();
        einsehenButton = new javax.swing.JButton();
        HistorieButton = new javax.swing.JButton();
        verwaltenButton = new javax.swing.JButton();
        auslagernButton = new javax.swing.JButton();
        umlagernButton = new javax.swing.JButton();
        LagerverwaltungLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Datei = new javax.swing.JMenu();
        Bearbeiten = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        einlagernButton.setFont(new java.awt.Font("Arial", 0, 12));
        einlagernButton.setText("Teile einlager");
        einlagernButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                einlagernButtonActionPerformed(evt);
            }
        });
        getContentPane().add(einlagernButton);
        einlagernButton.setBounds(51, 84, 119, 23);

        splittenButton.setFont(new java.awt.Font("Arial", 0, 12));
        splittenButton.setText("Teile Splitten");
        getContentPane().add(splittenButton);
        splittenButton.setBounds(188, 125, 159, 23);

        einsehenButton.setFont(new java.awt.Font("Arial", 0, 12));
        einsehenButton.setText("Teilebestand einsehen");
        getContentPane().add(einsehenButton);
        einsehenButton.setBounds(188, 84, 159, 23);

        HistorieButton.setFont(new java.awt.Font("Arial", 0, 12));
        HistorieButton.setText("Historie einsehen");
        getContentPane().add(HistorieButton);
        HistorieButton.setBounds(188, 166, 159, 23);

        verwaltenButton.setFont(new java.awt.Font("Arial", 0, 12));
        verwaltenButton.setText("Teile verwalten");
        getContentPane().add(verwaltenButton);
        verwaltenButton.setBounds(51, 125, 119, 23);

        auslagernButton.setFont(new java.awt.Font("Arial", 0, 12));
        auslagernButton.setText("Teile auslagern");
        getContentPane().add(auslagernButton);
        auslagernButton.setBounds(51, 166, 119, 23);

        umlagernButton.setFont(new java.awt.Font("Arial", 0, 12));
        umlagernButton.setText("Teile umlagern");
        getContentPane().add(umlagernButton);
        umlagernButton.setBounds(51, 207, 119, 23);

        LagerverwaltungLabel.setFont(new java.awt.Font("Arial", 0, 12));
        LagerverwaltungLabel.setText("Lagerverwaltung");
        getContentPane().add(LagerverwaltungLabel);
        LagerverwaltungLabel.setBounds(126, 11, 91, 46);

        Datei.setText("Datei");
        jMenuBar1.add(Datei);

        Bearbeiten.setText("Edit");
        jMenuBar1.add(Bearbeiten);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void einlagernButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_einlagernButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_einlagernButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Übersicht_Lagerverwaltung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Übersicht_Lagerverwaltung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Übersicht_Lagerverwaltung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Übersicht_Lagerverwaltung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Übersicht_Lagerverwaltung().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Bearbeiten;
    private javax.swing.JMenu Datei;
    private javax.swing.JButton HistorieButton;
    private javax.swing.JLabel LagerverwaltungLabel;
    private javax.swing.JButton auslagernButton;
    private javax.swing.JButton einlagernButton;
    private javax.swing.JButton einsehenButton;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton splittenButton;
    private javax.swing.JButton umlagernButton;
    private javax.swing.JButton verwaltenButton;
    // End of variables declaration//GEN-END:variables
}
